{
  "hash": "faee4b93c8e8dd86dc6b3f7bb1ef367b",
  "result": {
    "markdown": "---\noutput: html_document\neditor_options: \n  chunk_output_type: console\nexecute:\n  warning: false\n  error: false\nformat: \n  html: \n    css: webex.css\n    include-after-body: webex.js\n    df-print: kable\neditor: \n  markdown: \n    wrap: 72\n---\n\n```{=html}\n<!-- Some considerations about about this quarto template \n-   Text within \\<! \\> will not show in your final document.\n    -   The other parts such as slashes (///), dashes (-) and tildes (\\~) are just aesthetic\n    -   These comments are used to explain the code chunks.\\\n    -   We refer to functions in curly brackets, e.g. {dplyr} and functions end in brackets, e.g. count()\\\n    -   This comment will not show up when you knit the document.\\\n    -   You can delete them if you want.\\ -->\n```\n\n<!--Below insert the name of the Case study. In curly brackets is the section reference name to be cross-references throughout the book -->\n\n# TBE - Linear regression (ENG) {.unnumbered}\n\n## Overview {.unnumbered}\n\n| **Case study characteristics** |                           |\n|--------------------------------|:--------------------------|\n| Name:                          | TBE - linear regression   |\n| Language:                      | English                   |\n| Tool:                          | R; DAGitty                         |\n| Location:                      | Germany                   |\n| Scale:                         | National                  |\n| Diseases:                      | TBE                       |\n| Keywords:                      | TBE; Linear Regression; R |\n| Technical complexity:          | Intermediate              |\n| Methodological complexity:     | Intermediate              |\n\n***Authorship***\\\nOriginal authors: Teresa Nygren (RKI), Alicia Barrasa Blanco (UK FETP),\nJan Walter (RKI) and Achim Dörre (RKI)\\\nData source: Data is fictional and was inspired by [Nygren et al. Tick-borne encephalitis: acute clinical manifestations and severity in 581 cases from Germany, 2018-2020. Journal of Infection. 2023 Apr 1;86(4):369-75](https://linkinghub.elsevier.com/retrieve/pii/S0163-4453(23)00088-9)\\\nAdapted by: Liese Van Gompel (MediPIET), Joana Gomes Dias (ECDC), Chiara\nEntradi (ECDC) and Alberto Mateo Urdiales (ISS)\\\n\n## Instructions\n\n### Getting Help\n\nThere are several ways to get help:\n\n1)  Look for the \"hints\" and solutions (see below)\n2)  Post a question in [Applied Epi\n    Community](www.community.appliedepi.org) with reference to this case\n    study\n\n### Hints and Solutions\n\nHere is what the \"helpers\" look like:\n\n<!--Note that this is the way of including hints and explanations to the solutions -->\n\n\n```{=html}\n<!--\nNOTE: Below is the hint (all within details tags collapsed)\n-->\n```\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nHere you will see a helpful hint!\n\n</br>\n\n</details>\n\n\n```{=html}\n<!--\nNOTE: Below is the solution (all within details tags collapsed)\n-->\n```\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see the solution\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nebola_linelist %>% \n  filter(\n    age > 25,\n    district == \"Bolo\"\n  )\n```\n:::\n\n\nHere is more explanation about why the solution works.\n\n</br>\n\n</details>\n\n\n```{=html}\n<!--\nNOTE: End of solution\n-->\n```\n\n<!-- NOTE ABOUT SOLUTIONS: When using {webexercises} the solution will be automatically highlighted, so you can change (if appropriate) the feature \"Click here to see the solution\" to  \"Click here to see the explanation of the solution\" -->\n\n#### Posting a question in the Community Forum\n\n... description here about posting in Community... TO BE COMPLETED BY\nAPPLIED EPI\n\n#### Terms of Use\n\n**Disclaimer**: The information presented in this exercise and the associated data files have been deliberately changed so as to facilitate the acquisition of the learning objectives for fellows of EPIET, EUPHEM and EPIET-associated programmes.\nThis case study was first introduced in 2022 (see Copyright and Licence agreement for more information).\n\n\nYou are free:\n\n-   to Share: to copy and distribute the work\n-   to Remix: to adapt and build upon the material\n\nUnder the following conditions:\n\n-   Attribution: You must attribute the work in the manner specified by\n    the author or licensor (but not in any way that suggests that they\n    endorse you or your use of the work). The best way to do this is to\n    keep as it is the list of contributors: sources, authors and\n    reviewers.\n\n-   Share Alike: If you alter, transform, or build upon this work, you\n    may distribute the resulting work only under the same or similar\n    license to this one. Your changes must be documented. Under that\n    condition, you are allowed to add your name to the list of\n    contributors.\n\n-   Notification: If you use the work in the manner specified by the\n    author or licensor, [Walter\\@rki.de](mailto:Walterj@rki.de)\n\n-   You cannot sell this work alone but you can use it as part of a\n    teaching.\n\nWith the understanding that:\n\n-   Waiver: Any of the above conditions can be waived if you get\n    permission from the copyright holder.\n\n-   Public Domain: Where the work or any of its elements is in the\n    public domain under applicable law, that status is in no way\n    affected by the license.\n\n-   Other Rights: In no way are any of the following rights affected by\n    the license:\n\n    -   Your fair dealing or fair use rights, or other applicable\n        copyright exceptions and limitations;\n\n    -   The author's moral rights;\n\n    -   Rights other persons may have either in the work itself or in\n        how the work is used, such as publicity or privacy rights.\n\n-   Notice: For any reuse or distribution, you must make clear to others\n    the license terms of this work by keeping together this work and the\n    current license.\n\nThis licence is based on\n<http://creativecommons.org/licenses/by-sa/3.0/>\n\n### Feedback & suggestions\n\n-   You can write feedback and suggestions on this case study at the\n    [GitHub issues page](https://github.com/appliedepi/case_studies)\n-   Alternatively email us at:\n    [contact\\@appliedepi.org](mailto:contact@appliedepi.org)\n\n\\pagebreak\n\n### Version and revisions\n\nWrite date of first version\n\nWrite any revisions made to the case study\n\n| Date | Changes made                             |                                     Author |\n|---------------------|:-------------------------------|------------------:|\n| 2023 | Revision R code                          |                Liese Van Gompel (MediPIET) |\n| 2024 | Revision R code                          | Joana Gomes Dias and Chiara Entradi (ECDC) |\n| 2024 | Revision of content, structure, R code and adaptation of format to Applied Epi's template of case studies |               Alberto Mateo Urdiales (ISS) |\n\n\\pagebreak\n\n## Guidance\n\n### Objectives of this case study\n\nAt the end of the case study, participants should be able to:\n\n-   Use directed acyclic graphs (DAG) to identify variables suitable to control for confounding;\n-   To perform linear regression in R;\n-   To write down the associated models and interpret them.\n\n### Previous level of expertise assumed\n\nParticipants are expected to be familiar with directed acyclic graphs (DAGs) and the use of DAGitty (a browser-based environment for creating DAGS) for the first part; and with data management as well as descriptive and stratified analysis in R for the second part.\n\n### Preparation for the case study\n\nInclude the steps needed to start replicating the analysis of the case\nstudy\n\nFor example:\n\n1.  Download folder named tbe_en and extract contents in the local laptop\n\n2. Create an Rstudio project in the folder tbe_en. If you are unsure on how to do that, read the EpiRhandbook Chapter on [R projects](https://epirhandbook.com/en/new_pages/r_projects.html)\n\n3. Inside the folder \"tbe_en\": Subfolder \"data\" contains a raw data file named *tbe.RDS*. This is the only data file you will use in this case study. \n\n4.  Subfolder scripts should be used to save any scripts related to the\n    analysis. Inside \"backup\" you will find a solution script with the code of the case study named *tbe_lr_backup.R*. You will also find an image which corresponds to the proposed DAG solution.\n    \n5.  Subfolder \"outputs\" could be used to store all outputs (tables, graphs,\n    documents) that are the result of the analysis\n\n6.  You will also find inside \"tbe_en\" a word document called *starter_guide_DAGitty.docx* in case you need help using this website\n\n# Introduction to the case study\nTick-borne encephalitis (TBE) is a vaccine-preventable, tick-borne viral infection. The typical disease course is biphasic, consisting of a first phase with general symptoms such as headache and fever, a symptom-free interval, and a second phase with neurological manifestations. Severity ranges from mild symptoms over meningitis to severe meningoencephalitis or -myelitis. Overall, 70–95% of infections remain sub-clinical and <1% die.\nAge, monophasic course, central nervous system (CNS) comorbidities, and general comorbidities were found to be independently associated with severe TBE in some analysis. Results were inconsistent regarding diabetes, male sex and other factors. Further possible predictors include blood type, ticks’ blood meal duration (proxy: large tick at removal), immunosuppression, autoimmune diseases, and chronic inflammatory comorbidities. \nIn Germany, laboratory diagnosis of acute TBE became statutorily notifiable in 2001. From 2018-2020, intensified surveillance was conducted. Primary aims were to assess clinical manifestations, health care utilisation, informal care, treatment practices, quality of life, and sick leave, as well as to identify factors associated with TBE severity\n\n**Note**: This introduction has been adapted from [Nygren et al. Tick-borne encephalitis: acute clinical manifestations and severity in 581 cases from Germany, 2018-2020. Journal of Infection. 2023 Apr 1;86(4):369-75](https://linkinghub.elsevier.com/retrieve/pii/S0163-4453(23)00088-9)\n\n\n# Overall goal\n\nYou are one of the epidemiologists in charge of the intensified surveillance system. Your boss asks you to test a hypothesis that **high blood pressure may also be causal for severe TBE**. As proxy for severe TBE, you will use the length of hospitalisation (number of days spent in hospital). \n\n## **Goal 1: Draw a Directed Acyclic Graph (DAG)**\n\nSince you are interested in a causal question, please draw a DAG. If you want to use a computer, you may try [http://www.dagitty.net/](http://www.dagitty.net/).\n\n-   Which variables would you need to adjust for?\n\nIf you are new to DAGitty you can find a few helpful information in the document called *starter_guide_DAGitty.docx* present in the \"tbe_en\" folder you have downloaded in your laptop (See **Preparation for the case study**).\n\nOnce you have drawn your DAG, click on the solution below to see the DAG we propose.\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see the solution\n\n</summary>\n\n</br>\n\nWhen planning the study, the epidemiologist considered this DAG:\n\n![](../images/tbe/tbe_dag.png)\n\n\n![](../images/tbe/legend_dag.png)\n\n</br>\n\n</details>\n\n\n\nAccording to this DAG, if you want to explore the association between hypertension and severe TBE, you should adjust for:\n\n-   TBE diagnosis\n\n-   TBE vaccination\n\n-   age\n\n-   large tick (=large viral load)\n\n-   monophasic course\n\n-   other comorbidities\n\n-   sex. \n\nTBE Diagnosis is controlled by design (only cases are included).\n\nProbably your DAG will look differently. This is absolutely fine, since there is not only one possible DAG. But you should be able to justify your DAG based on the existing evidence. \n\n\n\n\n\n## **Goal 2: Perform linear regression in R**\n\nNow we will work on the data frame provided which includes data for 523 patients who have been hospitalized with TBE in the years 2018 to 2020 in Germany and for whom data were collected. \n\nThe following variables are provided:\n\n*Table 1: Data dictionary for the dataframe “tbe.RDS”:*\n\n|**Variable** |\t**Description**|\t**Values**|\n|-------------|:---------------|:-----------|\n|age\t        |age in years             |\tcontinuous|\n|hyper        |hypertension             |\t1= yes, 0=no|\n|vac\t        |vaccinated against TBE   |\t1= yes, 0=no|\n|mono\t        |monophasic disease course|\t1= yes, 0=no|\n|other        |\tother comorbidities     |\t1= yes, 0=no|\n|tick         |\tlarge tick at removal   |\t1= yes, 0=no|\n|sex          |\tsex                     |\t1= female, 0= male|\n|hospd        |\tlength of hospitalisation in days|\tcontinuous|\n\n\n### **Step 1: Set up**\n\n#### Step 1.1: Create a new R script\n\nOnce you have created an Rproject inside the \"tbe_en\" folder (as specified in the second point of the section **Preparation for the case study**). Create a new script with the name *tbe_lr* and save it in the subfolder \"scripts\".\nIf you are familiar with Rmarkdown, you may decide to use this type of file instead of a standard R script.\n\n#### Step 1.2: Define R language\n\nDepending on where you are and how you carried out R installation, your language \"locale\" might be different from the language of the graphs that you want to produce. For example, a french person might have a french \"locale\". If that is the case, when creating a graph by day of the week, Monday will be displayed as \"lundi\". If that french person wants to create an English report, as for this case study, the language \"locale\" should be changed.\n\n**Task**: Ensure your \"locale\" is in English and change it into English if it is not. If you don't know how to do this try finding it online (searching for online help is an important skill for R users!). Otherwise, see the solution below\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n::: {.cell}\n\n```{.r .cell-code}\n# To see your language locale\nSys.getlocale()\n\n# To change it into English\nSys.setlocale(\"LC_ALL\", \"English\")\n```\n:::\n\n\n</br>\n\n</details>\n\n\n#### Step 1.3: Install/load packages\n\nInstall and load the following packages: rio, skimr, janitor, gtsummary, broom, rstatix, ggfortify and tidyverse.\n\nYou can find more about installing/loading packages in the [Packages](https://epirhandbook.com/en/new_pages/basics.html#packages) section of the EpiRhandbook. \n\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nYou may end up using a long list of packages. Unfortunately different packages have functions with the same name. For example, the package {dplyr} (already installed with {tidyverse}) has a function called `select()` which we frequently use to subset columns of a data frame. But other packages such as {MASS} do also have a function called `select()`. This could create headaches if you want to subset columns using dplyr's `select()` but R thinks you're calling MASS's `select()` (we call this masking - `dplyr::select()` is masked by `MASS::select()`). Given that you are more likely to use functions from {tidyverse}, ensure that this is the last package in your `p_load()` list so that functions from {tidyverse} (including {dplyr} functions) will always \"prevail\".\n\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ensures the package \"pacman\" is installed\nif (!require(\"pacman\")) {\n     install.packages(\"pacman\") }\n\n# install (if necessary) from CRAN and load packages to be used\npacman::p_load(\n  rio,        # importing data  \n  skimr,      # get overview of data\n  janitor,    # data cleaning and tables\n  gtsummary,  # summary statistics, tests and regressions \n  broom,      # to generate tidy tibbles of regression analysis\n  rstatix,    # for statistics, including statistical tests\n  ggfortify,  # data visualisation for statistical analysis results\n  tidyverse  # data management and visualization\n)\n```\n:::\n\n</br>\n\n</details>\n\n### **Step 2: Import and explore data**\n\n\n\n#### Step 2.1: Import the data and brief exploration\n\nImport the data frame called \"tbe.RDS\" inside the \"data\" subfolder. If you are working within a project, finding the path to the dataframe should be relatively straightfoward. An \".RDS\" file is an R object file. You can import this dataframe using the `readRDS()` function from {base}. However, we recommend that you use the **`import()`** function from {rio} because, as you may remember, this function will recognise the file type and import it whether the file is from R, Stata, excel or many others. If you have any doubts about importing review the [Import and export](https://epirhandbook.com/en/new_pages/importing.html#import-data) chapter of the EpiRhandbook.\n\n\nThen, explore the data trying to answer the following questions:\n\n::: {.webex-check}\n\n\nQUESTION: How many columns does the dataframe have? <div class='webex-radiogroup' id='radio_HGIEVEAXUT'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_HGIEVEAXUT\" value=\"\"></input> <span>523</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_HGIEVEAXUT\" value=\"\"></input> <span>2</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_HGIEVEAXUT\" value=\"answer\"></input> <span>8</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_HGIEVEAXUT\" value=\"\"></input> <span>6</span></label></div>\n\n:::\n\n\n::: {.webex-check}\n\n\nQUESTION: How many rows have missing the column 'Other comorbidities'? <div class='webex-radiogroup' id='radio_ABXKFOVGHR'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ABXKFOVGHR\" value=\"\"></input> <span>958</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ABXKFOVGHR\" value=\"answer\"></input> <span>22</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ABXKFOVGHR\" value=\"\"></input> <span>18</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ABXKFOVGHR\" value=\"\"></input> <span>39</span></label></div>\n\n:::\n\n::: {.webex-check}\n\n\nQUESTION: How many cases have hypertension? <div class='webex-radiogroup' id='radio_SEFLMYGCHK'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_SEFLMYGCHK\" value=\"answer\"></input> <span>119</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_SEFLMYGCHK\" value=\"\"></input> <span>191</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_SEFLMYGCHK\" value=\"\"></input> <span>332</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_SEFLMYGCHK\" value=\"\"></input> <span>285</span></label></div>\n\n:::\n\n::: {.webex-check}\n\n\nQUESTION: How many character columns does the dataframe have? <div class='webex-radiogroup' id='radio_HLVIWZEHSN'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_HLVIWZEHSN\" value=\"answer\"></input> <span>0</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_HLVIWZEHSN\" value=\"\"></input> <span>6</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_HLVIWZEHSN\" value=\"\"></input> <span>2</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_HLVIWZEHSN\" value=\"\"></input> <span>8</span></label></div>\n\n:::\n\n::: {.webex-check}\n\n\nQUESTION: What is the difference between a column of class 'character' and a column of class 'factor'? <div class='webex-radiogroup' id='radio_AWTEQZYPPS'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_AWTEQZYPPS\" value=\"\"></input> <span>There is no difference between these classes, those are synonims</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_AWTEQZYPPS\" value=\"\"></input> <span>Character columns contain text, whereas factors contain numbers</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_AWTEQZYPPS\" value=\"\"></input> <span>Factors are used when we have more than 5 categories of data</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_AWTEQZYPPS\" value=\"answer\"></input> <span>Both classes contain text, but factors are used when there are a limited number of unique character strings and they often represent categorical data</span></label></div>\n\n:::\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nAn efficient way to explore data is to use the function `skim()` from the {skimr} package, as it gives you all the information needed with only one command. Of course, there are several alternatives. \n\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Import the data\n\ntbe <- import(\"data/tbe.RDS\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Explore the dataframe\nskim(tbe)\n```\n\n::: {.cell-output-display}\nTable: Data summary\n\n|                         |     |\n|:------------------------|:----|\n|Name                     |tbe  |\n|Number of rows           |523  |\n|Number of columns        |8    |\n|_______________________  |     |\n|Column type frequency:   |     |\n|factor                   |6    |\n|numeric                  |2    |\n|________________________ |     |\n|Group variables          |None |\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts         |\n|:-------------|---------:|-------------:|:-------|--------:|:------------------|\n|hyper         |         0|          1.00|FALSE   |        2|no: 404, yes: 119  |\n|vac           |         0|          1.00|FALSE   |        2|no: 503, yes: 20   |\n|mono          |         0|          1.00|FALSE   |        2|no: 285, yes: 238  |\n|other         |        22|          0.96|FALSE   |        2|yes: 317, no: 184  |\n|tick          |         0|          1.00|FALSE   |        2|no: 345, yes: 178  |\n|sex           |         0|          1.00|FALSE   |        2|mal: 332, fem: 191 |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|  mean|    sd| p0| p25|  p50| p75| p100|hist                                     |\n|:-------------|---------:|-------------:|-----:|-----:|--:|---:|----:|---:|----:|:----------------------------------------|\n|age           |        18|          0.97| 47.30| 18.97|  1|  34| 47.0|  61|   90|▂▅▇▆▂ |\n|hospd         |        39|          0.93| 42.23| 13.59|  3|  33| 41.5|  52|   86|▁▆▇▃▁ |\n:::\n:::\n\n</br>\n\n</details>\n\n\nNormally, at this point we would start **cleaning** our data. Fortunately for you, the tbe data has already been cleaned, so you can jump directly to the fun part. However, feel free to rename/recode or change any aspect of the dataframe to accomodate it to your personal preferences.\n\n\n#### Step 2.2: Inspect factor columns\n\nAs we saw before, we have 6 factor columns representing categorical variables in our dataframe. Although we looked at them with the `skim()` function, explore them further with the `tabyl()` function from the {janitor} package.\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nTo save time, try to always use functions that allow you to apply the same function to many different objects (e.g., multiple columns) simultaneously. You can achieve this using several approaches, such as *loops*, *lapply* or *purrr*. Here we give the solution with *purrr*, so if you want to explore further purrr have a look at the dedicated [section](https://epirhandbook.com/new_pages/iteration.html#iter_purrr) in the EpiRhandbook.\n\n</br>\n\n</details>\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### One by one\ntabyl(tbe, hyper)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|hyper |   n|   percent|\n|:-----|---:|---------:|\n|no    | 404| 0.7724665|\n|yes   | 119| 0.2275335|\n\n</div>\n:::\n\n```{.r .cell-code}\ntabyl(tbe, vac)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|vac |   n|   percent|\n|:---|---:|---------:|\n|no  | 503| 0.9617591|\n|yes |  20| 0.0382409|\n\n</div>\n:::\n\n```{.r .cell-code}\n#### All at once\ntbe %>% \n  \n  select(where(is.factor)) %>% #we first select only the columns that are of class 'factor'\n  \n  map(.f = tabyl)              #inside map() from {purrr} we specify the function we want to apply to the entire dataframe\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$hyper\n .x[[i]]   n   percent\n      no 404 0.7724665\n     yes 119 0.2275335\n\n$vac\n .x[[i]]   n    percent\n      no 503 0.96175908\n     yes  20 0.03824092\n\n$mono\n .x[[i]]   n   percent\n      no 285 0.5449331\n     yes 238 0.4550669\n\n$other\n .x[[i]]   n    percent valid_percent\n      no 184 0.35181644     0.3672655\n     yes 317 0.60611855     0.6327345\n    <NA>  22 0.04206501            NA\n\n$tick\n .x[[i]]   n   percent\n      no 345 0.6596558\n     yes 178 0.3403442\n\n$sex\n .x[[i]]   n   percent\n    male 332 0.6347992\n  female 191 0.3652008\n```\n:::\n:::\n\n</br>\n\n</details>\n\n#### Step 2.3: Histogram with length of hospitalisation \nOur outcome variable will be length of hospitalisation in days (column *hospd*). It might be worth it looking at this column in more detail, as its characteristics may influence how will carry out the analysis later on. One important aspect is to check its distribution and ascertain, at least visually, if it follows a normal distribution.\n\n**Task** Create an histogram with the distribution of *hospd*. Try adding the normal curve to this histogram.\n\n::: {.webex-check}\n\n\nQUESTION: Does lenght of hospitalisation look like normally distributed? <div class='webex-radiogroup' id='radio_CVDZESIDCJ'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_CVDZESIDCJ\" value=\"answer\"></input> <span>Yes</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_CVDZESIDCJ\" value=\"\"></input> <span>No</span></label></div>\n\n:::\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nThere are many ways to create an histogram in R, but try using the package {ggplot2}. You can have a look at the \n[ggplot basics](https://epirhandbook.com/new_pages/ggplot_basics.html) chapter of the EpiRhandbook if you struggle.\n\nAdding the normal curve to the histogram may prove quite challenging. Do not worry if you don't manage. One hint is that, in the histogram, you will need to display the **density** and not the frequency count. Try asking a *search engine* or any *AI platform* for help. Most of us use these tools on a daily basis to ask for help in R.\n\n</br>\n\n</details>\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbe %>%                                  #we call the data first and we pass it into ggplot with the pipe operator\n  \n  ggplot(mapping = aes(x = hospd)) +     #when drawing an histogram we only need to specify the x-axis   \n  \n  geom_histogram(aes(y = ..density..)) + #here we are telling ggplot2 to display the density and not the freq count\n  \n  #the function below will add the normal curve. \n  stat_function(fun = dnorm,  #In the fun = argument we are specifying that we want the normal curve         \n                args = list(mean = mean(tbe$hospd, na.rm = T), #to draw a normal curve we need to give the mean and standard deviation of our column\n                            sd   = sd(tbe$hospd, na.rm = T)),  \n                \n                col = \"darkblue\", lwd = 1) # Identify the colour and line width of the normal curve\n```\n\n::: {.cell-output-display}\n![](tbe_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nNow, that was tough! But we're here to push you out of your comfort zone. Let's go into more detail about what we have done.\n\nBy now, you should feel comfortable creating a basic histogram using ggplot, so let's focus on the new things.\nWe have added another aesthetic to the `geom_histogram()` in which we specify that we want the density plotted and not the frequency count. **Why is that?** Displaying the density is more appropriate  when we want to focus on the shape of the data, as we can see the underlying probability distribution more clearly. \n\nBut, **what is actually the density?** The density represents the relative frequency, what we do is scale the y-axis so that the area under the histogram equals 1, normalising the histogram to represent probabilities (density) rather than raw counts. In fact, look at how the y-axis changes when you represent the density and when you represent the counts. \n\nFinally, **why are we putting two dots before and after density in the aes()?** The double dots before and after ..density.. are a special syntax used within ggplot2. They indicate an internal variable that ggplot2 calculates during the plotting process. So, ggplot2 normally calculates the density for histograms, but it does not display it unless you specify it (with this syntax).\n\n</br>\n\n</details>\n\n\n\n#### Step 2.4: Create a cross-table and calculate a statistical test\n\nLet's say that we now want to explore whether sex is associated with hypertension.\nTo find this out, create a cross-table displaying these two variables and calculate the appropriate statistical test to know if there is a statistical association between them.\n\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nThere are several ways in which you can do this. You could, for example, create the cross-table with `tabyl()` and then separately calculate the statistical test. The easiest way would be to use the `tbl_summary()` function from the {gtsummary} package, which allows you to do both, the cross tabulation and the statistical tests, in the same command. You should be familiar with this package by now, but if you need a little refresher have a look at the dedicated [chapter](https://epirhandbook.com/new_pages/stat_tests.html#stats_gt) of the EpiRhandbook.\n\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbe %>% \n  select(hyper, sex) %>%   #we select the columns we are interested in\n  tbl_summary(by = hyper) %>% #we specify that we want by hypertension status\n  add_p()                     # adding this command will calculate the most appropriate statistical test\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"afthkswpgr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#afthkswpgr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#afthkswpgr thead, #afthkswpgr tbody, #afthkswpgr tfoot, #afthkswpgr tr, #afthkswpgr td, #afthkswpgr th {\n  border-style: none;\n}\n\n#afthkswpgr p {\n  margin: 0;\n  padding: 0;\n}\n\n#afthkswpgr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#afthkswpgr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#afthkswpgr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#afthkswpgr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#afthkswpgr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#afthkswpgr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#afthkswpgr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#afthkswpgr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#afthkswpgr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#afthkswpgr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#afthkswpgr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#afthkswpgr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#afthkswpgr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#afthkswpgr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#afthkswpgr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#afthkswpgr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#afthkswpgr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#afthkswpgr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#afthkswpgr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#afthkswpgr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#afthkswpgr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#afthkswpgr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#afthkswpgr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#afthkswpgr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#afthkswpgr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#afthkswpgr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#afthkswpgr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#afthkswpgr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#afthkswpgr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#afthkswpgr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#afthkswpgr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#afthkswpgr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#afthkswpgr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#afthkswpgr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#afthkswpgr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#afthkswpgr .gt_left {\n  text-align: left;\n}\n\n#afthkswpgr .gt_center {\n  text-align: center;\n}\n\n#afthkswpgr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#afthkswpgr .gt_font_normal {\n  font-weight: normal;\n}\n\n#afthkswpgr .gt_font_bold {\n  font-weight: bold;\n}\n\n#afthkswpgr .gt_font_italic {\n  font-style: italic;\n}\n\n#afthkswpgr .gt_super {\n  font-size: 65%;\n}\n\n#afthkswpgr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#afthkswpgr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#afthkswpgr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#afthkswpgr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#afthkswpgr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#afthkswpgr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#afthkswpgr .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;no&lt;/strong&gt;, N = 404&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>no</strong>, N = 404<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;yes&lt;/strong&gt;, N = 119&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>yes</strong>, N = 119<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;2&lt;/sup&gt;&lt;/span&gt;\"><strong>p-value</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>2</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sex</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.5</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    male</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">253 (63%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">79 (66%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    female</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">151 (37%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">40 (34%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> n (%)</td>\n    </tr>\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>2</sup></span> Pearson’s Chi-squared test</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n</br>\n\n</details>\n\n\nAs you can see, there isn't a significant association between sex and hypertension. \n\n### **Step 3: Check if there is a linear association between length of hospitalisation and age**\n\nAge is a potential confounder for a more severe course of TBE involving a longer stay in hospital, for which we would like to adjust. Since age is a continuous variable, we could include it in the regression model in various ways (e.g. as a continuous variable, in categories, by transforming it, etc.). In order to decide this, we need to analyze the association of age with the length of hospitalisation.\n\n\n#### Step 3.1: Inspect a potential linear association\n\nPlease first have a look at the relationship between age and length of hospitalisation using a scatterplot. \n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbe %>%    \n  \n  ggplot(mapping = aes(x = age,        # we put length of hospitalisation on the y-axis because this axis usually contains the dependent variable; and here we want to know if hospd depends on age\n                       y = hospd)) +    \n  \n  geom_point() +                       # this geometry will create a scatterplot\n    \n  scale_x_continuous(name = \"Age\" , limits = c(0,100)) +          # Format the x-axis to a range between 0 and 100 \n  \n  scale_y_continuous(limits = c(0,70)) +                          # Format the y axis to a range between 0 and 70\n  \n  labs(\n    x = \"Age\",\n    y = \"Length of hospitalisation in days\"\n  ) + \n  \n  \n  theme_bw()                            # Add a pre-defined theme for formatting\n```\n\n::: {.cell-output-display}\n![](tbe_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n</br>\n\n</details>\n\n\nWhat do you think? Is there a linear association? How can you be sure? Add a linear model trend line to help you with the interpretation. \n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nFor the trend line, you can add a `geom_smooth()` geometry. Look up the documentation for geom_smooth (you can type `?geom_smooth()` in the console and press \"Enter\") and search for the methods option.For a linear trend line you can assign the methods argument to “lm” (linear model).\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbe %>%    \n  \n  ggplot(mapping = aes(x = age,        # we put length of hospitalisation on the y-axis because this axis usually contains the dependent variable; and here we want to know if hospd depends on age\n                       y = hospd)) +    \n  \n  geom_point() +                       # this geometry will create a scatterplot\n  \n  geom_smooth(method = lm) +           # this geometry will add a trend line. \"lm\" is for \"linear model\"\n  \n  scale_x_continuous(name = \"Age\" , limits = c(0,100)) +          # Format the x-axis to a range between 0 and 100 \n  \n  scale_y_continuous(limits = c(0,70)) +                          # Format the y axis to a range between 0 and 70\n  \n  labs(\n    x = \"Age\",\n    y = \"Length of hospitalisation in days\"\n  ) + \n  \n  \n  theme_bw()                            # Add a pre-defined theme for formatting\n```\n\n::: {.cell-output-display}\n![](tbe_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n</br>\n\n</details>\n\nNow you have visual evidence of a linear association of age with the duration of hospitalisation. Therefore, **it seems reasonable to include age as a continuous variable in the analysis.**\n\n#### Step 3.2: Check if the association between age and length of hospitalisation varies by sex\nNow, check visually whether the association between age and hospd differs by sex\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nYou may choose to create separate graphs adding a `facet_grid()` to your `ggplot()` (try looking up the syntax yourself). You may also decide to use colour coding to differentiate between factor levels of sex. For the latter, where do you think you should specify the colour, inside or outside the `aes()`? Read this [section](https://epirhandbook.com/new_pages/ggplot_basics.html#ggplotgroups) of the EpiRhandbook if you have doubts.\n\n</br>\n\n</details>\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# As separate graphs\ntbe %>%    \n  \n  ggplot(mapping = aes(x = age,        # we put length of hospitalisation on the y-axis because this axis usually contains the dependent variable; and here we want to know if hospd depends on age\n                       y = hospd)) +    \n  \n  geom_point() +                       # this geometry will create a scatterplot\n  \n  geom_smooth(method = lm) +           # this geometry will add a trend line. \"lm\" is for \"linear model\"\n  \n  facet_grid(~sex)  +                   # adding this function will generate a separate graph for each category of sex\n\n  \n  scale_x_continuous(name = \"Age\" , limits = c(0,100)) +          # Format the x-axis to a range between 0 and 100 \n  \n  scale_y_continuous(limits = c(0,70)) +                          # Format the y axis to a range between 0 and 70\n  \n  labs(\n    x = \"Age\",\n    y = \"Length of hospitalisation in days\"\n  ) + \n  \n  \n  theme_bw()                            # Add a pre-defined theme for formatting\n```\n\n::: {.cell-output-display}\n![](tbe_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Same graphs with different colours\ntbe %>%    \n  \n  ggplot(mapping = aes(x = age,        # we put length of hospitalisation on the y-axis because this axis usually contains the dependent variable; and here we want to know if hospd depends on age\n                       y = hospd,\n                       colour = sex )) + #we add the colour in the aes so that it varies according to the categories of sex   \n  \n  geom_point() +                       # this geometry will create a scatterplot\n  \n  geom_smooth(method = lm) +           # this geometry will add a trend line. \"lm\" is for \"linear model\"\n  \n  scale_x_continuous(name = \"Age\" , limits = c(0,100)) +          # Format the x-axis to a range between 0 and 100 \n  \n  scale_y_continuous(limits = c(0,70)) +                          # Format the y axis to a range between 0 and 70\n  \n  labs(\n    x = \"Age\",\n    y = \"Length of hospitalisation in days\"\n  ) + \n  \n  \n  theme_bw()                            # Add a pre-defined theme for formatting\n```\n\n::: {.cell-output-display}\n![](tbe_files/figure-html/unnamed-chunk-18-2.png){width=672}\n:::\n:::\n\n\n\n</br>\n\n</details>\n\n-   **What do you observe?**\nThe lines for female and male patients have different slopes, indicating that the association between age and hospitalisation days is modified by sex.\n\n-   **Why does this matter?**\nSince there are different effects of age on the length of the hospitalisation by sex, you may want to control for this.\n\n\n### **Step 4: Check if there is a difference in length of hospitalisation by hypertension status**\nLet's now focus on our exposure of interest (hypertension). We can check whether TBE cases with high blood pressure have a significant longer stay in hospital compared with those without high blood pressure either by carrying out a simple statistical test or through univariate regression. We will do both.\n\n#### Step 4.1: Simple statistical test\nOne way would be to carry out a **simple statistical test** which enables us to ascertain if there is a significant difference between groups. As you know, the choice of statistical test will be determined by the number of groups that we have and the nature of the variables. If you don't remember well how to choose the appropriate statistical test have a look at this [BMJ article](https://www.bmj.com/about-bmj/resources-readers/publications/statistics-square-one/13-study-design-and-choosing-statisti)\n\n::: {.webex-check}\n\n\nQUESTION: What simple statistical tests do you think would be most appropriate in this case? <div class='webex-radiogroup' id='radio_KOTWNEAQVA'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_KOTWNEAQVA\" value=\"\"></input> <span>Chi-square or Fisher&apos;s exact test</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_KOTWNEAQVA\" value=\"\"></input> <span>ANOVA or Kruskal Wallis</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_KOTWNEAQVA\" value=\"answer\"></input> <span>Student t test or Mann Whitney/Wilcoxon rank-sum test</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_KOTWNEAQVA\" value=\"\"></input> <span>McNemar&apos;s test or Spears Rank</span></label></div>\n\n:::\n\n\nIn this case we have independent data, two groups (hypertension yes/no) and a quantitative dependent outcome (length of hospitalisation), so we will choose either a **t-test** or **Wilcoxon rank-sum test** (also known as Mann-Whitney). We'd do a t-test if length of hospitalisation is normally distributed and Wilcoxon if it isn't. We already checked in **Step 2.3** that the distribution of *hospd* looked normal from the histogram, let's now have a look if the distribution looks normal for both categories of hypertension: hypertension-yes and hypertension-no.\n\n**Task** Check visually whether length of hospitalisation is normally distributed for both categories of hypertension. \n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nA simple way to check this is by generating a histogram for *hospd* using ggplot(). Stratification by *hyper* is easily done by adding a `facet_grid()` to your ggplot, as we have already seen with the scatterplot. Looking at the frecuency distribution of \"hospd\" by \"hypertension\" can already give us an idea of whether the data is normally distributed or not.However, if we want to to add a normal curve, we'd need to plot the density and not the frequency, as you may rembember from the histogram we built above in **Sep 2.3**. \n</br>\n\n</details>\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the frecuency distribution by hypertension status\ntbe %>%\n  \n  ggplot(mapping = aes(x = hospd)) +\n  \n    geom_histogram() + \n    \n    facet_grid(~hyper) # add facet_grid() to get a graph for each hyper status\n```\n\n::: {.cell-output-display}\n![](tbe_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Plot the density and add a  normal curve\ntbe %>%                                  \n  \n  ggplot(mapping = aes(x = hospd, fill = hyper)) +  #remember that for bars, fill is is the interior colour     \n  \n    geom_histogram(aes(y = ..density..)) + #here we are telling ggplot2 to display the density and not the freq count\n  \n    facet_grid(~hyper) + # add facet_grid() to get a graph for each hyper status\n\n    #the function below will add the normal curve. \n    stat_function(fun = dnorm,  #The fun = argument we are specifying that we want the normal curve         \n                args = list(mean = mean(tbe$hospd, na.rm = T), #to draw a normal curve we need to give the mean and standard deviation of our column\n                            sd   = sd(tbe$hospd, na.rm = T)),  \n                \n                col = \"darkblue\", lwd = 1) + # Identify the colour and line width of the normal curve\n    labs(\n      x = \"Length of hospitalisation in days\",\n      y = \"Density\"\n      )\n```\n\n::: {.cell-output-display}\n![](tbe_files/figure-html/unnamed-chunk-20-2.png){width=672}\n:::\n:::\n\n\n\n</br>\n\n</details>\n\n\nFrom the graphs looks like the data is normally distributed, but there is a test we can do to determine this: **Shapiro-Wilk test**. \n\n**Task**: Use the Shapiro test to determine whether length of hospitalisation comes from a normally-distributed population.\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nYou can choose {base} functions to carry out the Shapiro test (and any other statistical test) or functions from the {rstatix} package. Here we will use the latter, because {rstatix} has a syntax that is compatible with {dplyr}, which can be an advantage. In any case the name of the functions are very similar. For example, using {base} the Shapiro test function is `shapiro.test()`; and with {rstatix} the same function is written as: `shapiro_test()`. If you want to know more about how to carry out simple statistical tests in R, read the EpiRhandbook Chapter on [Simple statistical tests](https://epirhandbook.com/new_pages/stat_tests.html)\n\n</br>\n\n</details>\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbe %>%\n  \n  group_by(hyper) %>% #we first group by out independent or exposure variable\n  \n  \n  shapiro_test(hospd)  # this function performs the Shapiro-Wilk test for all groups separately\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|hyper |variable | statistic|         p|\n|:-----|:--------|---------:|---------:|\n|no    |hospd    | 0.9946512| 0.2207864|\n|yes   |hospd    | 0.9870178| 0.3632204|\n\n</div>\n:::\n:::\n\n\n\n</br>\n\n</details>\n\n\nThe null hypothesis of Shapiro'test is that data is normally distributed. As our results were non-significant (p>0.05) we cannot reject such null hypothesis. In other words, we can conclude that data is normally distributed.\n\n*Note*: A statistician, or an epidemiologist pretending to be a statistician, would feel very uncomfortable by the conclusion written above. When we are unable to reject a null hypothesis we cannot conclude that this hypothesis (in this case that data is normally distributed) is true, but we should simply state that we were unable to reject it. However, in practical terms, by carrying out a Shapiro test we are assuming that the data is normally distributed....so word it as you like, but the consequences are the same.\n\n\n::: {.webex-check}\n\n\nQUESTION: Now that we know that the data is normally distributed, what test should we carry out? <div class='webex-radiogroup' id='radio_GPIWZJHFJG'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_GPIWZJHFJG\" value=\"answer\"></input> <span>Student t-test</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_GPIWZJHFJG\" value=\"\"></input> <span>Wilcoxon rank-sum test</span></label></div>\n\n:::\n\n**Task** Carry out the statistical test to ascertain if there are significant differences in length of hospitalisation according to hypertension status\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbe %>%\n  \n  t_test(hospd ~ hyper)  # we write first our dependent variable and then the exposure one\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|.y.   |group1 |group2 |  n1|  n2| statistic|       df|       p|\n|:-----|:------|:------|---:|---:|---------:|--------:|-------:|\n|hospd |no     |yes    | 373| 111| -2.706422| 181.4443| 0.00745|\n\n</div>\n:::\n:::\n\n\n\n</br>\n\n</details>\n\n\n::: {.webex-check}\n\n\nQUESTION: Is there a significant difference in the length of hospitalisation among patients with and without hypertension? <div class='webex-radiogroup' id='radio_ENIKPUNFBT'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ENIKPUNFBT\" value=\"answer\"></input> <span>Yes</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ENIKPUNFBT\" value=\"\"></input> <span>No</span></label></div>\n\n:::\n\n\n*Note*: In large datasets (as this one) the Shapiro-Wilk test may reject the normality hypothesis even though the deviation from the normal distribution is rather small. In this case you may still choose to calculate the t-test despite the violation of the normality assumption. This is acceptable because for large samples, the error imposed by t-test approximation is negligible.\n\n\n#### Step 4.2: Univariate linear regression between hospd and hyper\nThe other way was through univariate regression. Carry out a univariate linear regression with length of hospitalisation (hospd) as the dependent variable and hypertension as the independent variable. Assign this model to an object named: *hyper_hospd_lm*. If this is the first time doing regression in R, have a look at the [Univariate](https://epirhandbook.com/new_pages/regression.html#univariate) regression chapter of the EpiRhandbook.\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nAs we are doing linear regression, we could use the `lm()` function from {base} to analyse the association between hypertension and length of hospitalisation. The syntax is: lm(outcome/dependent variable ~ exposure/independent variable, data = dataframe) You can print the model output in a subsequent command using the `summary()` function. However, the `tidy()` function from {broom} provides an overview which can be more easily compiled and used in down-stream analyses if needed.\n\nThe approach described above is the {base} R approach. You can also perform univariate regression analysis using the function `tbl_uvregression()` from the {gtsummary} package. If you want to explore this alternative approach further read the dedicated EpiRhandbook [chapter](https://epirhandbook.com/new_pages/regression.html#reg_gt_uni)\n</br>\n\n</details>\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#First we write the formula (lm stands for linear model) and assign the model to an object\nhyper_hospd_lm <- lm(hospd ~ hyper, data= tbe)\n\n# Prin the detailed output of the model\nsummary(hyper_hospd_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = hospd ~ hyper, data = tbe)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-38.324  -9.324  -1.261   9.676  44.676 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  41.3244     0.6991  59.113  < 2e-16 ***\nhyperyes      3.9369     1.4598   2.697  0.00724 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 13.5 on 482 degrees of freedom\n  (39 observations deleted due to missingness)\nMultiple R-squared:  0.01487,\tAdjusted R-squared:  0.01282 \nF-statistic: 7.273 on 1 and 482 DF,  p-value: 0.007243\n```\n:::\n\n```{.r .cell-code}\n# Print the main model parameters\nresults_hyper_hospd_lm <- tidy(hyper_hospd_lm) \nresults_hyper_hospd_lm\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |  estimate| std.error| statistic|   p.value|\n|:-----------|---------:|---------:|---------:|---------:|\n|(Intercept) | 41.324397| 0.6990698| 59.113403| 0.0000000|\n|hyperyes    |  3.936864| 1.4597610|  2.696924| 0.0072434|\n\n</div>\n:::\n:::\n\n\n\n</br>\n\n</details>\n\n\n::: {.webex-check}\n\n\nQUESTION: Based on the results of this model, is there a significant association between hypertension and hospd? <div class='webex-radiogroup' id='radio_HCUWTGBPBX'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_HCUWTGBPBX\" value=\"answer\"></input> <span>Yes</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_HCUWTGBPBX\" value=\"\"></input> <span>No</span></label></div>\n\n:::\n\n\n::: {.webex-check}\n\n\nQUESTION: How much does having hypertension increase length of hospitalisation (in days)? <div class='webex-radiogroup' id='radio_EQEJHFNHPS'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_EQEJHFNHPS\" value=\"answer\"></input> <span>3.9</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_EQEJHFNHPS\" value=\"\"></input> <span>41.3</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_EQEJHFNHPS\" value=\"\"></input> <span>1.46</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_EQEJHFNHPS\" value=\"\"></input> <span>1.2</span></label></div>\n\n:::\n\n\n::: {.webex-check}\n\n\nQUESTION: What % of the variability in length of hospitalisation can be explained by hypertension? <div class='webex-radiogroup' id='radio_VHQLMUVBMZ'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_VHQLMUVBMZ\" value=\"\"></input> <span>2.7%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_VHQLMUVBMZ\" value=\"\"></input> <span>41%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_VHQLMUVBMZ\" value=\"answer\"></input> <span>1.3%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_VHQLMUVBMZ\" value=\"\"></input> <span>3%</span></label></div>\n\n:::\n\n\nIn this case the regression equation is: $hopsd(predicted)=41.3+3.9⋅hyper$.\n\nNow let's go through the outputs of the model. \nWe will first review the outputs of the `tidy()` function. As explained before, the advantage of using `tidy()` is that we can save the output as an object for further manipulation. Also, `tidy()` keeps what we would normally need in epidemiology for the interpretation of the model:\n\nWe have four columns and two rows. The rows refer to the **intercept** (baseline value for hospd when there is NO hypertension: 41.3) and our only exposure/predictor (hypertension). \nIn most cases, you will be interested in the row for **hypertension** (your predictor) and in the columns **estimate** and **p.value**. The **estimate** of hypertension tells us the estimated change in hospd when you go from NO hypertension to YES hypertension (that's why it is written as *hyperyes*). In this case, it’s approximately 3.94, meaning that having hypertension is associated with an increase in 3.94 days of hospitalisation. The column **p.value** tells us whether this estimate is statistically significant.\n\n**This is most of what you need to know to be a functional epidemiologist**. But if you want to know more, we will explain the rest of the elements of the output of both functions:  \n\nThe column **std.error** provides an estimate of the variability or uncertainty associated with the estimate. In this case it means that the estimated effect of hypertension on hospitalisation duration (hospd) is expected to vary by about 1.46 days (on average) due to sampling variability. Finally, the **statistic** column gives us a value of the statistical test (t-test in this case) used to ascertain if the estimate is significantly different from 0 (normally you can ignore this column). \n\n\nYou may have noticed that the `summary()` output has more information than the `tidy()` output. Here we leave a brief explanation on what each part of the `summary()` output means:\n\n\n**Call:** This line shows the formula used for the regression model. \n\n**Residuals:** These are the differences between the actual hospd values and the predicted values from the regression model. The summary provides statistics like minimum, median, and maximum residuals.\n\n**Coefficients:** This is the bit that interests us the most: \n\n-   **Intercept**: The estimated intercept (baseline value) for hospd when age is zero. In this case, it’s approximately 41.3.\n-   **hyperyes:** The estimated change in hospd when you go from NO hypertension to YES hypertension. Here, it’s approximately 3.9. The t-value and **p-value** indicate whether this coefficient is statistically significant.\n\n**Significance Codes:** Indicate whether the p-value is highly significant (*** p < 0.001) or only marginally significant (* p<0.05)\n\n**Residual Standard Error:** This measures the average deviation of the observed hospd values from the regression line. In this case, it’s approximately 13.5.\n\n**Multiple and Adjusted R-squared:** These values (0.01487 and 0.01282) represent the proportion of variance in hospd explained by the linear relationship with hypertension. Higher values indicate better fit. The adjusted one is adjusted for the number of predictors. In this case we could say that around 1.3% of the variability in hospd is explained by hypertension.\n\n**F-statistic and p-value:** The F-statistic tests whether the overall model (including all predictors) is significant. A low p-value (like this one, < 0.007243) indicates that the model is significant.\n\n\n### **Step 5: Check if there is a linear association between length of hospitalisation and the rest of variables**\n\nWe also need to know if there is a univariate association between our outcome (length of hospitalisation) and the confounders we may want to introduce in our model. We will do this in two steps, first with the continous variable and then with the factor variables. \n\n#### Step 5.1: Univariate linear regression between length of hospitalisation and age\n\nTry running a linear regression model with length of hospitalisation (hospd) as the dependent variable and age as the independent variable. \n\n::: {.webex-check}\n\n\nQUESTION: Based on the results of the model, is there a significant association between age and hospd? <div class='webex-radiogroup' id='radio_KSTTTTJTTN'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_KSTTTTJTTN\" value=\"answer\"></input> <span>Yes</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_KSTTTTJTTN\" value=\"\"></input> <span>No</span></label></div>\n\n:::\n\n\n::: {.webex-check}\n\n\nQUESTION: How much does an additional year of age increase length of hospitalisation (in days)? <div class='webex-radiogroup' id='radio_FTAPHBZIUA'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_FTAPHBZIUA\" value=\"answer\"></input> <span>0.372</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_FTAPHBZIUA\" value=\"\"></input> <span>24.5</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_FTAPHBZIUA\" value=\"\"></input> <span>0.271</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_FTAPHBZIUA\" value=\"\"></input> <span>1.42</span></label></div>\n\n:::\n\n\n::: {.webex-check}\n\n\nQUESTION: What % of the variability in length of hospitalisation can be explained by age? <div class='webex-radiogroup' id='radio_NCQRAJZZXR'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NCQRAJZZXR\" value=\"\"></input> <span>65%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NCQRAJZZXR\" value=\"\"></input> <span>15%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NCQRAJZZXR\" value=\"answer\"></input> <span>27%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NCQRAJZZXR\" value=\"\"></input> <span>99%</span></label></div>\n\n:::\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run the linear regression and assign the output to age_hospd_lm\nage_hospd_lm <- lm(hospd ~ age, data = tbe)\n\n# Print the results using the summary() function\nsummary(age_hospd_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = hospd ~ age, data = tbe)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-35.676  -7.893   0.521   6.844  32.279 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  24.5314     1.4233   17.24   <2e-16 ***\nage           0.3722     0.0278   13.39   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 11.61 on 482 degrees of freedom\n  (39 observations deleted due to missingness)\nMultiple R-squared:  0.2711,\tAdjusted R-squared:  0.2696 \nF-statistic: 179.2 on 1 and 482 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n# Print the results of the regression analysis with the tidy() function\ntidy(age_hospd_lm)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |   estimate| std.error| statistic| p.value|\n|:-----------|----------:|---------:|---------:|-------:|\n|(Intercept) | 24.5314214| 1.4232588|  17.23609|       0|\n|age         |  0.3722366| 0.0278031|  13.38831|       0|\n\n</div>\n:::\n:::\n\n\n\n</br>\n\n</details>\n\n#### Step 5.2: Univariate linear regression between length of hospitalisation and factor variables\nNow carry out a similar univariate model for each of the factor variables that we have not explored to ascertain which ones are significantly associated with length of hospitalisation.\n\n::: {.webex-check}\n\n\nQUESTION: What of the following variables have a significant linear association with length of hospitalisation? <div class='webex-radiogroup' id='radio_NGEXVHQFTX'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NGEXVHQFTX\" value=\"answer\"></input> <span>Sex</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NGEXVHQFTX\" value=\"answer\"></input> <span>Other comorbidities</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NGEXVHQFTX\" value=\"answer\"></input> <span>Monophasic disease</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NGEXVHQFTX\" value=\"\"></input> <span>Large tick at removal</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NGEXVHQFTX\" value=\"answer\"></input> <span>Vaccinated against TBE</span></label></div>\n\n:::\n\n\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nWe have seen already how to write a linear formula with `lm()`. You can then use either `summary()` from {base} or `tidy()` from {broom} to look at the coefficient and significance value. You could write these functions for each variable, but you could also try to use map() from {purrr} to do them all at once, as we did in the **Step 2.2**. Have a look at the Chapter on  [Purrr](https://epirhandbook.com/new_pages/iteration.html#iter_purrr) in the EpiRhandbook if you have any doubts.\n\n</br>\n\n</details>\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Here we write one by one for each variable the formula and tidy\n\n#sex\nsex_hospd_lm <- lm(hospd ~ sex, data = tbe)\ntidy(sex_hospd_lm)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |  estimate| std.error| statistic| p.value|\n|:-----------|---------:|---------:|---------:|-------:|\n|(Intercept) |  46.66559| 0.6932755|  67.31176|       0|\n|sexfemale   | -12.41704| 1.1595927| -10.70810|       0|\n\n</div>\n:::\n\n```{.r .cell-code}\n#other comorbidities\nother_hospd_lm <- lm(hospd ~ other, data = tbe)\ntidy(other_hospd_lm)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |  estimate| std.error| statistic|   p.value|\n|:-----------|---------:|---------:|---------:|---------:|\n|(Intercept) | 39.590909|  1.014237| 39.035162| 0.0000000|\n|otheryes    |  4.142857|  1.271413|  3.258466| 0.0011993|\n\n</div>\n:::\n\n```{.r .cell-code}\n#vaccination\nvac_hospd_lm    <- lm(hospd ~ vac, data = tbe)\ntidy(vac_hospd_lm)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |  estimate| std.error| statistic|   p.value|\n|:-----------|---------:|---------:|---------:|---------:|\n|(Intercept) | 42.556989| 0.6262426| 67.956072| 0.0000000|\n|vacyes      | -8.399095| 3.1607381| -2.657321| 0.0081379|\n\n</div>\n:::\n\n```{.r .cell-code}\n#monophasic course\nmono_hospd_lm   <- lm(hospd ~ mono, data = tbe)\ntidy(mono_hospd_lm)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |  estimate| std.error| statistic|   p.value|\n|:-----------|---------:|---------:|---------:|---------:|\n|(Intercept) | 40.690566| 0.8291071| 49.077574| 0.0000000|\n|monoyes     |  3.396192| 1.2325691|  2.755377| 0.0060844|\n\n</div>\n:::\n\n```{.r .cell-code}\n#large tick at removal\ntick_hospd_lm   <- lm(hospd ~ tick, data = tbe) \ntidy(tick_hospd_lm)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |  estimate| std.error| statistic|   p.value|\n|:-----------|---------:|---------:|---------:|---------:|\n|(Intercept) | 42.731250| 0.7593945| 56.270158| 0.0000000|\n|tickyes     | -1.487348| 1.3045725| -1.140103| 0.2548094|\n\n</div>\n:::\n\n```{.r .cell-code}\n## Here we do it with {purrr} all in one command\ntbe %>% \n  select(-hyper, -age, -hospd) %>% # we first remove the columns we have explored before + the outcome column\n  map(.f = ~lm(hospd ~ .x, data = tbe)) %>%   # here we carry out the model for each column. \".x\" represents all the column\n  map(tidy)                                   # finally we do tidy on each model\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$vac\n# A tibble: 2 x 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)    42.6      0.626     68.0  4.69e-249\n2 .xyes          -8.40     3.16      -2.66 8.14e-  3\n\n$mono\n# A tibble: 2 x 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)    40.7      0.829     49.1  1.30e-189\n2 .xyes           3.40     1.23       2.76 6.08e-  3\n\n$other\n# A tibble: 2 x 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)    39.6       1.01     39.0  2.43e-151\n2 .xyes           4.14      1.27      3.26 1.20e-  3\n\n$tick\n# A tibble: 2 x 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)    42.7      0.759     56.3  5.50e-214\n2 .xyes          -1.49     1.30      -1.14 2.55e-  1\n\n$sex\n# A tibble: 2 x 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)     46.7     0.693      67.3 2.99e-247\n2 .xfemale       -12.4     1.16      -10.7 3.79e- 24\n```\n:::\n:::\n\n\n\n</br>\n\n</details>\n\n\nStatistically significant ($p<0.05$) univariable effects were observed for sex, other comorbidities, vaccination and monophasic disease course but not for large tick at removal. Women had on average 12.4 days shorter hospitalisation stay than men, other comorbidities increase the hospitalisation by 4.1 days, vaccination reduced it by 8.4 days, and monophasic disease course increased it by 3.4 days.\n\n\n### **Step 6: Multivariable analysis**\n\nTo control for possible confounding, we will adjust for the minimum adjustment set that we have identified through the DAG analysis (**Goal 1**), adding each variable in different steps.\n\n#### Step 6.1: Add age as a covariate to the model\n\nAs a first step, add age to the model of the main effect. \n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nWe have already calculated and saved the model of our main effect (*hyper_hospd_lm*). You can add age to this model by creating a new model and adding the additional variable, so that the formula syntax is model <- lm(hospd ~ hyper + newVariable, data = data)\n\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating a new model and adding age \nhyper_hospd_adj_lm <- lm(hospd ~ hyper + age, data = tbe)\n\ntidy(hyper_hospd_adj_lm)                                   \n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |   estimate| std.error| statistic|   p.value|\n|:-----------|----------:|---------:|---------:|---------:|\n|(Intercept) | 23.6918245|  1.437666| 16.479366| 0.0000000|\n|hyperyes    |  3.8015966|  1.245007|  3.053473| 0.0023875|\n|age         |  0.3715581|  0.027567| 13.478364| 0.0000000|\n\n</div>\n:::\n:::\n\n\n\n</br>\n\n</details>\n\nAdjusting for age, we find that hypertension is associated with a 3.8 increase in the days of hospitalisations. This is only a slight change compared to the effect in the unadjusted model (where the coefficient was 3.9).\n\n\n#### Step 6.2: Compare the performance of both models\n\nWe have the univariate model (*hyper_hospd_lm*), and now we have one adjusted by age (*hyper_hospd_adj_lm*). Compare both models calculating model performance metrics such as AIC and logLik. \n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nOne easy function to calculate performance metrics is `glance()` from the {broom} package. But, of course, there are many others. Choose the one you feel most comfortable with!\n \n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(hyper_hospd_lm)   # performance metrics of the univariate model\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| r.squared| adj.r.squared|    sigma| statistic|   p.value| df|    logLik|      AIC|     BIC| deviance| df.residual| nobs|\n|---------:|-------------:|--------:|---------:|---------:|--:|---------:|--------:|-------:|--------:|-----------:|----:|\n| 0.0148657|     0.0128219| 13.50128|  7.273399| 0.0072434|  1| -1945.512| 3897.024| 3909.57| 87861.17|         482|  484|\n\n</div>\n:::\n\n```{.r .cell-code}\nglance(hyper_hospd_adj_lm) # performance metrics of the adjusted model\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| r.squared| adj.r.squared|    sigma| statistic| p.value| df|    logLik|      AIC|      BIC| deviance| df.residual| nobs|\n|---------:|-------------:|--------:|---------:|-------:|--:|---------:|--------:|--------:|--------:|-----------:|----:|\n| 0.2849348|     0.2819616| 11.51466|  95.83297|       0|  2| -1867.974| 3743.948| 3760.676| 63774.52|         481|  484|\n\n</div>\n:::\n:::\n\n\n\n</br>\n\n</details>\n\nThe output of `glance()` gives us several performance metrics. If you want to focus on the important bits, you can look at the **logLik** and the **AIC**. A larger logLik means a better model; and a lower AIC means also a better model. So, if your logLik goes up and your AIC goes down, you are going in the right direction. The advantage of the logLik is that there is a formal test (Likelihood Ratio Test) to test if two logLiks are significantly different. However, AIC takes more things into consideration than the logLik, such as the complexity of the model (favours simpler models), so it is very useful to compare models with different numbers of parameters (like this case).\n\n\nIf you want to know more, let's review each element of the output given by `glance()`:\n\n-   **r.squared**: This is a measure of how well the independent variables in your model explain the variability of the dependent variable. Think of it as a percentage that tells you how much of the changes in the outcome can be predicted by the model. So, in our example, hypertension alone explains 1.5% of the variability in length of hospitalisation, but when we add age, that model explains 28.5% of the variability in our dependent variable.\n\n-   **adj.r.squared**: The adjusted R-squared value adjusts the R-squared value based on the number of predictors in the model. It is a more accurate measure when comparing models with different numbers of predictors (as in this case). Here, it is slightly lower at 28.2%, indicating a small adjustment for the number of predictors.\n\n-   **sigma**: This represents the residual standard error, which is the standard deviation of the residuals.\n\n-   **statistic**: This is the F-statistic value for the overall significance of the model. It tests whether at least one predictor variable has a non-zero coefficient.\n\n-   **p.value**: The p-value associated with the F-statistic.\n\n-   **df**: Degrees of freedom associated with the model which typically correspond to the number of predictors (1 in the first case and 2 in the second).\n\n-   **logLik**: The log-likelihood of the model, which is a measure of the model fit. Higher values indicate a better fit. As stated above, one of the main performance measures that you will use as an epidemiologist.\n\n-   **AIC**: Akaike Information Criterion, which is used for model comparison. Lower values indicate a better model.\n\n-   **BIC**: Bayesian Information Criterion, similar to AIC but with a higher penalty for models with more parameters.\n\n-   **deviance**: This is a measure of the goodness of fit of the model. Lower values indicate a better fit.\n\n-   **df.residual**: The residual degrees of freedom, which is the number of observations minus the number of parameters estimated.\n\n-   **nobs**: The number of observations used in the model, which is 484 in our case\n\n#### (Optional) Step 6.3: Plotting effects of age by hypertension\nIf you remember, in **Step 3.2** we checked visually for the association between age and length of hospitalisation by sex. Now, we will do something similar by plotting the estimated effect of age on length of hospitalisation **by hypertension status**. The final output that we want is a scatterplot displaying the raw data (length of hospitalisation by age), and then the fitted regression line by hypertension status. \n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nIn order to plot the estimated effects of age by hypertension we have to extract the fitted values of “hospd” from the model and add them to the dataframe. This only works if we have removed all rows that contain NAs in the hospd column before. we can then pass this new dataframe to a `ggplot()` with a `geom_point()` for the scatterplot and `geom_line()` for the fitted trend lines. \nNote: Previously, we used `geom_smooth()` to add trend lines to the scatterplot. Because we want to plot the predicted values of an existing model and not fit a linear model within `ggplot()`, we have to use `geom_line()` and use the predicted values of our model as input for y.\n\n</br>\n\n</details>\n\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First add a variable with the fitted values to the dataframe\ndata_fitted <- tbe %>%\n  \n  filter(!is.na(hospd)) %>%   # Remove NAs \n\n  mutate(fit = predict(hyper_hospd_adj_lm)) # Create a new variable with the predicted values\n\n### You can now open data_fitted to have a look at the new column\n\n# Now we do the plot with the fitted lines\n\nplot_fitted <- data_fitted %>%\n  \n  ggplot(mapping = aes(x = age, \n                       y = hospd,\n                       colour = hyper)) +\n  \n  geom_point() +                            # Adding a scatter plot\n  \n  geom_line(aes(y = fit)) +                 # we add a line specifying that we want the fitted and not the observed values in the y-axis\n\n  labs(\n    title = \"Effect of age on TBE hospital stay length for people\\nwith and without hypertension \", # Title of the plot, note that \"\\n\" breaks the title into the next line\n    x = \"Age\",\n    y = \"Length of hospitalisation in days\",\n    colour = \"Hypertension\"\n  ) +\n  \n  theme_bw()                                  # we add a predefined theme\n\nplot_fitted\n```\n\n::: {.cell-output-display}\n![](tbe_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n\n</br>\n\n</details>\n\nWe did not allow the association between age and hospitalisation to vary by levels of hypertension. So we force them to be parallel by the way we specify the model. If we want the slopes to differ, we would need to allow for an interaction term. We’ll get to that later.\n\n#### Step 6.4: Continue building the adjusted model and check quality of the model\n\nContinue adding the rest of variables that we have to adjust for according to the DAG (TBE vaccination, age, large tick, monophasic course, other comorbidities and sex) to the model *hyper_hospd_adj_lm* **one by one**. Check, after you add each variable, **model performance metrics** to ensure that the model is improving.\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### We first add sex to the previous model\nhyper_hospd_adj_lm <- lm(hospd ~ hyper + age + sex, data = tbe) # formula\ntidy(hyper_hospd_adj_lm)                                # estimates\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |    estimate| std.error|  statistic|  p.value|\n|:-----------|-----------:|---------:|----------:|--------:|\n|(Intercept) |  28.9661798| 1.3613386|  21.277718| 0.000000|\n|hyperyes    |   3.4659484| 1.1079250|   3.128324| 0.001865|\n|age         |   0.3452202| 0.0246333|  14.014368| 0.000000|\n|sexfemale   | -11.0377082| 0.9762639| -11.306071| 0.000000|\n\n</div>\n:::\n\n```{.r .cell-code}\nglance(hyper_hospd_adj_lm)                              # performance metrics\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| r.squared| adj.r.squared|    sigma| statistic| p.value| df|    logLik|      AIC|      BIC| deviance| df.residual| nobs|\n|---------:|-------------:|--------:|---------:|-------:|--:|---------:|--------:|--------:|--------:|-----------:|----:|\n| 0.4353144|     0.4317851| 10.24315|  123.3435|       0|  3| -1810.837| 3631.674| 3652.584| 50362.62|         480|  484|\n\n</div>\n:::\n\n```{.r .cell-code}\n### TBE vaccination\nhyper_hospd_adj_lm <- lm(hospd ~ hyper + age + sex + vac, data = tbe) # formula\ntidy(hyper_hospd_adj_lm)                                # estimates\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |    estimate| std.error|  statistic|   p.value|\n|:-----------|-----------:|---------:|----------:|---------:|\n|(Intercept) |  29.0192105| 1.3398585|  21.658415| 0.0000000|\n|hyperyes    |   3.5401913| 1.0905445|   3.246260| 0.0012512|\n|age         |   0.3507362| 0.0242813|  14.444681| 0.0000000|\n|sexfemale   | -10.9105961| 0.9613218| -11.349577| 0.0000000|\n|vacyes      |  -9.6218919| 2.3644063|  -4.069475| 0.0000551|\n\n</div>\n:::\n\n```{.r .cell-code}\nglance(hyper_hospd_adj_lm)                              # performance metrics\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| r.squared| adj.r.squared|    sigma| statistic| p.value| df|    logLik|      AIC|      BIC| deviance| df.residual| nobs|\n|---------:|-------------:|--------:|---------:|-------:|--:|---------:|--------:|--------:|--------:|-----------:|----:|\n|  0.454185|     0.4496271| 10.08105|   99.6467|       0|  4| -1802.611| 3617.223| 3642.315|  48679.6|         479|  484|\n\n</div>\n:::\n\n```{.r .cell-code}\n### Monophasic disease course\nhyper_hospd_adj_lm <- lm(hospd ~ hyper + age + sex + vac + mono, data = tbe) # formula\ntidy(hyper_hospd_adj_lm)                                # estimates\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |    estimate| std.error|  statistic|   p.value|\n|:-----------|-----------:|---------:|----------:|---------:|\n|(Intercept) |  27.9231475| 1.3632885|  20.482199| 0.0000000|\n|hyperyes    |   3.7307298| 1.0799901|   3.454411| 0.0006006|\n|age         |   0.3443505| 0.0240868|  14.296254| 0.0000000|\n|sexfemale   | -11.0608203| 0.9517650| -11.621378| 0.0000000|\n|vacyes      |  -9.8262935| 2.3391721|  -4.200757| 0.0000317|\n|monoyes     |   3.1330906| 0.9155900|   3.421936| 0.0006751|\n\n</div>\n:::\n\n```{.r .cell-code}\nglance(hyper_hospd_adj_lm)                              # performance metrics\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| r.squared| adj.r.squared|    sigma| statistic| p.value| df|    logLik|      AIC|      BIC| deviance| df.residual| nobs|\n|---------:|-------------:|--------:|---------:|-------:|--:|---------:|--------:|--------:|--------:|-----------:|----:|\n| 0.4672362|     0.4616634| 9.970207|  83.84164|       0|  5| -1796.755| 3607.509| 3636.784|  47515.6|         478|  484|\n\n</div>\n:::\n\n```{.r .cell-code}\n### Large tick at removal\nhyper_hospd_adj_lm <- lm(hospd ~ hyper + age + sex + vac + mono + tick, data = tbe) # formula\ntidy(hyper_hospd_adj_lm)                                # estimates\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |    estimate| std.error|   statistic|   p.value|\n|:-----------|-----------:|---------:|-----------:|---------:|\n|(Intercept) |  28.1079813| 1.3968015|  20.1231029| 0.0000000|\n|hyperyes    |   3.7655402| 1.0821694|   3.4796219| 0.0005482|\n|age         |   0.3446256| 0.0241066|  14.2959288| 0.0000000|\n|sexfemale   | -11.0239613| 0.9542624| -11.5523372| 0.0000000|\n|vacyes      |  -9.7114161| 2.3481138|  -4.1358371| 0.0000418|\n|monoyes     |   3.0852716| 0.9194697|   3.3554903| 0.0008555|\n|tickyes     |  -0.5959864| 0.9677751|  -0.6158315| 0.5382995|\n\n</div>\n:::\n\n```{.r .cell-code}\nglance(hyper_hospd_adj_lm)                              # performance metrics\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| r.squared| adj.r.squared|    sigma| statistic| p.value| df|    logLik|      AIC|      BIC| deviance| df.residual| nobs|\n|---------:|-------------:|--------:|---------:|-------:|--:|---------:|--------:|--------:|--------:|-----------:|----:|\n| 0.4676595|     0.4609634| 9.976687|   69.8405|       0|  6| -1796.562| 3609.124| 3642.581| 47477.85|         477|  484|\n\n</div>\n:::\n\n```{.r .cell-code}\n### Other comorbidities\nhyper_hospd_adj_lm <- lm(hospd ~ hyper + age + sex + vac + mono + tick + other, data = tbe) # formula\ntidy(hyper_hospd_adj_lm)                                # estimates\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |    estimate| std.error|   statistic|   p.value|\n|:-----------|-----------:|---------:|-----------:|---------:|\n|(Intercept) |  27.1251926| 1.4596417|  18.5834593| 0.0000000|\n|hyperyes    |   2.7139444| 1.1769928|   2.3058292| 0.0215491|\n|age         |   0.3406119| 0.0240754|  14.1477140| 0.0000000|\n|sexfemale   | -11.0797108| 0.9506756| -11.6545649| 0.0000000|\n|vacyes      |  -9.2298015| 2.3484899|  -3.9301005| 0.0000975|\n|monoyes     |   3.0995048| 0.9157172|   3.3847838| 0.0007712|\n|tickyes     |  -0.7577796| 0.9665465|  -0.7840074| 0.4334257|\n|otheryes    |   2.3008449| 1.0351078|   2.2228070| 0.0266978|\n\n</div>\n:::\n\n```{.r .cell-code}\nglance(hyper_hospd_adj_lm)                              # performance metrics\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| r.squared| adj.r.squared|    sigma| statistic| p.value| df|    logLik|      AIC|      BIC| deviance| df.residual| nobs|\n|---------:|-------------:|--------:|---------:|-------:|--:|---------:|--------:|--------:|--------:|-----------:|----:|\n| 0.4731284|     0.4653803| 9.935728|  61.06371|       0|  7| -1794.063| 3606.126| 3643.765|  46990.1|         476|  484|\n\n</div>\n:::\n:::\n\n\n\n</br>\n\n</details>\n\nAs you can see, adding the rest of variables identified through the DAG improved the model, according to the metrics. The only exception was the addition of the variable \"Large tick at removal\". However, the choice of covariates should be made conceptually through the DAG, and not based on whether there are small differences in AIC/logLik. If you concluded that this variable was a possible confounder, then keep it in the model.\n\n\n#### Step 6.5: Adding an interaction term\n\nWe saw in **Step 3.2** that the effect of age on length of hospitalisation is modified by sex. We knew this because the slopes were different for males and females. Given this information add now to the model an interaction term between sex and age.\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nAn interaction can be written as a multiplication of two variables in your regression formula, e.g. age*sex. There is no need to keep both variables individually in the formula AND in the interaction term. By just including the interaction term, R will estimate the coefficients independently for both variables and with the interaction.\n\n</br>\n\n</details>\n\n\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhyper_hospd_adj_lm <- lm(hospd ~ hyper + vac + mono + tick + other + age*sex, data = tbe) # formula\n\ntidy(hyper_hospd_adj_lm)                                # estimates\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term          |   estimate| std.error|  statistic|   p.value|\n|:-------------|----------:|---------:|----------:|---------:|\n|(Intercept)   | 24.2675847| 1.6629366| 14.5932114| 0.0000000|\n|hyperyes      |  2.9092258| 1.1650411|  2.4971014| 0.0128588|\n|vacyes        | -9.0596630| 2.3224314| -3.9009389| 0.0001096|\n|monoyes       |  2.9451978| 0.9064522|  3.2491487| 0.0012396|\n|tickyes       | -0.6988387| 0.9557594| -0.7311868| 0.4650256|\n|otheryes      |  2.2322254| 1.0235851|  2.1807913| 0.0296887|\n|age           |  0.3998845| 0.0293313| 13.6333864| 0.0000000|\n|sexfemale     | -3.0511594| 2.5045520| -1.2182456| 0.2237354|\n|age:sexfemale | -0.1728331| 0.0499755| -3.4583541| 0.0005924|\n\n</div>\n:::\n\n```{.r .cell-code}\nglance(hyper_hospd_adj_lm)                              # performance metrics\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| r.squared| adj.r.squared|    sigma| statistic| p.value| df|    logLik|     AIC|      BIC| deviance| df.residual| nobs|\n|---------:|-------------:|--------:|---------:|-------:|--:|---------:|-------:|--------:|--------:|-----------:|----:|\n| 0.4860689|     0.4774132| 9.823278|  56.15605|       0|  8| -1788.045| 3596.09| 3637.911| 45835.97|         475|  484|\n\n</div>\n:::\n:::\n\n\n</br>\n\n</details>\n\n::: {.webex-check}\n\n\nQUESTION: Looking at the estimates of the model, for females, what is the net effect of age on length of hospitalisation? <div class='webex-radiogroup' id='radio_QLOUFCQMZA'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_QLOUFCQMZA\" value=\"\"></input> <span>+0.4</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_QLOUFCQMZA\" value=\"answer\"></input> <span>+0.23</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_QLOUFCQMZA\" value=\"\"></input> <span>-0.17</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_QLOUFCQMZA\" value=\"\"></input> <span>+0.17</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_QLOUFCQMZA\" value=\"\"></input> <span>-0.32</span></label></div>\n\n:::\n\nLooking at the results, we see that age has an estimate of 0.4, which means that one additional year of age is associated with an increase in 0.4 days of hospitalisation. We also see that being female is associated with a decrease in 3 days of hospitalisation (compared with being male). The interaction estimate of -0.17 means that for females, each additional year of age is associated with a decrease in 0.17 days of hospitalisation. \nSo, to sum up, all things equal, a female of 41 years, compared to one of 40 years, would have +0.4 days of hospitalisation for having one extra year, but as she is female you have to add the interaction term (-0.17), so the net effect would be +0.23. For males, one extra year would still be associated with +0.4 days of hospitalisation.\n\nWe also see that adding the interaction term changes the effect estimate for hypertension and improves the model, so we may want to keep the interaction in the model, assuming that this ensures a better control for confounding of “age” and “sex”.\n\n\n*Note*: You should also look for other effect interaction terms in the dataframe. In the interest of the exercise, we will skip this step.\n\n\n### **Step 7: Model diagnostics**\nThe multiple linear regression model that we just run, like all models, has several assumptions:\n\n1. **Linearity**: The relationship between the independent variables and the dependent variable (length of hospitalisation) is linear. This means that the change in the dependent variable is proportional to the change in the independent variables.\n\n2. **Independence**: The observations are independent of each other. \n\n3. **Normality of Residuals**: The residuals of the model are normally distributed, meaning that they are symmetrically distributed around 0 and the residuals’ distribution is bell-shaped.\n\n4. **Homoscedasticity**: The residuals (difference between the observed values and the values estimated from the model) have constant variance at every level of the independent variables. This means that the spread of the residuals should be roughly the same across all levels of the independent variables.\n\n5. **No Multicollinearity**: The independent variables are not highly correlated with each other. High multicollinearity can make it difficult to determine the individual effect of each independent variable on the dependent variable.\n\n6. **No Autocorrelation**: The residuals are not correlated with each other. This is particularly important in time series data where observations are ordered in time.\n\n\nIn this case study we will learn how to check two of these assumptions: **Normality of residuals** and **Homoscedasticity**\n\n\n#### Step 7.1: Normality assumption\n\nTo assess whether the residuals of our model are normally distributed or not we will do these three things:\n\n-   Generating some diagnostic plots of the model\n\n-   Creating an histogram with the residuals\n\n-   Carrying out a Shapiro-test\n\n**Task**: Generate diagnostic plots of the model *hyper_hospd_adj_lm*. Don't worry if you don't find out how to do these. If you struggle, have a look at the hint below.\n\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nYou can retrieve **diagnostic plots** by using the function `autoplot()` from {ggfortify}. Pass your model object to the `autoplot()` function to generate three basic diagnostic plots. You can also specify which plot `autoplot()` needs to generate using the which = argument. In the solution, we specify that we want the first 2 plots.\n\n</br>\n\n</details>\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(hyper_hospd_adj_lm, which = 1:2)\n```\n\n::: {.cell-output-display}\n![](tbe_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\n</br>\n\n</details>\n\n\nLet's interpret each graph:\n\n-   **Residuals vs. fitted plot (plot 1, upper left corner):** You see a scatterplot with a blue line (LOESS smoothing curve). If the residuals are normally distributed around zero, then the blue line will be horizontal (parallel to the zero line).\n\n-   **Q-Q plot (plot 2, upper right plot):** The Q-Q plot shows you whether or not the residuals are normally distributed. On the X-axis you can see the quantiles of a normal distribution, while on the Y-axis you can see the standardized residuals (residuals dived by their standard deviation). If the residuals are normally distributed, in general, most of the points need to lie on the diagonal.\n\n\n\n::: {.webex-check}\n\n\nQUESTION: Are residuals normally distributed, based on these plots? <div class='webex-radiogroup' id='radio_UOAOOAOUAA'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_UOAOOAOUAA\" value=\"\"></input> <span>No</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_UOAOOAOUAA\" value=\"answer\"></input> <span>Yes</span></label></div>\n\n:::\n\n\n\n**Task**: Build an histogram with the residuals of the *hyper_hospd_adj_lm* model. \n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nTo do an **histogram of the residuals** you can follow a similar approach than the one we used in the **step 6.3**. That is, first adding to the *tbe* dataframe the residuals as a column (you can use the function `resid()`) and then using `ggplot()` to plot this column in the x-axis of a `geom_histogram()`\n\n</br>\n\n</details>\n\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First add a variable with the residual values to the dataframe\ndata_res <- tbe %>%\n  \n  filter(!is.na(hospd)) %>%   # Remove NAs \n  \n  mutate(res = resid(hyper_hospd_adj_lm)) # Create a new variable with the residual values\n\n### You can now open data_res to have a look at the new column\n\n# Now we do the histogram with the residuals\n\ndata_res %>%\n  \n  ggplot(mapping = aes(x = res)) +\n  \n  geom_histogram(aes(y = ..density..)) +                        # Adding a histogram with density\n  \n  #the function below will add the normal curve. \n  stat_function(fun = dnorm,  #The fun = argument we are specifying that we want the normal curve         \n                args = list(mean = mean(data_res$res, na.rm = T), #to draw a normal curve we need to give the mean and standard deviation of our column\n                            sd   = sd(data_res$res, na.rm = T)),  \n                \n                col = \"darkblue\", lwd = 1) +\n  labs(\n    title = \"Histogram of Residuals\", \n    x = \"Residuals\",\n    y = \"Frequency\"\n  ) +\n  \n  theme_bw()                                  # we add a predefined theme\n```\n\n::: {.cell-output-display}\n![](tbe_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\n</br>\n\n</details>\n\n::: {.webex-check}\n\n\nQUESTION: Does the histogram suggest a normal distribution of residuals? <div class='webex-radiogroup' id='radio_AMWLABWYWU'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_AMWLABWYWU\" value=\"\"></input> <span>No</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_AMWLABWYWU\" value=\"answer\"></input> <span>Yes</span></label></div>\n\n:::\n\n\n**Task**: Carry out a Shapiro-Wilk test to ascertain statistically if residuals are normally distributed\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nReview Step 4.1 and/or have a look at the EpiRhandbook Chapter on [Simple statistical tests](https://epirhandbook.com/new_pages/stat_tests.html) if you still have doubts.\n\n\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_res %>%\n  shapiro_test(res)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|variable | statistic|         p|\n|:--------|---------:|---------:|\n|res      | 0.9960796| 0.2762974|\n\n</div>\n:::\n:::\n\n\n</br>\n\n</details>\n\n\n::: {.webex-check}\n\n\nQUESTION: How do you interpret the result of the Shapiro-Wilk test? <div class='webex-radiogroup' id='radio_NBQAJISKHI'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NBQAJISKHI\" value=\"\"></input> <span>Residuals do not follow a normal distribution</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NBQAJISKHI\" value=\"answer\"></input> <span>We cannot reject the null hypothesis that residuals follow a normal distribution</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NBQAJISKHI\" value=\"\"></input> <span>We accept the alternative hypothesis</span></label></div>\n\n:::\n\n#### Step 7.2: Homoscedasticity\n\nNow we will check the other assumption, that the variance of the residuals (i.e., the magnitude of their distance to 0) does not depend on the predictor.\n\nCheck homoscedasticity by running plot number 3 (Scale-location plot) in the `autoplot()` function.\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate the scale-location plot\nautoplot(hyper_hospd_adj_lm, which = 3)\n```\n\n::: {.cell-output-display}\n![](tbe_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\n</br>\n\n</details>\n\nThis plot is called a scale-location plot and represents the fitted values vs. the square root of the standardized residuals. With this plot it is possible to check for heteroscedasticity (i.e., heterogeneity of variance - the opposite of homoscedasticity). Ideally, the residuals should be **evenly spread** out across all levels of fitted values. This means there should be no clear pattern or systematic change in the spread of residuals as you move along the x-axis.  If the residuals form a **funnel shape** (narrow at one end and wide at the other), this indicates heteroscedasticity, meaning the variance of the residuals is not constant. The **blue smoothed line** should be roughly horizontal and close to zero. Significant deviations from this line can indicate issues with homoscedasticity.\n\n::: {.webex-check}\n\n\nQUESTION: Based on this graph, do you think that the assumption of homoscedasticity is reasonably met? <div class='webex-radiogroup' id='radio_FQTCKQYPNN'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_FQTCKQYPNN\" value=\"\"></input> <span>No</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_FQTCKQYPNN\" value=\"answer\"></input> <span>Yes</span></label></div>\n\n:::\n\n\n### **Step 8: Public health relevance**\n\n- Discuss the PH relevance of your findings and any next steps and recommendations that may result from this.\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try it yourself first!)\n\n</summary>\n\n</br>\n\nThis is the first time that an association between hypertension and severity of TBE (based on the duration of hospitalisation) has been detected. Even though you suspected such an association in the beginning (and thus tested for it) and even though you think that it may be causal based on your DAGs and the control for confounding, there are more steps involved in establishing a causal relationship. We should follow the Bradford Hill Criteria to argue causality. For example, the biological basis for this effect needs to be established. Similar effects have been seen for other infections (e.g., SARS-CoV-2), which may have promoted the hypothesis in the beginning. You may also decide to look for a possible dose-response relationship in further analysis of our data. Furthermore, these results should be repeated independently to rule out a chance finding. Once the causal relationship between hypertension and TBE is further corroborated, vaccination against TBE for persons with hypertension could be recommended.\n</br>\n\n</details>\n\n\n",
    "supporting": [
      "tbe_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}