project:
  type: book
book:
  title: Applied Epi Case Studies
  author: Applied Epi
  date: 10/09/2023
  cover-image: images/logos/Applied_Epi_logo.png
  chapters:
  - index.qmd
  - pages/fulton-en.qmd
  - pages/oswego-es.qmd
bibliography: references.bib
format:
  html:
    toc: true
    number-sections: false
    number-depth: 0
    css:
    - webex.css
    include-after-body:
    - webex.js
  pdf:
    documentclass: scrreprt
