project:
  type: book

book:
  title: "Applied Epi Case Studies"
  author: "Applied Epi"
  date: "10/09/2023"
  cover-image: Applied_Epi_logo.png
  chapters:
    - index.qmd
    - intro.qmd
    - fulton-en.qmd
    - oswego-es.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



