project:
  type: book
book:
  title: Applied Epi Case Studies
  author: Applied Epi
  date: 10/09/2023
  cover-image: Applied_Epi_logo.png
  chapters:
  - index.qmd
  - pages/intro.qmd
  - pages/fulton-en.qmd
  - pages/oswego-es.qmd
  - pages/summary.qmd
  - pages/references.qmd
bibliography: references.bib
format:
  html:
    css:
    - webex.css
    include-after-body:
    - webex.js
  pdf:
    documentclass: scrreprt
