project:
  type: website
  render:
    - index.qmd      
 
    - pages/instructions.qmd
    # - pages/fulton.qmd          
    # - pages/r_practical.qmd
    - pages/multi_disease_lab.qmd
    # - pages/under_construction.qmd
    # - pages/tbe.qmd
    # - pages/stegen-en.qmd                
    # - pages/openxlsx2_tutorial-en_revised.qmd       
    
    # Spanish
   # - pages/oswego.es.qmd
   # - pages/under_construction.es.qmd
    
    # French
   # - pages/under_construction.fr.qmd
    

website:
  title: "Applied Epi Open Case Study Repository"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/instructions.qmd
        text: How-to Guide
      - href: "https://appliedepi.org/"
        text: About Applied Epi
    tools:
      - icon: twitter
        href: "https://twitter.com/appliedepi"
      - icon: linkedin
        href: "https://www.linkedin.com/company/appliedepi/"
    background: primary
  sidebar:
    logo: "images/logos/Applied_Epi_logo.png"  
    
format:
  html: 
    theme: 
      light: sandstone
      dark: [darkly, theme-dark.scss]
    toc: true
    toc-location: left 
    number-sections: false
    number-depth: 0
    grid: 
      body-width: 1200px
      margin-width: 40px
    # css:
    #  - webex.css
    # include-after-body:
    #  - webex.js

babelquarto:
  languagecodes:
  - name: es
    text: "Español"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['es']
  languagelinks: sidebar
title-es: "Estudios de casos de AppliedEpi"
lang: en
