---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Considerations for standardised coding in this case-study template


## General coding framework

* When possible, use [tidyverse}, not {data.table}, no apply() functions, and avoid {base}
* Use a vertical approach to writing coding - easier to read
* Use spaces in your code
* Use lowercase and underscores in your object names
* For quick tabulations Use tabyl() from {janitor}, not table() from {base}
* Use the magrittr pipe %>%, not the native pipe
* Use  <-   not =


## Vocabulary

* Use **“Data frame”** instead of “dataset”
* Use **“Import (data)”** - avoid saying “read in” which doesn’t align with the import() function, and can be confusing to people who are not native english speakers. Reserve the word “load” for packages (see below).
* Use the word **“load”** for packages, as it aligns with the nomenclature of the p_load() function (or “install”, for the step prior to loading)
* Use **“Quotation marks”** vs. “Inverted commas” - “inverted” is a complicated word for non-native English speakers
* **Columns & Rows** vs. Variables & Observations



<!-- Some considerations about about this quarto template 
-   Text within \<! \> will not show in your final document.
    -   The other parts such as slashes (///), dashes (-) and tildes (\~) are just aesthetic
    -   These comments are used to explain the code chunks.\
    -   We refer to functions in curly brackets, e.g. {dplyr} and functions end in brackets, e.g. count()\
    -   This comment will not show up when you knit the document.\
    -   You can delete them if you want.\ -->


<!--Below insert the name of the Case study. In curly brackets is the section reference name to be cross-references throughout the book -->

# Name of case study {#sec-name-lan}

## Overview

 **Case study characteristics** 
|                              |      |
|------------------------------|:-----|
| **Name**                     |      |
| **Language**                 |      |
| **Tool**                     |      | <!-- Specify tool (e.g., R, Excel, STATA...) -->
| **Location**                 |      |
| **Scale**                    |      | <!-- Local, Regional, National or Global -->
| **Diseases**                 |      | <!-- Specify pathogen -->
| **Keywords**                 |      | <!-- Examples: Outbreak investigation, GIS, TSA... -->
| **Technical complexity**     |      | <!-- Basic, Intermidiate or High -->
| **Methodolocial complexity** |      | <!-- Basic, Intermidiate or High -->
 
 
 Name: XXX\ -->
Language: XXXX\
Tool: R\ <!-- Specify tool (e.g., R, Excel, STATA...) -->
Location: XXXX\
Scale: XXXX\ <!-- Local, Regional, National or Global -->
Disease: XXXXX\ <!-- Specify pathogen -->
Keywords:  <!-- Examples: Outbreak investigation, GIS, TSA... -->
Technical complexity: Basic/intermidiate/advanced 
Methodological complexity: Basic/intermidiate/advanced 

***Authorship***\
Original authors: Centre for Disease Prevention and Control (CDC)\
Data source: Epi Info, version 3.5.4 (CDC)
Adapted to R by: Leonel Lerebours Nadal y Alberto Mateo Urdiales

## Instructions

### Getting Help

There are several ways to get help:

1)  Look for the "hints" and solutions (see below)
2)  Post a question in [Applied Epi Community](www.community.appliedepi.org) with reference to this case study

#### Hints and Solutions

Here is what the "helpers" look like:

```{=html}
<!--
NOTE: Below is the hint (all within details tags collapsed)
-->
```
<details>

<summary style="text-decoration: underline; color: darkgreen;">

`r fontawesome::fa("lightbulb", fill = "gold")` Click to read a hint

</summary>

</br>

Here you will see a helpful hint!

</br>

</details>

```{=html}
<!--
NOTE: Below is the solution (all within details tags collapsed)
-->
```
<details>

<summary style="text-decoration: underline; color: red;">

`r fontawesome::fa("check", fill = "red")`Click to see a solution (try it yourself first!)

</summary>

</br>

```{r eval = F, echo=T}
ebola_linelist %>% 
  filter(
    age > 25,
    district == "Bolo"
  )
```

Here is more explanation about why the solution works.

</br>

</details>

```{=html}
<!--
NOTE: End of solution
-->
```


#### Posting a question in the Community Forum

... description here about posting in Community... TO BE COMPLETED BY APPLIED EPI



#### Icons  

You will see these icons throughout the exercises:

Icon  |Meaning
------|--------------------
`r fontawesome::fa("eye", fill = "darkblue")`|Observe  
`r fontawesome::fa("exclamation", fill = "red")`|Alert!  
`r fontawesome::fa("pen", fill = "brown")`|An informative note  
`r fontawesome::fa("terminal", fill = "black")`|Time for you to code!  
`r fontawesome::fa("window-restore", fill = "darkgrey")`|Change to another window  
`r fontawesome::fa("bookmark", fill = "orange")`|Remember this for later  

### Terms of Use

<!-- Describe the licencing and other appropriate information about Terms of use or any other disclaimer -->

##  Feedback & suggestions

-   You can write feedback and suggestions on this case study at the
    [GitHub issues
    page](https://github.com/appliedepi/case_studies)
-   Alternatively email us at:
    [contact\@appliedepi.org](mailto:contact@appliedepi.org)




\pagebreak

## Version XXX

Write DATE OF LAST UPDATE


## Disclaimer 

HERE YOU CAN WRITE ANY APPROPRIATE DISCLAIMER

\pagebreak


## Revisions
WRITE ANY REVISIONS MADE TO THE CASE STUDY

| Date    | Changes made | Version| 
|---------|:-------------|-------:|
|         |              |        |
|         |              |        |
|         |              |        |




\pagebreak

## Guidance

## Objectives of this case study 

HERE WRITE AN INTRODUCTION TO THE CASE STUDY, SPECIFYING:
      1. Background
      2. Objectives/Learning outcomes
      3. What the users of the case study will learn
      4. Online references to both R code (e.g., EpiRhandbook) and to methodological documents
      

### Previous level of expertise assumed
ADD INFORMATION OF PREVIOUS EXPERTISE NEEDED TO FOLLOW THE CASE STUDY. THIS INCLUDES EXPERTISE ON:

* EPIDEMIOLOGICAL EXPERIENCE (e.g, KNOWLEDGE OF THE FOUNDATIONS OF SURVIVAL ANALYSIS). 
* SOFTWARE EXPERIENCE (e.g., BASIC KNOWLEDGE OF R) (RMARKDOWN)

INCLUDE REFERENCES IF POSSIBLE



### Preparation for the case study

INCLUDE THE STEPS NEEDED TO START REPLICATING THE ANALYSIS OF THE CASE STUDY

EXAMPLE:

1. Download folder named XXX and extract contents in the local laptop
2. Create an Rstudio project in the folder XXX (they already come with the project)
3. Subfolder data contains XXXX
4. Subfolder scripts should be used to save any scripts related to the analysis
5. Subfolder outputs will be used to store all outputs (tables, graphs, documents) that are the result of the analysis








## Specific to the case study

HERE ADD THE DIFFERENT SECTIONS OF THE CASE STUDY. PLEASE INCLUDE QUESTIONS WITH HINTS AND SOLUTIONS AS SHOWN ABOVE.

