{
  "hash": "4695caf4ebaf0a00b952a9635d777900",
  "result": {
    "markdown": "---\noutput: html_document\neditor_options: \n  chunk_output_type: console\nexecute:\n  warning: false\n  error: false\nformat: \n  html: \n    css: webex.css\n    include-after-body: webex.js\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n# Descriptive analysis of the 2022 Mpox outbreak in Europe {#sec-rpractical}\n\n::: {.callout-note appearance=\"minimal\" icon=\"false\"}\n**Tool**: R \\| **Technical complexity**: Basic \\| **Methodological\ncomplexity**: Basic\\\n**Source:** ECDC EI Group (simulated data)\\\n**Prior knowledge required:** [R\nbasics](https://epirhandbook.com/en/new_pages/basics.html) (Using\nRstudio; R packages, functions and arguments, using pipes)\n:::\n\nFor instructions on how to use our case studies, see our [How-to\nGuide](pages/instructions.qmd_). We welcome feedback and suggestions via\n[contact\\@appliedepi.org](mailto:contact@appliedepi.org). You can also\ndiscuss the case study or related concepts on the [Applied Epi\nCommunity](https://community.appliedepi.org/).\n\n\\pagebreak\n\n## Scenario\n\nIt is May 2022 and Mpox has just been reported for the first time across\n5 countries in Europe: Countries \"A\", \"B\", \"C\", \"D\", and \"E\". You have\nbeen requested to provide a basic descriptive analysis to the European\nCentre for Disease Prevention and Control (ECDC).\n\nYou are given access to:\n\n-   A dataset with aggregate case counts, submitted to ECDC by the five\n    countries as part of routine European reporting\n-   A linelist with cases, submitted by the five countries to ECDC for\n    this particular analysis\n\nLet's go!\n\n## Objectives\n\nIn this case study you will:\n\n1.  Explore different types of files and how they can be imported in R.\n2.  Perform basic data cleaning, e.g., changing the variable type,\n    recoding variables, aggregating and filtering.\n3.  Perform a basic descriptive analysis using tables and graphs\n\n## Step 1. Set up\n\n### 1.1 Get started in RStudio\n\nStart by setting up a reproducible and well-organized workflow. This\nwill make it easy to rerun your analysis whenever needed.\n\n**Tasks:**\n\n-   Set up an RStudio project\n-   Set up clear sub-folders where your code, data, and outputs will go\n-   Create an R script, or an R Markdown file if you prefer. Make sure\n    the script purpose, date, and author are written as comments at the\n    top.\n-   Extra: Ensure your working language in RStudio is appropriate (e.g.\n    English for this exercise)\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\n-   Create a folder where all the work in this case study will go. For\n    example, create 'mpox_analysis' on your computer desktop. Create\n    your RStudio project to be based in this folder.\n\n-   We suggest creating the following sub-folders: `scripts` (for your\n    code), `data` (for your data), and `outputs` (for your analytical\n    outputs).\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\nCreate a folder (e.g. 'mpox_analysis' on your Desktop) for your work. To\ncreate an Rstudio project in your new folder, click `New Project…` in\nthe top left of your R Studio, then `Existing Directory`, then `Browse`\nto select your new folder. For more information, look at the [R\nprojects](https://epirhandbook.com/new_pages/r_projects.html) section of\nthe Epi R Handbook.\n\nStart a new R script by clicking `New File…` in the top left of your R\nStudio, then `R Script`. Save it immediately in the appropriate place,\ne.g. in a 'scripts' subfolder of your R Project.\n\nAt the top of your new R script, write some essential information like\nyour name, the purpose of the file, and the date.\n\nYour R locale determines the language and regional settings used for\nthings like date formats and translations. If your locale is different\nfrom the language you want for your report (e.g., a French locale vs. an\nEnglish report), you can change it to English by running\n`Sys.setlocale(\"LC_ALL\", \"English\")`. Include this in your script if\nneeded, or skip it if your locale is usually appropriate. This is\nexplained in more detail in the [How-to Guide](pages/instructions.qmd_).\n\n</details>\n\n### 1.2 Install/load packages\n\nNext in your R script, you need to install and load the necessary R\npackages. This ensures that the functions you need are available for\nyour analysis.\n\nYou will need the following packages: `rio` (for importing data),\n`janitor` (for cleaning data), `lubridate` (for cleaning dates), `skimr`\n(for reviewing data), `epikit` (for epi-related tasks), `gtsummary` (for\npresentation-ready tables), `apyramid` (for age-sex pyramids), and\n`tidyverse` (for general data manipulation/science tasks).\n\nAs you start, your trusted colleague nudges you and whispers \"I've heard\nthat a great way to manage your packages is with the `pacman` package\".\n\nOver to you!\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\nUse the function `p_load()` from `pacman` for this task. You provide the\nfunction with a list of packages that you want to use. It will take two\nsteps per package: 1) Check if the package is installed on your\ncomputer, and install it if necessary, then 2) Load the package so it\ncan be used during this R session.\n\nIf you don't already have `pacman` installed, you will need to install\nit the \"traditional way\" first, with `install.packages()`.\n\nNote that the order of packages in your p_load function can be\nimportant. If two packages have the same function names (e.g. `select()`\nin the package `MASS` and `select()` in `tidyverse`, which do different\nthings), then R will use the function from the most recently loaded\npackage. To prioritize functions from tidyverse, which are commonly used\nfor data manipulation and visualization, load tidyverse last.\n\n</detail>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ensures the package \"pacman\" is installed\nif (!require(\"pacman\")) {\n     install.packages(\"pacman\") }\n\n# install (if necessary) from CRAN and load packages to be used\npacman::p_load(\n  rio,        # importing data  \n  skimr,      # get overview of data\n  janitor,    # data cleaning and tables\n  lubridate,  # working with dates\n  epikit,     # to create age categories\n  gtsummary,  # summary statistics, tests and regressions \n  apyramid,   # plotting age pyramids \n  tidyverse  # data management and visualization\n)\n```\n:::\n\n\n## Step 2: Download and import the data\n\n### 2.1: Download the data\n\nECDC provides you with two files for your analysis, both updated as of 31st August 2022:\n\n-   A case-level linelist (*\"mpox_linelist.xlsx\"*) with case information\n    from five countries (countries A - E)\n-   An aggregate table (*\"mpox_aggregate_table.csv\"*) for those\n    countries with cumulative case counts per day.\n\nThey provide it to you via AppliedEpi's very useful data repository,\nwhich you can access using the `{appliedepidata}` package. So first you\nneed to download these two files to your own computer, as follows:\n\n1)  Install the `{appliedepidata}` package from GitHub using the\n    `install_github()` function in the `{remotes}` package. Install\n    `{remotes}` if you need to first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Install remotes if you need to (so you can install a package from GitHub)\npacman::p_load(\"remotes\")\n\n# Use the install_github function from remotes to install appliedepidata\nremotes::install_github(\"appliedepi/appliedepidata\")\n```\n:::\n\n\n2)  Save the two datasets into a specific folder using the `save_data()`\n    function from `{appliedepidata}`, by running the code below. The\n    example below saves the data into a 'data' subfolder within the\n    RStudio project. Note that if you do not specify a location within\n    the 'path' argument of the function, a window will pop up asking you\n    to manually select a folder.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Save down the two mpox files using the save_data() function from appliedepidata\nappliedepidata::save_data(\"mpox_linelist\",\n                        path = \"data\")\n\nappliedepidata::save_data(\"mpox_aggregate_table\",\n                          path = \"data\")\n```\n:::\n\n\n### 2.2 Import the data\n\nGreat! Thanks ECDC and Applied Epi! Now it's time to import the data\nfrom that folder into RStudio, so you can analyse it.\n\n**Task:** Import the downloaded case-based and aggregated data into your\nR environment. Ideally you want to use one function for both datasets,\ndespite one being a csv and the other an xlsx file.\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nUse the `import` function from the `{rio}` package, which can recognize\nand import different file types. It replaces importing functions that\nare specific to the file type, such as `read.csv()` from `{base}` for\n.csv files and `read_excel()` from `{readxl}` to import .xlsx files.\n\nIf you feel you need to know more about importing functions, read the\n[Import and export](https://epirhandbook.com/new_pages/importing.html)\nchapter of the EpiRhandbook.\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\nBelow we use the import function to bring in both files. Note how we are\nassigning the imported data to two objects, one called\n*mpox_linelist_raw*, and one called *mpox_agg_raw*. We add the 'raw'\nsuffix to distinguish this data from the cleaned versions we will make\nlater.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Import data  --------------\n\n# Case-based data\nmpox_linelist_raw <- import(\"data/mpox_linelist.xlsx\")\n\n# Aggregated data\nmpox_agg_raw <- import(\"data/mpox_aggregate_table.csv\")\n```\n:::\n\n\n\n\n</details>\n\n## Step 3: Explore the data\n\nYou need to understand what the data looks like as a first step, to\ninform your analysis.\n\n**Tasks:** Take a look at the different data frames and determine:\n\n-   The number of columns and observations (e.g. their *dimensions*)\n-   The class of their columns and whether it matches its nature (e.g.,\n    are \"dates\" considered \"dates\" by R?)\n-   If the contents of columns are clean and standardized in the mpox\n    linelist (e.g. gender, clinical symptoms, outcome, hiv status and\n    sexual orientation). Do you need to recode any of them?\n-   How unknown or missing data is categorised in these columns. Do\n    these values need to be standardized?\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nAn efficient function for initial data exploring is `skim()` from the\n`{skimr}` package, as it gives you a lot of information on data\nstructure and content, including the classes of columns.\n\nYou can use the function `tabyl()` from `{janitor}`, to get counts and\npercentages of every category in the data column, one by one. These get\nprinted to your RStudio console.\n\nAlso - we recommend just looking at the data itself! A good function for\nthis is `view()`, a baseR function.\n\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\nUsing the `skim` commands you can see the rows and columns of each\ndataset, and you can see how most of the columns in *mpox_linelist_raw*\n(including those containing dates) are character classes. (Results not\nshown on this exercise page)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Explore the dimensions of the two data objects \nskim(mpox_linelist_raw)\nskim(mpox_agg_raw)\n```\n:::\n\n\nTake a look at the overall data using `view()`. It will pop up in the\nData Viewer tab and you will get a good sense of how clean the data is\nand what the missingness is like. This preview shows just 5 rows from\nthe linelist data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nview(mpox_linelist_raw)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-29c38ce120eeb2856db8\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-29c38ce120eeb2856db8\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\"],[\"2022-03-03\",\"2022-03-23\",\"2022-05-01\",\"2022-03-10\",\"2022-05-04\"],[\"2022-03-02\",\"2022-03-23\",\"2022-05-01\",null,\"2022-05-04\"],[\"2022-02-27\",\"2022-03-13\",\"2022-04-19\",\"2022-02-27\",\"2022-04-27\"],[39,46,49,45,41],[\"M\",\"M\",\"F\",\"M\",\"M\"],[\"MSM\",null,null,null,null],[\"A\",\"A\",\"UNK\",\"A\",\"A\"],[\"POS\",\"UNK\",null,\"NEG\",\"NEG\"],[\"CountryA\",\"CountryA\",\"CountryC\",\"CountryC\",\"CountryA\"],[\"Rash\",\"Rash\",\"Rash, Systemic symptoms\",\"Rash, Systemic symptoms, Lesions\",\"Rash, Systemic symptoms, Lesions\"],[\"Rash\",\"Rash\",\"Rash\",\"Rash\",\"Rash\"],[null,null,\"Systemic symptoms\",\"Systemic symptoms\",\"Systemic symptoms\"],[null,null,null,\"Lesions\",\"Lesions\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>DateOfNotification<\\/th>\\n      <th>DateOfDiagnosis<\\/th>\\n      <th>DateOfOnset<\\/th>\\n      <th>Age<\\/th>\\n      <th>Gender<\\/th>\\n      <th>SexualOrientation<\\/th>\\n      <th>Outcome<\\/th>\\n      <th>HIVStatus<\\/th>\\n      <th>Country<\\/th>\\n      <th>ClinicalSymptoms<\\/th>\\n      <th>Rash<\\/th>\\n      <th>SystemicSymptoms<\\/th>\\n      <th>Lesions<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":4},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"DateOfNotification\",\"targets\":1},{\"name\":\"DateOfDiagnosis\",\"targets\":2},{\"name\":\"DateOfOnset\",\"targets\":3},{\"name\":\"Age\",\"targets\":4},{\"name\":\"Gender\",\"targets\":5},{\"name\":\"SexualOrientation\",\"targets\":6},{\"name\":\"Outcome\",\"targets\":7},{\"name\":\"HIVStatus\",\"targets\":8},{\"name\":\"Country\",\"targets\":9},{\"name\":\"ClinicalSymptoms\",\"targets\":10},{\"name\":\"Rash\",\"targets\":11},{\"name\":\"SystemicSymptoms\",\"targets\":12},{\"name\":\"Lesions\",\"targets\":13}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false},\"selection\":{\"mode\":\"multiple\",\"selected\":null,\"target\":\"row\",\"selectable\":null}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n\\br\n\nBelow is an example of using the `tabyl()` function from `{janitor},` to\nlook at the distribution of clinical symptoms. You can see 12 cases have\nmissing clinical information and that many cases have a mix of symptoms.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabyl(mpox_linelist_raw, HIVStatus)  \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n HIVStatus   n percent valid_percent\n       NEG 525  0.2625     0.4107981\n       POS 307  0.1535     0.2402191\n       UNK 446  0.2230     0.3489828\n      <NA> 722  0.3610            NA\n```\n:::\n:::\n\n\nYou can explore further columns one by one (results not shown):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Explore the values of different categorical columns in the mpox linelist: with tabyl\ntabyl(mpox_linelist_raw, Gender)\n\ntabyl(mpox_linelist_raw, ClinicalSymptoms)\n\ntabyl(mpox_linelist_raw, Outcome)\n\ntabyl(mpox_linelist_raw, SexualOrientation)\n```\n:::\n\n\nYou could add extra arguments to `tabyl()` to customize the tables, such\nas adding totals and changing the proportions to percentages so they are\neasier to read. See the table on clinical symptoms below. But remember -\nthis is just an initial look so don't go too crazy.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabyl(mpox_linelist_raw, ClinicalSymptoms) %>%    # Tabulate symptoms \n  adorn_totals() %>%                              # Add totals to bottom of table\n  adorn_pct_formatting(digits = 2)                # Format percentages\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 ClinicalSymptoms    n percent valid_percent\n                          Lesions   14   0.70%         0.70%\n                             Rash  257  12.85%        12.93%\n                    Rash, Lesions  323  16.15%        16.25%\n          Rash, Systemic symptoms  676  33.80%        34.00%\n Rash, Systemic symptoms, Lesions  654  32.70%        32.90%\n                Systemic symptoms   28   1.40%         1.41%\n       Systemic symptoms, Lesions   36   1.80%         1.81%\n                             <NA>   12   0.60%             -\n                            Total 2000 100.00%       100.00%\n```\n:::\n:::\n\n\nFinally, as an alternative approach to `tabyl()`, you could use\n`tbl_summary()` from the `{gtsummary}` package. We will describe this\nlater.\n\n</br>\n\n</details>\n\n::: {.callout-note appearance=\"minimal\" icon=\"false\"}\n**Test yourself!**\n\n::: webex-check\n\nHow many columns does the aggregated data have? <div class='webex-radiogroup' id='radio_JDMBAOSFNY'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_JDMBAOSFNY\" value=\"\"></input> <span>2000</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_JDMBAOSFNY\" value=\"\"></input> <span>13</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_JDMBAOSFNY\" value=\"answer\"></input> <span>3</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_JDMBAOSFNY\" value=\"\"></input> <span>101</span></label></div>\n\n:::\n\n::: webex-check\n\nWhat is the class of the column DateOfNotification in the mpox linelist? <div class='webex-radiogroup' id='radio_WDEKPNQZZT'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_WDEKPNQZZT\" value=\"\"></input> <span>Date</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_WDEKPNQZZT\" value=\"answer\"></input> <span>Character</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_WDEKPNQZZT\" value=\"\"></input> <span>Numeric</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_WDEKPNQZZT\" value=\"\"></input> <span>Factor</span></label></div>\n\n:::\n\n::: webex-check\n\nFor how many cases is the HIV status Unknown or missing? <div class='webex-radiogroup' id='radio_QOUCLNOOPQ'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_QOUCLNOOPQ\" value=\"answer\"></input> <span>1168</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_QOUCLNOOPQ\" value=\"\"></input> <span>722</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_QOUCLNOOPQ\" value=\"\"></input> <span>900</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_QOUCLNOOPQ\" value=\"\"></input> <span>446</span></label></div>\n\n:::\n:::\n\n## Step 4: Clean the data\n\n### 4.1: Clean the case-based data\n\n**Cleaning column names and values**\n\nGreat! From your exploration, you know that you can describe the\ngeographic distribution of cases by country, trends over time, their\ndemographic details, their sexual orientation and hiv status, plus their\noutcome and clinical symptoms.\n\nYou plan to make some tables and graphs to describe those variables.\n\nBUT! You may noticed that there are a few things that you need to clean\nup before really diving into the analysis.\n\nFor example:\n\n-   Column names have capital letters. This isn't outright a problem,\n    but can lead to mistakes since R treats ColumnName and Columnname as\n    different.\n-   Date columns are recognized as character classes, not dates, which\n    would cause issues like incorrect ordering (alphabetical) in\n    epicurves.\n-   Some columns have values that are unclear or unsuitable for\n    presentation. For example gender is categorized with \"F\", \"M\", \"O\"\n    and \"UNK\". The column Outcome is \"A\" and \"UNK\".\n-   Missing data is inconsistently handled, for instance with both \"UNK\"\n    and NA in the HIV status column. R thinks \"UNK\" is a valid value,\n    which it treats differently to true missing data (indicated by NA)\n\n**Tasks**:\n\n-   Create a clean version of your case-based data making all cleaning\n    changes in a single piping command\n-   Change all column names to lower case.\n-   Convert all date columns to class \"Date\".\n-   Recode \"Gender\" categories into: \"Female\", \"Male\", \"Other\", and\n    \"Unknown\"\n-   Recode \"Outcome\" categories into: \"Alive\" and \"Unknown\"\n-   Recode HIV status into: \"Positive\", \"Negative\" and \"Unknown\"\n-   Recode Sexual orientation into: \"Bisexual\", \"Heterosexual\",\n    \"MSM/homo or bisexual male\" and \"Unknown\".\n-   Check that all changes have been made correctly\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nTo convert all column names to lower case at once rather than renaming\neach column, use the function `clean_names()` from the `{janitor}`\npackage.\n\nUse `{lubridate}` functions to transform date columns into \"Date\" class.\nYou can do this one by one, or you could do all at the same time using\nthe `across()` function from `{dplyr}.` If you feel you need to know\nmore about transforming dates read the chapter [Working with\nDates](https://epirhandbook.com/en/new_pages/dates.html) from the\nEpiRhandbook. If you are not sure how to use the across() function, you\ncan also read the section on [Transform multiple\ncolumns](https://epirhandbook.com/en/new_pages/cleaning.html#clean_across).\n\nThere are different functions that we can use to recode values. We\npropose three: The function `recode()` from `{dplyr}`, the function\n`ifelse()` from `{base}` and the function `case_when()` from `{dplyr}`.\nIf you want to know more about these functions, look that the section on\n[Re-code\nvalues](https://epirhandbook.com/en/new_pages/cleaning.html#re-code-values)\nfrom the EpiRhandbook.\n\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\nHere we clean the data using a 'chain' of commands connected by pipes\n(%\\>%), which is the grammar of the functions in the {Tidyverse}. The\noutput is assigned to a new object called mpox_linelist to differentiate\nit from the raw data. It can be helpful to have both the cleaned and raw\ndata available in the environment to compare to the original data if\nneeded.\n\nSee the series of functions and the explanation in the comments.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a new object called mpox_linelist which is the clean version of the raw data\nmpox_linelist <- mpox_linelist_raw %>% \n  \n  # standardises names and puts all into lower case \n  clean_names() %>% \n  \n  #transform ONE column into date (note the column names are lower case now)\n  mutate(date_of_notification = ymd(date_of_notification)) %>%  \n\n  #transforms ALL columns starting with \"date\" into dates\n  mutate(across(starts_with(\"date\"), \n                .fns = ~ ymd(.x))) %>%  \n  \n\n  # Recode the gender values to be more obvious  \n  mutate(gender = recode(gender,\n                         \"F\" = \"Female\",\n                         \"M\" = \"Male\",\n                         \"O\" = \"Other\",\n                         \"UNK\" = \"Unknown\")) %>%\n  \n  #transforms UNK to Unknown across all character columns \n  mutate(across(where(is.character), \n                .fns = ~ ifelse(.x == \"UNK\", \"Unknown\", .x)))  %>% \n  \n  #recode with ifelse to change only one or two categories based on a rule. \n  mutate(outcome = ifelse(outcome == \"A\", \"Alive\", outcome)) %>%   \n  \n  #recode with case_when for more complex recoding \n  mutate(hiv_status = case_when(hiv_status == \"NEG\" ~ \"Negative\",    \n                                hiv_status == \"POS\" ~ \"Positive\",\n                                TRUE                ~ \"Unknown\")) %>% \n  \n  mutate(sexual_orientation = case_when(sexual_orientation == \"BISEXUAL\" ~ \"Bisexual\",\n                                        sexual_orientation == \"HETERO\" ~ \"Heterosexual\",\n                                        sexual_orientation == \"MSM\" ~ \"MSM/homo or bisexual male\",\n                                        TRUE                        ~  \"Unknown\")) \n```\n:::\n\n\nYou can then review your data by tabulating across all the different\ncolumns you have cleaned. See the preview of the HIV table below - it\nlooks tidier now with more understandable categories, and all missing\ndata is classified as 'Unknown'.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check that all changes have been made correctly\n\nskim(mpox_linelist)\n\ntabyl(mpox_linelist, gender)\n\ntabyl(mpox_linelist, clinical_symptoms)\n\ntabyl(mpox_linelist, outcome)\n\ntabyl(mpox_linelist, hiv_status)\n\ntabyl(mpox_linelist, sexual_orientation)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n hiv_status    n percent\n   Negative  525  0.2625\n   Positive  307  0.1535\n    Unknown 1168  0.5840\n```\n:::\n:::\n\n\n**IMPORTANT**: If 'unknown' and NA had meaningful differences, combining\nthem wouldn't be appropriate (e.g., 'unknown' means the case was asked\nbut didn't want to respond, while NA means they weren't asked). Here, we\nassume no meaningful difference and combine them for simplicity.\n\n</br>\n\n</details>\n\n::: {.callout-note appearance=\"minimal\" icon=\"false\"}\n**Test yourself!**\n\n::: webex-check\n\nIs it always appropriate to combine different types of unknown data? (e.g. missing, unknown, did not respond, NA) <div class='webex-radiogroup' id='radio_WDTCTODGHM'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_WDTCTODGHM\" value=\"\"></input> <span>Yes</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_WDTCTODGHM\" value=\"answer\"></input> <span>Depends on the meaning of those values</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_WDTCTODGHM\" value=\"\"></input> <span>No - never do this</span></label></div>\n\n:::\n\n::: webex-check\n\nHow many male cases do we have in the data frame? <div class='webex-radiogroup' id='radio_BVRCNILIDM'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BVRCNILIDM\" value=\"\"></input> <span>36</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BVRCNILIDM\" value=\"answer\"></input> <span>1960</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BVRCNILIDM\" value=\"\"></input> <span>65</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BVRCNILIDM\" value=\"\"></input> <span>1523</span></label></div>\n\n:::\n\n::: webex-check\n\nHow many cases have 'alive' as an outcome? <div class='webex-radiogroup' id='radio_YSYMEZGJAF'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_YSYMEZGJAF\" value=\"answer\"></input> <span>1405</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_YSYMEZGJAF\" value=\"\"></input> <span>None</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_YSYMEZGJAF\" value=\"\"></input> <span>595</span></label></div>\n\n:::\n:::\n\n**Creating new columns for analysis**\n\nFabulous, you're getting there. Now, because you plan to create weekly\nepicurves and an age-sex pyramid, you need to ensure your data has the\nright columns for this.\n\n***Tasks:***\n\n-   Use the column \"DateOfNotification\" to create a column called\n    \"week_date\" which has the week of notification, starting on Mondays.\n\n-   Create a column called \"age_group\" with ten year age groups and the\n    oldest group being 70+\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nTo create the age groups, explore the function called `age_categories()`\nfrom the `{epikit}` package.\n\nOne simple way to create the \"week_date\" column would be to use the\nfunction `floor_date()` from `{lubridate}`. Take a look at the\ndocumentation to understand how it works and how to make Monday the\nstarting day of the week.\n\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\nAdd the creation of these columns to your cleaning code:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpox_linelist <- mpox_linelist %>% \n  # create week column with Monday start \n  mutate(week_date = floor_date(date_of_notification, unit = \"week\", week_start = \"Monday\")) %>%\n  \n  # Use the age_categories function to create age categories\n  mutate(age_group = age_categories(age, lower = 0, #set up the lower age\n                                    upper = 70, #set up the upper age\n                                    by = 10)) #set up the age breaks\n```\n:::\n\n\n</details>\n\n::: {.callout-note appearance=\"minimal\" icon=\"false\"}\n**Test yourself!**\n\n::: webex-check\n\nWhich week has the largest number of cases? <div class='webex-radiogroup' id='radio_ZUBAMSCLRA'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZUBAMSCLRA\" value=\"answer\"></input> <span>2022-04-11</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZUBAMSCLRA\" value=\"\"></input> <span>2022-07-25</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZUBAMSCLRA\" value=\"\"></input> <span>2022-02-28</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZUBAMSCLRA\" value=\"\"></input> <span>2022-05-09</span></label></div>\n\n:::\n:::\n\n### 4.2: Clean the aggregated data\n\nIn a similar way, clean the aggregated data by:\n\n-   Standardising names to lower case\n-   Ensuring that date of reporting is of class \"Date\"\n-   Creating a column called \"week_date\" with the week of reporting\n    starting on Monday\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\nWe can first check the class of the DateRep column, which shows us that\nit was already recognized as a date column on import.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check class of date of reporting column\nclass(mpox_agg_raw$DateRep)\n```\n:::\n\n\nThen create a new object for the clean aggregate data, and write your\ncleaning coded connected with pipes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a new object called mpox_agg which is the clean version of the raw data, applying the cleaning functions\n\nmpox_agg <- mpox_agg_raw %>% \n  \n  # standardises names and puts all into lower case\n  clean_names() %>%  \n  \n  # create week column with Monday start\n  mutate(week_date = floor_date(date_rep, \n                              unit = \"week\",\n                              week_start = \"Monday\")) \n```\n:::\n\n\n</br>\n\n</details>\n\n::: {.callout-note appearance=\"minimal\" icon=\"false\"}\n**Test yourself!**\n\n::: webex-check\n\nTake a look at the aggreate data. Which country reported the largest cumulative number of cases during the week 2022-04-11? <div class='webex-radiogroup' id='radio_WVXJKTHNMP'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_WVXJKTHNMP\" value=\"answer\"></input> <span>Country A</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_WVXJKTHNMP\" value=\"\"></input> <span>Country B</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_WVXJKTHNMP\" value=\"\"></input> <span>Country C</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_WVXJKTHNMP\" value=\"\"></input> <span>Country D</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_WVXJKTHNMP\" value=\"\"></input> <span>Country E</span></label></div>\n\n:::\n:::\n\n## Step 5: Describe outbreak by person, place, and time\n\n### 5.1: Describe total case counts by country\n\n**Task**: Using the mpox case linelist, create a table showing the total\nnumber of cases by country. This time, make the table more\npublication-friendly.\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nYou could use `tabyl()` like before, but an easy way to produce\npublication-ready tables is with the function tbl_summary() from\n{gtsummary} package. This formats the table for you. It will print to\nyour Viewer rather than the console.\n\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\nCreate a new object with the table output - as this is a key output that you can then integrate into a document later rather than just viewing for now. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create an object with the table\ncb_country_table <- mpox_linelist %>%\n\n  #select the column that we want to use in the table\n  select(country) %>% \n  \n  # create the table. No need to specify columns; it will tabulate all available columns (selected above)\n  tbl_summary() \n\n# Print the table\ncb_country_table\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"hljugtkmuz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hljugtkmuz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hljugtkmuz thead, #hljugtkmuz tbody, #hljugtkmuz tfoot, #hljugtkmuz tr, #hljugtkmuz td, #hljugtkmuz th {\n  border-style: none;\n}\n\n#hljugtkmuz p {\n  margin: 0;\n  padding: 0;\n}\n\n#hljugtkmuz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hljugtkmuz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hljugtkmuz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hljugtkmuz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hljugtkmuz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hljugtkmuz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hljugtkmuz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hljugtkmuz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hljugtkmuz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hljugtkmuz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hljugtkmuz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hljugtkmuz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hljugtkmuz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hljugtkmuz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hljugtkmuz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hljugtkmuz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hljugtkmuz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hljugtkmuz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hljugtkmuz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hljugtkmuz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hljugtkmuz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hljugtkmuz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hljugtkmuz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hljugtkmuz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hljugtkmuz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hljugtkmuz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hljugtkmuz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hljugtkmuz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hljugtkmuz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hljugtkmuz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hljugtkmuz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hljugtkmuz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hljugtkmuz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hljugtkmuz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hljugtkmuz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hljugtkmuz .gt_left {\n  text-align: left;\n}\n\n#hljugtkmuz .gt_center {\n  text-align: center;\n}\n\n#hljugtkmuz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hljugtkmuz .gt_font_normal {\n  font-weight: normal;\n}\n\n#hljugtkmuz .gt_font_bold {\n  font-weight: bold;\n}\n\n#hljugtkmuz .gt_font_italic {\n  font-style: italic;\n}\n\n#hljugtkmuz .gt_super {\n  font-size: 65%;\n}\n\n#hljugtkmuz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hljugtkmuz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hljugtkmuz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hljugtkmuz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hljugtkmuz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hljugtkmuz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hljugtkmuz .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;N = 2,000&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>N = 2,000</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">country</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    CountryA</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">816 (41%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    CountryB</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">391 (20%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    CountryC</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">474 (24%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    CountryD</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">217 (11%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    CountryE</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">102 (5.1%)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> n (%)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n</br>\n\n</details>\n\n::: {.callout-note appearance=\"minimal\" icon=\"false\"}\n**Test yourself!**\n\n::: webex-check\n\nWhat country has the largest percentage of cases? <div class='webex-radiogroup' id='radio_BTKDMUQPEC'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BTKDMUQPEC\" value=\"\"></input> <span>Country C</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BTKDMUQPEC\" value=\"\"></input> <span>Country D</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BTKDMUQPEC\" value=\"\"></input> <span>Country B</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BTKDMUQPEC\" value=\"\"></input> <span>Country E</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BTKDMUQPEC\" value=\"answer\"></input> <span>Country A</span></label></div>\n\n:::\n:::\n\n### 5.2: Describe cases over time\n\nOkay so Country A has the most cases in total based on most recent data. But how does that change look over time? \n\n**Tasks**:\n\n-   Using the mpox case linelist, create an epicurve by week of\n    notification\n-   Using the mpox case linelist, create an epicurve by week of\n    notification to enable a comparison of trends by country.\n-   Using the mpox case linelist, create a heat plot with the number of\n    cases by country and week of notification.\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nTo do the epicurve, you can use ggplot() and geom_histogram(), which\nwill automatically aggregate your data. If you are unsure on how\nggplot() works, read the EpiRhandbook chapter on [Epidemic\ncurves](https://epirhandbook.com/en/new_pages/epicurves.html).\n\nAn alternative approach is to first aggregate the number of cases by\nweek of notification. You can do this using the functions group_by() and\nsummarise() from {dplyr}. If you are unsure on how to do this, review\nthe [Grouping data](https://epirhandbook.com/en/new_pages/grouping.html)\nchapter of the EpiRhandbook.\n\nOnce you have an object with aggregated cases by week of notification,\ncreate the epicurve using ggplot(). If want a dynamic colour inside the\nbins, you need to assign the fill to the column you want to use\n(country) and place it inside the aesthetics\n\nHeat plots can be useful to understand how the epidemic evolved in\ndifferent countries. You will need to aggregate your data by country and\nweek of notification. You can do this using the functions group_by() and\nsummarise() from {dplyr}. If you are unsure on how to do this, review\nthe Grouping data chapter of the EpiRhandbook. Then, use the geom\ngeom_tile() to create a heat plot. If you're unsure on how to do this,\nread the EpiRhanbook section on [Heat\nPlots](https://epirhandbook.com/en/new_pages/heatmaps.html)\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\nThe code below creates an epicurve using ggplot() and the geom_bar() function and applies further formatting. You can plug in the column you created during the data cleaning step for the x axis. With geom_bar(), you do not need to specify the y axis as the function counts the number of rows per x axis value. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Open up the plot production with ggplot() function, specifying object and columns\nepicurve_mpox <- ggplot(data = mpox_linelist,          \n                        aes(x = week_date)) +    \n  \n  geom_bar(fill=\"darkgreen\",                     #colour inside the bins\n                 color=\"white\",                  #outline colour of the bins\n                 alpha=0.8) +                    #transparency of the bins\n  \n  scale_x_date(breaks = \"2 weeks\") +             #set the x axis labels to two week intervals\n\n  labs(title=\"Mpox cases reported in 2022 in Countries A, B, C, D, and E\",\n       subtitle = \"Date as of August 31st 2022\") +  #add a title\n  \n  theme_bw() +                                  #assign a predefined theme\n  \n  theme(axis.text = element_text(size=9),       #define the font size of the axis text\n        axis.title = element_blank(),           #remove the titles of the x and y axis \n        axis.text.x = element_text(angle=90))   #rotate the x axis text\n           \n# Print the epicurve\nepicurve_mpox\n```\n\n::: {.cell-output-display}\n![](r_practical_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nTo examine how the outbreak spread by country, add `facet_wrap()` to your ggplot code. This splits the graph into multiple smaller ones. Below, we show how we can even simply add the function to the national epicurve object. Alternatively, you could add fill = country to the aes() in the epicurve code to keep a single curve but color each bar by country. However, we don't recommend this for comparing trends, as stacked bars make it harder to see individual patterns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nepicurve_epox_country <- epicurve_mpox + \n \n   # Facet wrap to make mini-plots, specifying that you want two columns of plots. \n  facet_wrap(.~country,\n             ncol = 1) \n\n# Print the epicurve\nepicurve_epox_country\n```\n\n::: {.cell-output-display}\n![](r_practical_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Heatmap of cases by country over time\n\nhp_epox <- mpox_linelist %>% #we first group the data by country and week of notification\n  \n  group_by(country, week_date) %>% \n  \n  summarise(n_cases = n(), .groups = \"drop\") %>% \n\n  #now we can use the pipe to directly plot the resulting data from the grouping\n  \n  ggplot(aes(x = week_date,\n           y = country,           #we want the countries to be in the y axis\n           fill = n_cases)) +     #the colour of the tiles should depend on the number of cases\n  \n  geom_tile(colour = \"black\") +   #this is the outline colour of each tile\n  \n  scale_fill_gradient(            #here we define the colours we want to use in the gradient\n    low = \"lightgreen\",\n    high = \"red\") +\n  \n  scale_x_date(breaks = \"2 weeks\") +             #set the x axis labels to two week intervals\n  \n  labs(\n    title= \"Mpox cases by country and week of notification\",\n    fill = \"Number of cases\"                               \n  ) +\n  \n  theme_bw() +\n  \n  theme(legend.position = \"bottom\",             #legend position to the bottom\n        axis.text = element_text(size=9),       #define the font size of the axis\n        axis.title = element_blank(),           #remove the titles of the x and y \n        axis.text.x = element_text(angle=90))   #rotate the x axis text\n    \nhp_epox \n```\n\n::: {.cell-output-display}\n![](r_practical_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n</br>\n\n</details>\n\n### 5.3: Describe demographic characteristics\n\nNow that we have created some outputs by time and place, we should focus\non the \"person\" element. The two most important demographic\ncharacteristics are usually age and gender. In the case we are seeing,\nwe may also want to explore the sexual orientation of cases.\n\n**Task**:\n\n-   Explore the number of cases by age group and gender.\n-   Create a table with number and percentages of cases by sexual\n    orientation\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nThe easiest way to explore both columns (age_group and gender) would be\nto use the tabyl() function from {janitor}. Then, to create the age\npyramid explore the function age_pyramid() from the {apyramid} package.\nYou can find more about this function in the EpiRhandbook chapter\n[Demographic pyramids and\nLikert-scales](https://epirhandbook.com/en/new_pages/age_pyramid.html)\n\nTo create the table by sexual orientation, consider using the function\ntbl_summary() from {gtsummary}\n\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Explore gender and age group columns\ntabyl(mpox_linelist, gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  gender    n percent\n  Female   36  0.0180\n    Male 1960  0.9800\n   Other    1  0.0005\n Unknown    3  0.0015\n```\n:::\n\n```{.r .cell-code}\ntabyl(mpox_linelist, age_group)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n age_group   n percent valid_percent\n       0-9   1  0.0005  0.0005007511\n     10-19  33  0.0165  0.0165247872\n     20-29 396  0.1980  0.1982974462\n     30-39 766  0.3830  0.3835753630\n     40-49 524  0.2620  0.2623935904\n     50-59 204  0.1020  0.1021532298\n     60-69  64  0.0320  0.0320480721\n       70+   9  0.0045  0.0045067601\n      <NA>   3  0.0015            NA\n```\n:::\n\n```{.r .cell-code}\n# Table with sexual orientation \n\ntab_sor <- mpox_linelist %>% \n  \n  select(sexual_orientation) %>% \n  \n  tbl_summary(label = list(sexual_orientation ~ \"Sexual Orientation\")) \n\ntab_sor\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ywbhppwgup\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ywbhppwgup table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ywbhppwgup thead, #ywbhppwgup tbody, #ywbhppwgup tfoot, #ywbhppwgup tr, #ywbhppwgup td, #ywbhppwgup th {\n  border-style: none;\n}\n\n#ywbhppwgup p {\n  margin: 0;\n  padding: 0;\n}\n\n#ywbhppwgup .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ywbhppwgup .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ywbhppwgup .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ywbhppwgup .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ywbhppwgup .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ywbhppwgup .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ywbhppwgup .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ywbhppwgup .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ywbhppwgup .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ywbhppwgup .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ywbhppwgup .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ywbhppwgup .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ywbhppwgup .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ywbhppwgup .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ywbhppwgup .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ywbhppwgup .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ywbhppwgup .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ywbhppwgup .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ywbhppwgup .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ywbhppwgup .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ywbhppwgup .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ywbhppwgup .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ywbhppwgup .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ywbhppwgup .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ywbhppwgup .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ywbhppwgup .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ywbhppwgup .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ywbhppwgup .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ywbhppwgup .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ywbhppwgup .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ywbhppwgup .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ywbhppwgup .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ywbhppwgup .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ywbhppwgup .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ywbhppwgup .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ywbhppwgup .gt_left {\n  text-align: left;\n}\n\n#ywbhppwgup .gt_center {\n  text-align: center;\n}\n\n#ywbhppwgup .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ywbhppwgup .gt_font_normal {\n  font-weight: normal;\n}\n\n#ywbhppwgup .gt_font_bold {\n  font-weight: bold;\n}\n\n#ywbhppwgup .gt_font_italic {\n  font-style: italic;\n}\n\n#ywbhppwgup .gt_super {\n  font-size: 65%;\n}\n\n#ywbhppwgup .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ywbhppwgup .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ywbhppwgup .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ywbhppwgup .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ywbhppwgup .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ywbhppwgup .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ywbhppwgup .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;N = 2,000&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>N = 2,000</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Sexual Orientation</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Bisexual</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">7 (0.4%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Heterosexual</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">46 (2.3%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    MSM/homo or bisexual male</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">833 (42%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1,114 (56%)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> n (%)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n</br>\n\n</details>\n\n::: {.callout-note appearance=\"minimal\" icon=\"false\"}\n**Test yourself!**\n\n::: webex-check\n\nWhich demographic group is more affected by Mpox? <div class='webex-radiogroup' id='radio_FYCYUXCEAN'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_FYCYUXCEAN\" value=\"\"></input> <span>Females 60-69</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_FYCYUXCEAN\" value=\"\"></input> <span>Males 40-49</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_FYCYUXCEAN\" value=\"\"></input> <span>Females 10-19</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_FYCYUXCEAN\" value=\"answer\"></input> <span>Males 30-39</span></label></div>\n\n:::\n:::\n\n### 5.4: Describe clinical characteristics\n\nNow, let's summarise the main clinical information that we have in our\ncase-based data frame.\n\n**Tasks**:\n\n-   Create a bar plot with the proportion of each type clinical symptoms\n\n-   Create a table with the number and percentage of cases by outcome\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nTo create bar plots we can use geom_bar() or geom_col() depending on the\nnature of our data. If we aggregate first, we can use geom_col(),\notherwise we should use geom_bar(). There is a function of the\n{gtsummary} package called add_p() which enables you to easy calculate a\nstatistical test across groups. If you want to know more read the\nsection on [gtsummary\npackage](https://epirhandbook.com/en/new_pages/stat_tests.html#stats_gt)\nof the EpiRhandbook.\n\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bar plot with clinical symptoms\n\nbar_clinical <- mpox_linelist %>% \n  \n  drop_na(clinical_symptoms) %>%   # we remove those with missing clinical symptoms\n  \n  group_by(clinical_symptoms) %>% \n  \n  summarise(n_cases = n(), .groups = \"drop\") %>%\n  \n  mutate(prop=(n_cases/sum(n_cases))*100) %>%  # we create a column with proportions\n  \n  ggplot(aes(y = reorder(clinical_symptoms, prop), x = prop)) +  # the reorder function ensures that categories are ordered by proportion in the graph\n  \n  geom_col(fill = \"darkgreen\") + \n  \n  labs(\n    title= \"Frequency of clinical symptoms in Mpox cases\",\n    y = \"\",\n    x = \"Number of cases\"\n  ) +\n  \n  theme_bw() +\n  \n  theme(axis.text = element_text(size=9))       #define the font size of the axis\n\nbar_clinical  \n```\n\n::: {.cell-output-display}\n![](r_practical_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Table with number and percentage of cases by outcome\n\ntab_outcome <- mpox_linelist %>% \n  \n  select(outcome) %>% \n  \n  tbl_summary(label = list(outcome = \"Reported outcome\")) # with the argument \"label\" we can change how the column name is displayed\n\ntab_outcome\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"iklyhlccwd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#iklyhlccwd table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#iklyhlccwd thead, #iklyhlccwd tbody, #iklyhlccwd tfoot, #iklyhlccwd tr, #iklyhlccwd td, #iklyhlccwd th {\n  border-style: none;\n}\n\n#iklyhlccwd p {\n  margin: 0;\n  padding: 0;\n}\n\n#iklyhlccwd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#iklyhlccwd .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#iklyhlccwd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#iklyhlccwd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#iklyhlccwd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iklyhlccwd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iklyhlccwd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iklyhlccwd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#iklyhlccwd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#iklyhlccwd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#iklyhlccwd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#iklyhlccwd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#iklyhlccwd .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#iklyhlccwd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#iklyhlccwd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#iklyhlccwd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#iklyhlccwd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#iklyhlccwd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#iklyhlccwd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iklyhlccwd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#iklyhlccwd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#iklyhlccwd .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#iklyhlccwd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iklyhlccwd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#iklyhlccwd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#iklyhlccwd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iklyhlccwd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iklyhlccwd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#iklyhlccwd .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iklyhlccwd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#iklyhlccwd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iklyhlccwd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iklyhlccwd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iklyhlccwd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iklyhlccwd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iklyhlccwd .gt_left {\n  text-align: left;\n}\n\n#iklyhlccwd .gt_center {\n  text-align: center;\n}\n\n#iklyhlccwd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#iklyhlccwd .gt_font_normal {\n  font-weight: normal;\n}\n\n#iklyhlccwd .gt_font_bold {\n  font-weight: bold;\n}\n\n#iklyhlccwd .gt_font_italic {\n  font-style: italic;\n}\n\n#iklyhlccwd .gt_super {\n  font-size: 65%;\n}\n\n#iklyhlccwd .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#iklyhlccwd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#iklyhlccwd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#iklyhlccwd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#iklyhlccwd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#iklyhlccwd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#iklyhlccwd .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;N = 2,000&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>N = 2,000</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Reported outcome</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Alive</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1,405 (70%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">595 (30%)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> n (%)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n</br>\n\n</details>\n\n## **Step 6: Reviewing data quality**\n\nIt is important to understand how timely, complete, and valid your data\nis, if it will be the basis of understanding an outbreak and making\ndecisions. For example - you will need to be mindful of reporting delays\nwhen interpreting epicurves, and be aware of how complete different\nsources of data are compared to each other.\n\n### 6.1: Delay between date of onset, diagnosis and notification\n\n**Tasks**\n\n-   Calculate median time from symptom onset to diagnosis and from\n    diagnosis to notification, both overall and by country\n\n-   Assess visually the number of cases by calendar period and type of\n    date (onset, diagnosis and notification)\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nTo plot together the different dates you may need to transform your data\nfrom \"wide\" to \"long\" form. What we call \"pivoting\" in R. The objective\nis to have a column with the different date categories (onset, diagnosis\nand notification) and another column with their date value. If you are\nunsure on how to do this, have a look at the [Pivoting\ndata](https://epirhandbook.com/en/new_pages/pivoting.html) chapter of\nthe EpiRhandbook. Then, try to plot with the daily values, but if that's\nnot easy to interpret you may want to aggregate cases by week.\n\n</br>\n\n</details>\n\n::: {.callout-note appearance=\"minimal\" icon=\"false\"}\n**Test yourself!**\n\n::: webex-check\n\nIs there a difference in the delay from diagnosis to notification by country? <div class='webex-radiogroup' id='radio_EDYGKREBFP'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_EDYGKREBFP\" value=\"\"></input> <span>Yes</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_EDYGKREBFP\" value=\"answer\"></input> <span>No</span></label></div>\n\n:::\n:::\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Estimate delay between onset and diagnosis, and between diagnosis and notification\n\ndelay_db <- mpox_linelist %>% \n  \n  mutate(delay_diag = as.numeric(date_of_diagnosis - date_of_onset)) %>%   #we create variables with difference between dates, we transform them in numeric to be able to then calculate measures of central tendency\n  \n  mutate(delay_not = as.numeric(date_of_notification - date_of_diagnosis))\n\nsummary(delay_db$delay_diag) #the summary will give us measures of central tendency and dispersion\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n -2.000   4.000   7.000   7.758  10.000  66.000     897 \n```\n:::\n\n```{.r .cell-code}\nsummary(delay_db$delay_not)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n-46.0000  -2.0000   0.0000  -0.6078   1.0000  23.0000      715 \n```\n:::\n\n```{.r .cell-code}\ndelay_country <- delay_db %>% #here, we group by country and summarise the median to compare across countries\n  \n  group_by(country) %>% \n  \n  summarise(median_delay_diag = median(delay_diag, na.rm = T),\n            median_delay_not = median(delay_not, na.rm = T))\n\ndelay_country\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 3\n  country  median_delay_diag median_delay_not\n  <chr>                <dbl>            <dbl>\n1 CountryA                 7                0\n2 CountryB                 7                0\n3 CountryC                 6                0\n4 CountryD                 7                0\n5 CountryE                 6                0\n```\n:::\n\n```{.r .cell-code}\n# Line graph with the different dates \n\ndates_longer <- mpox_linelist %>% # use the variables of the dates and make a longer dataset. In the pivot_longer() command we select the columns which we want to expand in long format and transform the dataset\n   \n  pivot_longer(\n    \n    cols=starts_with(\"date_\"),         # all columns starting with \"date_\" will be taken \n\n    names_to = \"indicator\",            #the names of the columns will be placed in a single column called \"indicator\"\n\n    values_to = \"date\")                # the values (which are dates in this case) will be placed in a column called \"date\"\n  \n\ndates_longer_week <- dates_longer  %>% \n\n  mutate(week_date = floor_date(date, unit = \"week\", week_start = \"Monday\")) %>%  # we create a week column\n    \n  group_by(indicator, week_date) %>% \n    \n  summarise(n=n(), .groups=\"drop\") %>%   # we group and summarise to have the number of cases by date type and week\n    \n  drop_na(week_date)                     # we drop the cases with no data on dates\n\n\n\n\nplot_date_delay <-   ggplot(data = dates_longer_week,\n                            aes(x = week_date, \n                                y = n, \n                                color=indicator)) +\n  \n  geom_line(linewidth = 1.5) +\n  \n  scale_x_date(breaks = \"2 weeks\")+\n  \n  theme_bw() +\n  \n  theme(legend.position = \"bottom\", \n        axis.text = element_text(size=9),\n        axis.title = element_blank(),\n        axis.text.x = element_text(angle=90),\n        legend.title = element_blank()) +\n  labs(title=\"Mpox cases reported in 2022, by date of onset, diagnosis and notification.\")\n\nplot_date_delay\n```\n\n::: {.cell-output-display}\n![](r_practical_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n</br>\n\n</details>\n\n### 6.2: Compare case-based and aggregated data\n\n**Task**: Create a plot comparing the number of cases reported to\nthrough the case-based flow and through the aggregated flow in each\ncountry.\n\nNOTE: Take into consideration that the column on cases in the aggregated\ndata frame reports the *cumulative* number of cases.\n\n::: {.callout-note appearance=\"minimal\" icon=\"false\"}\n**Test yourself!**\n\n::: webex-check\n\nWhich country is not reporting aggregated data? <div class='webex-radiogroup' id='radio_TGJMNIXKET'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_TGJMNIXKET\" value=\"\"></input> <span>A</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_TGJMNIXKET\" value=\"\"></input> <span>B</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_TGJMNIXKET\" value=\"answer\"></input> <span>C</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_TGJMNIXKET\" value=\"\"></input> <span>D</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_TGJMNIXKET\" value=\"\"></input> <span>E</span></label></div>\n\n:::\n:::\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a data frame with the overall number of cases reported through the aggregated flux\n\nmpox_agg_country <- mpox_agg %>% \n  \n  group_by(country) %>% \n  \n  filter(date_rep == max(date_rep)) %>% # as we have cumulative data, we keep only the last week (after grouping by country)\n  \n  select(-date_rep, -week_date) %>%     # remove unnecessary columns\n\n  mutate(source = \"aggregated\")         # we create this column to distinguish the numbers from the case-based flux\n\n\n# Create a data frame with the overall number of cases reported through the case-based flux\n\nmpox_linelist_country <- mpox_linelist %>%\n  \n  group_by(country) %>% \n  \n  summarise(cases = n(), .groups = \"drop\") %>% \n  \n  mutate(source = \"case_based\")       # we create this column to distinguish the numbers from the\n  \n\n# We append both data frames. Remember this is different from merging\n\ntotal_data <- bind_rows(mpox_linelist_country, mpox_agg_country)\n\n\n# We create a graph to compare the cases reported in both sources\n\ngraph_comp <- ggplot(data = total_data,\n                     aes(x = source, \n                         y = cases, \n                         fill = source)) +\n  \n  geom_col(position = \"dodge\") +            #position dodge puts bars one next to each other, instead of \"stacked\"\n  \n  facet_wrap(~ country, scales = \"free_y\") +  # this command gives us one graph per country. The argument scales is used to allow each y axis scales to adjust to the data\n\n  scale_fill_viridis_d(\n    labels = c(\"Aggregated\", \"Case-based\")  # this function changes the colours, but with the argument \"labels\" we can change the text of each fill.\n     ) +\n  \n  \n  labs(\n    title = \"Number of cases of Mpox reported in 2022 according to source of data\",\n    fill = \"Source\",\n    x = \"\",\n    y = \"Total number of cases\"\n  ) + \n  \n  theme_bw() +\n  \n  theme(axis.text.x = element_blank(),      # we remove the text of the x axis because it is already present in the legend\n        axis.ticks.x = element_blank())     # we also remove the ticks for aesthetic purposes\n\ngraph_comp\n```\n\n::: {.cell-output-display}\n![](r_practical_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n</br>\n\n</details>\n\n## Final thoughts\n\nWell done! Through your analysis you now understand the magnitude of the\noutbreak so far, where and when it spread, which demographic groups are\nmost affected, and how the disease actually manifests in terms of\nsymptoms and severity. ECDC is very happy with your work.\n\nBy coding this up in R, this analysis should be reproducible, meaning\nyou can quickly update it with new data and keep monitoring the\noutbreak. To further practise reproducible reports, \\[link to\nRMarkdown\\].\n\n## Case study information\n\n**Authorship**\n\nOriginal authors: Xanthi Andrianou, Gianfranco Spiteri (ECDC EI Group)\\\nData source: Fictional data provided by ECDC EI Group for training\npurposes\\\n\n| Date         | Changes made                   | Version | Author                 |\n|------------------|:------------------|-----------------:|------------------|\n| October 2021 | First draft                    |       1 | Xanthi Andrianou       |\n| June 2024    | Adapted to case study template |     1.1 | Alberto Mateo Urdiales |\n\n**Terms of Use**\n\n<!-- Describe the licencing and other appropriate information about Terms of use or any other disclaimer -->\n",
    "supporting": [
      "r_practical_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\r\n<link href=\"../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/datatables-binding-0.33/datatables.js\"></script>\r\n<script src=\"../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\r\n<link href=\"../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\r\n<link href=\"../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\r\n<link href=\"../site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}