{
  "hash": "ce3e1083bb0d71226b91d678f4fc0a5a",
  "result": {
    "markdown": "---\noutput: html_document\neditor_options: \n  chunk_output_type: console\nexecute:\n  warning: false\n  error: false\nformat: \n  html: \n    css: webex.css\n    include-after-body: webex.js\n    df-print: kable\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n# An Outbreak of Gastroenteritis in Stegen, Germany (ENG) {.unnumbered} \n\n## Overview {.unnumbered}\n\n| **Case study characteristics** |                           |\n|--------------------------------|:--------------------------|\n| Name:                          | An Outbreak of Gastroenteritis in Stegen, Germany   |\n| Language:                      | English                   |\n| Tool:                          | R;                         |\n| Location:                      | Germany                   |\n| Scale:                         | Local                  |\n| Diseases:                      | GI                       |\n| Keywords:                      | GI; Stratified analysis; R |\n| Technical complexity:          | Intermediate              |\n| Methodological complexity:     | Basic              |\n# \n\n***Authorship***\\\nOriginal authors: This case study was first designed by Alain Moren and\nGilles Desve for EPIET. It is based on an investigation conducted by\nAnja Hauri, RKI, Berlin, 1998.\\\nData source: Data is fictional and was inspired by [Nygren et al.\nTick-borne encephalitis: acute clinical manifestations and severity in\n581 cases from Germany, 2018-2020. Journal of Infection. 2023 Apr\n1;86(4):369-75](https://linkinghub.elsevier.com/retrieve/pii/S0163-4453(23)00088-9)\\\nAdapted and modified by: Alicia Barrasa (EPIET), Ioannis Karagiannis\n(Public Health England - PHE), Giri Shankar (Public Health Wales),\nNiklas Willrich (Robert Koch Institute-RKI), Patrick Keating (Austrian\nAgency for Health and Food Safety-AGES), Alexander Spina (AGES), Daniel\nGardiner (PHE), Lukas Richter (AGES), Liese Van Gompel (MedEPIET),  Kostas Danis (MedEPIET) and Alberto Mateo Urdiales\n(Istituto Superiore di Sanità - ISS)\\\n\n## Instructions\n\n### Getting Help\n\nThere are several ways to get help:\n\n1)  Look for the \"hints\" and solutions (see below)\n2)  Post a question in [Applied Epi\n    Community](www.community.appliedepi.org) with reference to this case\n    study\n\n### Hints and Solutions\n\nHere is what the \"helpers\" look like:\n\n<!--Note that this is the way of including hints and explanations to the solutions -->\n\n\n```{=html}\n<!--\nNOTE: Below is the hint (all within details tags collapsed)\n-->\n```\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nHere you will see a helpful hint!\n\n</br>\n\n</details>\n\n\n```{=html}\n<!--\nNOTE: Below is the solution (all within details tags collapsed)\n-->\n```\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see the solution\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nebola_linelist %>% \n  filter(\n    age > 25,\n    district == \"Bolo\"\n  )\n```\n:::\n\n\nHere is more explanation about why the solution works.\n\n</br>\n\n</details>\n\n\n```{=html}\n<!--\nNOTE: End of solution\n-->\n```\n\n<!-- NOTE ABOUT SOLUTIONS: When using {webexercises} the solution will be automatically highlighted, so you can change (if appropriate) the feature \"Click here to see the solution\" to  \"Click here to see the explanation of the solution\" -->\n\n#### Posting a question in the Community Forum\n\n... description here about posting in Community... TO BE COMPLETED BY\nAPPLIED EPI\n\n#### Terms of Use\n\n**Disclaimer**: The information presented in this exercise and the\nassociated data files have been deliberately changed so as to facilitate\nthe acquisition of the learning objectives for fellows of EPIET, EUPHEM\nand EPIET-associated programmes. This case study was first introduced in\n2022 (see Copyright and Licence agreement for more information).\n\nYou are free:\n\n-   to Share: to copy and distribute the work\n-   to Remix: to adapt and build upon the material\n\nUnder the following conditions:\n\n-   Attribution: You must attribute the work in the manner specified by\n    the author or licensor (but not in any way that suggests that they\n    endorse you or your use of the work). The best way to do this is to\n    keep as it is the list of contributors: sources, authors and\n    reviewers.\n\n-   Share Alike: If you alter, transform, or build upon this work, you\n    may distribute the resulting work only under the same or similar\n    license to this one. Your changes must be documented. Under that\n    condition, you are allowed to add your name to the list of\n    contributors.\n\n-   Notification: If you use the work in the manner specified by the\n    author or licensor, [Walter\\@rki.de](mailto:Walterj@rki.de)\n\n-   You cannot sell this work alone but you can use it as part of a\n    teaching.\n\nWith the understanding that:\n\n-   Waiver: Any of the above conditions can be waived if you get\n    permission from the copyright holder.\n\n-   Public Domain: Where the work or any of its elements is in the\n    public domain under applicable law, that status is in no way\n    affected by the license.\n\n-   Other Rights: In no way are any of the following rights affected by\n    the license:\n\n    -   Your fair dealing or fair use rights, or other applicable\n        copyright exceptions and limitations;\n\n    -   The author's moral rights;\n\n    -   Rights other persons may have either in the work itself or in\n        how the work is used, such as publicity or privacy rights.\n\n-   Notice: For any reuse or distribution, you must make clear to others\n    the license terms of this work by keeping together this work and the\n    current license.\n\nThis licence is based on\n<http://creativecommons.org/licenses/by-sa/3.0/>\n\n### Feedback & suggestions\n\n-   You can write feedback and suggestions on this case study at the\n    [GitHub issues page](https://github.com/appliedepi/case_studies)\n-   Alternatively email us at:\n    [contact\\@appliedepi.org](mailto:contact@appliedepi.org)\n\n\\pagebreak\n\n### Version and revisions\n\nWrite date of first version\n\nWrite any revisions made to the case study\n\n| Date | Changes made                                                                                                                                                                                                                                       |                                                                                                                                    Author |\n|---------------------|:-------------------------------|------------------:|\n| 2015 | The case study has been divided in two parts: the first includes descriptive, univariable and stratified analysis as pre-module homework; the second includes logistic and binary regression (not shown here). Unnecessary toponymes were removed. |                                                               Alicia Barrasa (EPIET) and Ioannis Karagiannis (Publich Health England-PHE) |\n| 2017 | Questions were rephrased to reflect real life scenarios (rather than academic exercise)                                                                                                                                                            |                                                                         Alicia Barrasa (EPIET) and Giri Shankar (Public Health Wales-PHW) |\n| 2017 | The case study was adapted to include the help on R                                                                                                                                                                                                | Niklas Willrich (Robert Koch Institute-RKI), Patrick Keating (Austrian Agency for Health and Food Safety-AGES) and Alexander Spina (AGES) |\n|2017| Contribution to the R code|Daniel Gardiner (Public Health England-PHE) and Lukas Richter (AGES)|\n|2022|Minor revisions to the R code and explanations| |\n|2023| Major revision of the R code. R code was simplified and R tidyverse code was implemented| Liese Van Gompel (MedEPIET)|\n|2024| Revision of the R code, i.e. use of EpiStas package for univariable and multivariable analysis, simplification and harmonisation of the R code| Kostas Danis (MediPIET)|\n| 2017 | Revision of content, structure, R code and adaptation of format to Applied Epi's template of case studies | Alberto Mateo Urdiales (ISS) |\n\n\\pagebreak\n\n## Guidance\n\n### Objectives of this case study\n\nAt the end of this case study, participants should:\n\n-   know and be able to perform the fundamental steps of a descriptive statistical analysis of a foodborne outbreak (including quantitative assessment (frequency distributions, missing values, means/medians/modes, quartiles/SDs) and visualization of the data (histogram, boxplot))\n\n-   be able to perform univariate statistical analysis to identify potential vehicles of a foodborne outbreak (including risk ratios and/or odds ratios, depending on the design)\n\n-   know why and how stratification can be conducted in datasets related to an outbreak investigation\n\n-   be able to conduct a stratified analysis with respect to potential risk factors and confounders/effect modifiers\n\n\n### Previous level of expertise assumed\n\nParticipants are expected to be familiar with data management and basic analysis in R.\n\n### Preparation for the case study\n\n1.  Download folder named *stengen_mva* and extract contents in the local\n    laptop\n\n2.  Create an Rstudio project in the folder *stengen_mva* If you are unsure on\n    how to do that, read the EpiRhandbook Chapter on [R\n    projects](https://epirhandbook.com/en/new_pages/r_projects.html)\n\n3.  Inside the folder *stengen_mva*: Subfolder \"data\" contains a raw data\n    file named *tira.csv*. This is the only data file you will use in\n    this case study. In the same folder you can find the **data dictionary** with\n    a description of the dataframe variables.\n    \n4.  Subfolder scripts should be used to save any scripts related to the\n    analysis. Inside \"backup\" you will find a solution script with the\n    code of the case study named *stengen_analysis_backup.R*. \n\n5.  Subfolder \"outputs\" could be used to store all outputs (tables,\n    graphs, documents) that are the result of the analysis\n\n\n# **Part 1 - Scenario, study design and analysis plan**\n## Introduction \n\nOn 26 June 1998, the St Sebastian High School in Stegen (school A), Germany, celebrated a graduation party, where 250 to 350 participants were expected. Attendees included graduates from that school, their families and friends, teachers, 12th grade students and some graduates from a nearby school (school B).\n\nA self-service party buffet was supplied by a commercial caterer in Freiburg. Food was prepared on the day of the party and transported in a refrigerated van to the school.  \n\nFestivities started with a dinner buffet which opened from 8:30 pm onwards and were followed by a dessert buffet offered from 10 pm. The party and the buffet extended late during the night and alcoholic beverages were quite popular. All agreed it was a party to be remembered.\n\n\n## The alert\n\nOn 2nd July 1998, the Freiburg local health office reported to the Robert Koch Institute (RKI) in Berlin the occurrence of many cases of gastroenteritis following the graduation party described above. More than 100 cases were suspected among attendees and some of them were admitted to nearby hospitals. Sick people suffered from fever, nausea, diarrhoea and vomiting that lasted for several days. Most believed that the tiramisu consumed at dinner was responsible for their illness. Salmonella Enteritidis was isolated from 19 stool samples. \n\nThe Freiburg health office sent a team to investigate the kitchen facilities of the caterer. Food preparation procedures were reviewed. Food samples, except tiramisu (none was left over), were sent to the laboratory of Freiburg University. Microbiological analyses were performed on samples of the following: brown chocolate mousse, caramel cream, remoulade sauce, yoghurt dill sauce and 10 raw eggs.  \n \nThe Freiburg health office requested help from the RKI in the investigation to assess the magnitude of the outbreak and identify potential vehicle(s) and risk factors for transmission in order to better control the outbreak.\n\n\n## The study\n\nCases were defined as any person who had attended the party at St Sebastian High School who suffered from diarrhoea (≥ 3 loose stool for 24 hours) between 27 June and 29 June 1998; or who suffered from at least three of the following symptoms: vomiting, fever ≥38.5°C, nausea, abdominal pain, and headache.\n\nStudents from both schools attending the party were asked through phone interviews to provide names of persons who attended the party. \n\nOverall, 291 responded to enquiries and 103 cases were identified (attack rate: 35%). Among these cases, 84 (82%) received medical treatment and four were admitted to hospitals. Attack rates by age group were 36.6% for persons <20 years, 32.1% for persons 20 to 29 years, and 36.8% for persons older than 29 years. \n\n![Figure 1: Cases of gastroenteritis by time of onset among attendees of a high-school graduation ceremony (n=103), Germany, June 1998](../images/stengen/figure1.png)\n\n\n**QUESTION 1**. What would be your hypothesis concerning the source of the outbreak?\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see the solution\n\n</summary>\n\n</br>\n\nThe shape of the epidemic curve and the attendance to a single event (a buffet) pointed towards a foodborne outbreak related to a **point source of infection.**\n\n</br>\n\n</details>\n\n\n**QUESTION 2**. What study design would you choose to test this hypothesis?\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see the solution\n\n</summary>\n\n</br>\n\nUsing the updated list of attendants, a **retrospective cohort study** including all attendants to the party (that could be reached) was conducted. All had received a standard questionnaire asking for demographic information, signs, symptoms and duration, admission to hospital, and food and beverages consumption at the party including amount consumed. Food-specific attack rates were computed for more than 50 food items and beverages.\n\n\n</br>\n\n</details>\n\n**Question 3**. What would your overall plan of analysis be?\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see the solution\n\n</summary>\n\n</br>\n\n**Perform data cleaning**\n\n-   For each variable, look at the range, unexpected and missing values.\n\n-   Correct data using the original forms used if needed \n\n**Describe each variable**\n\n-   For each variable, describe frequency distributions including missing values and, if needed, means, median, modes, quartiles, standard deviation, outliers \n\n-   Make appropriate histograms and box plots\n\n-   Choose relevant characteristics to describe the population\n\n**Identify the outbreak vehicle if any**\n\n-   Calculate food-specific attack rates\n\n-   Look at the proportions of cases exposed\n\n-   Chose the appropriate measure of association\n\n-   Chose the appropriate statistical tests and significance level\n\n-   Calculate the percentages of cases exposed to each exposure\n\n-   Search for any dose-response relationship if appropriate\n\n-   Interpret the results\n\n**Perform a stratified analysis**\n\n-   Identify the variables that are potential effect modifiers (EM) and confounders\n\n-   Design appropriate stratification tables\n\n-   Stratify on each level taken by the EM and confounders\n\n-   Compute appropriate measurements to identify confounding and effect modification\n\n-   Conduct appropriate statistical tests\n\n-   Interpret the results\n\n**Perform a multivariable analysis**\n\n-   This will be discussed during the module.\n\n</br>\n\n</details>\n\n\n\n\n# **Part 2 - Descriptive, univariate and stratified analysis with R**\n\n### **Step 1: Set up**\n\n#### Step 1.1: Create a new R script\n\nOnce you have created an Rproject inside the \"stengen_mva\" folder (as\nspecified in the second point of the section **Preparation for the case\nstudy**). Create a new script with the name *stengen_analysis* and save it in the\nsubfolder \"scripts\". If you are familiar with Rmarkdown, you may decide\nto use this type of file instead of a standard R script.\n\n#### Step 1.2: Define R language\n\nDepending on where you are and how you carried out R installation, your\nlanguage \"locale\" might be different from the language of the graphs\nthat you want to produce. For example, a french person might have a\nfrench \"locale\". If that is the case, when creating a graph by day of\nthe week, Monday will be displayed as \"lundi\". If that french person\nwants to create an English report, as for this case study, the language\n\"locale\" should be changed.\n\n**Task**: Ensure your \"locale\" is in English and change it into English\nif it is not. If you don't know how to do this try finding it online\n(searching for online help is an important skill for R users!).\nOtherwise, see the solution below\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# To see your language locale\nSys.getlocale()\n\n# To change it into English\nSys.setlocale(\"LC_ALL\", \"English\")\n```\n:::\n\n\n</br>\n\n</details>\n\n#### Step 1.3: Install/load packages\n\nInstall and load the following packages: rio, skimr, janitor, gtsummary,\nrstatix, epitools, epiR, epikit and tidyverse.\n\nYou can find more about installing/loading packages in the\n[Packages](https://epirhandbook.com/en/new_pages/basics.html#packages)\nsection of the EpiRhandbook.\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nYou may end up using a long list of packages. Unfortunately different\npackages have functions with the same name. For example, the package\n{dplyr} (already installed with {tidyverse}) has a function called\n`select()` which we frequently use to subset columns of a data frame.\nBut other packages such as {MASS} do also have a function called\n`select()`. This could create headaches if you want to subset columns\nusing dplyr's `select()` but R thinks you're calling MASS's `select()`\n(we call this masking - `dplyr::select()` is masked by\n`MASS::select()`). Given that you are more likely to use functions from\n{tidyverse}, ensure that this is the last package in your `p_load()`\nlist so that functions from {tidyverse} (including {dplyr} functions)\nwill always \"prevail\".\n\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ensures the package \"pacman\" is installed\nif (!require(\"pacman\")) {\n     install.packages(\"pacman\") }\n\npacman::p_load(\n  \n  rio,             # to import datasets\n  skimr,           # for displaying your data\n  janitor,         # a package for data cleaning\n  gtsummary,       # to create frequency tables\n  rstatix,         # to generate summary statistics\n  epitools,        # for univariable analysis\n  epikit,          # for creating age categories\n  epiR,            # for the adjusted risk ratios across strata\n  tidyverse  # data management and visualization\n)\n```\n:::\n\n\n</br>\n\n</details>\n\n### **Step 2: Import and explore data**\n\n\n\n\n\n#### Step 2.1: Import the data \n\n**Task** Import the data frame called \"tira.csv\" inside the \"data\" subfolder. \n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nIf you are working within a project, finding the path to the dataframe\nshould be relatively straightfoward. A \".csv\" file is a \"Comma-separated Values\" file.\nYou can import this dataframe using the `read.csv()` which comes already pre-installed in R.\nHowever, we recommend that you use the **`import()`** function\nfrom {rio} because, as you may remember, this function will recognise\nthe file type and import it whether the file is from R, Stata, excel or\nmany others. If you have any doubts about importing review the [Import\nand\nexport](https://epirhandbook.com/en/new_pages/importing.html#import-data)\nchapter of the EpiRhandbook.\n</br>\n\n</details>\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Import the dataset 'tira.csv'  \ntira_raw <- import(\"data/tira.csv\") \n```\n:::\n\n\n\n</br>\n\n</details>\n\n\n\n#### Step 2.2: Explore the data \n\n**Task**: Explore the data trying to answer the following questions:\n\n\n::: webex-check\n\nQUESTION: How many rows and columns does the dataframe have? <div class='webex-radiogroup' id='radio_BFPKOXHDUC'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BFPKOXHDUC\" value=\"\"></input> <span>522 and 8</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BFPKOXHDUC\" value=\"\"></input> <span>2 and 345</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BFPKOXHDUC\" value=\"answer\"></input> <span>291 and 20</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BFPKOXHDUC\" value=\"\"></input> <span>600 and 23</span></label></div>\n\n:::\n\n\n\n::: {.webex-check}\n\n\nQUESTION: How many cases have 'age' missing? <div class='webex-radiogroup' id='radio_ZTYNQBYGWK'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZTYNQBYGWK\" value=\"answer\"></input> <span>8</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZTYNQBYGWK\" value=\"\"></input> <span>14</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZTYNQBYGWK\" value=\"\"></input> <span>1</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZTYNQBYGWK\" value=\"\"></input> <span>0</span></label></div>\n\n:::\n\n::: {.webex-check}\n\n\nQUESTION: What is the class of the column 'salmon'? <div class='webex-radiogroup' id='radio_NKCTAPJVMO'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NKCTAPJVMO\" value=\"\"></input> <span>factor</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NKCTAPJVMO\" value=\"answer\"></input> <span>integer</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NKCTAPJVMO\" value=\"\"></input> <span>character</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NKCTAPJVMO\" value=\"\"></input> <span>logical</span></label></div>\n\n:::\n\n::: {.webex-check}\n\n\nQUESTION: What percentage of attendees ate tomato? <div class='webex-radiogroup' id='radio_WXDVRNZQNZ'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_WXDVRNZQNZ\" value=\"\"></input> <span>83%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_WXDVRNZQNZ\" value=\"\"></input> <span>70%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_WXDVRNZQNZ\" value=\"answer\"></input> <span>29%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_WXDVRNZQNZ\" value=\"\"></input> <span>6%</span></label></div>\n\n:::\n\n::: {.webex-check}\n\n\nQUESTION: What is the class of the column 'dateonset'? <div class='webex-radiogroup' id='radio_ZALDWMEBHM'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZALDWMEBHM\" value=\"\"></input> <span>factor</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZALDWMEBHM\" value=\"\"></input> <span>character</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZALDWMEBHM\" value=\"answer\"></input> <span>date</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZALDWMEBHM\" value=\"\"></input> <span>numeric</span></label></div>\n\n:::\n\n::: {.webex-check}\n\n\nQUESTION: How are missing categorised in the variables 'salmon', 'horseradish' and 'pork'? <div class='webex-radiogroup' id='radio_HOMVQIUFNG'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_HOMVQIUFNG\" value=\"\"></input> <span>As &apos;NA&apos;</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_HOMVQIUFNG\" value=\"\"></input> <span>As empy spaces</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_HOMVQIUFNG\" value=\"\"></input> <span>With an &apos;Unknown&apos; cateogry</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_HOMVQIUFNG\" value=\"answer\"></input> <span>With the number 9</span></label></div>\n\n:::\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nAn efficient way to explore data is to use the function `skim()` from the {skimr} package, as it gives you all the information needed with only one command. Of course, there are several alternatives. You can also have a look at `glimpse()` from {dplyr}, for example.\nAn easy way to explore single variables that have categories is to use `tabyl()` from {janitor}\n</br>\n\n</details>\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Inspect your dataset and generate basic statistics using the skim function  \nskim(tira_raw)\n```\n\n::: {.cell-output-display}\nTable: Data summary\n\n|                         |         |\n|:------------------------|:--------|\n|Name                     |tira_raw |\n|Number of rows           |291      |\n|Number of columns        |20       |\n|_______________________  |         |\n|Column type frequency:   |         |\n|Date                     |1        |\n|numeric                  |19       |\n|________________________ |         |\n|Group variables          |None     |\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|dateonset     |       160|          0.45|1998-06-26 |1998-07-09 |1998-06-28 |       11|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|   mean|    sd| p0|  p25| p50|   p75| p100|hist                                     |\n|:-------------|---------:|-------------:|------:|-----:|--:|----:|---:|-----:|----:|:----------------------------------------|\n|uniquekey     |         0|          1.00| 146.00| 84.15|  1| 73.5| 146| 218.5|  291|▇▇▇▇▇ |\n|ill           |         0|          1.00|   0.35|  0.48|  0|  0.0|   0|   1.0|    1|▇▁▁▁▅ |\n|sex           |         0|          1.00|   0.52|  0.50|  0|  0.0|   1|   1.0|    1|▇▁▁▁▇ |\n|age           |         8|          0.97|  26.66| 14.33| 12| 18.0|  20|  27.0|   80|▇▁▂▁▁ |\n|tira          |         5|          0.98|   0.42|  0.49|  0|  0.0|   0|   1.0|    1|▇▁▁▁▆ |\n|tportion      |         5|          0.98|   0.67|  0.90|  0|  0.0|   0|   1.0|    3|▇▃▁▂▁ |\n|wmousse       |        14|          0.95|   0.26|  0.44|  0|  0.0|   0|   1.0|    1|▇▁▁▁▃ |\n|dmousse       |         4|          0.99|   0.39|  0.49|  0|  0.0|   0|   1.0|    1|▇▁▁▁▅ |\n|mportion      |        12|          0.96|   0.65|  0.90|  0|  0.0|   0|   1.0|    3|▇▂▁▂▁ |\n|beer          |        20|          0.93|   0.39|  0.49|  0|  0.0|   0|   1.0|    1|▇▁▁▁▅ |\n|redjelly      |         0|          1.00|   0.27|  0.45|  0|  0.0|   0|   1.0|    1|▇▁▁▁▃ |\n|fruitsalad    |         0|          1.00|   0.24|  0.43|  0|  0.0|   0|   0.0|    1|▇▁▁▁▂ |\n|tomato        |         0|          1.00|   0.29|  0.45|  0|  0.0|   0|   1.0|    1|▇▁▁▁▃ |\n|mince         |         0|          1.00|   0.30|  0.46|  0|  0.0|   0|   1.0|    1|▇▁▁▁▃ |\n|salmon        |         0|          1.00|   0.48|  1.12|  0|  0.0|   0|   1.0|    9|▇▁▁▁▁ |\n|horseradish   |         0|          1.00|   0.31|  0.84|  0|  0.0|   0|   1.0|    9|▇▁▁▁▁ |\n|chickenwin    |         0|          1.00|   0.29|  0.45|  0|  0.0|   0|   1.0|    1|▇▁▁▁▃ |\n|roastbeef     |         0|          1.00|   0.10|  0.30|  0|  0.0|   0|   0.0|    1|▇▁▁▁▁ |\n|pork          |         0|          1.00|   0.47|  0.86|  0|  0.0|   0|   1.0|    9|▇▁▁▁▁ |\n:::\n\n```{.r .cell-code}\n# Glimpse is an alternative to skim which gives more accurate information about the nature of the  variables\nglimpse(tira_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 291\nColumns: 20\n$ uniquekey   <int> 210, 12, 288, 186, 20, 148, 201, 106, 272, 50, 216, 141, 9~\n$ ill         <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~\n$ dateonset   <IDate> 1998-06-27, 1998-06-27, 1998-06-27, 1998-06-27, 1998-06-~\n$ sex         <int> 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1~\n$ age         <int> 18, 57, 56, 17, 19, 16, 19, 19, 40, 53, 20, 23, 17, 19, 15~\n$ tira        <int> 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~\n$ tportion    <int> 3, 1, 0, 1, 2, 2, 3, 2, 2, 1, 3, 2, 1, 1, 1, 2, 1, 2, 2, 2~\n$ wmousse     <int> 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0~\n$ dmousse     <int> 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, NA, 1, 0, 1, 0, 1, 1, 1, ~\n$ mportion    <int> 1, 1, 0, NA, 0, 1, 1, 1, 2, 1, 3, 1, 1, 0, 2, 0, 1, 2, 2, ~\n$ beer        <int> 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, NA, ~\n$ redjelly    <int> 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1~\n$ fruitsalad  <int> 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1~\n$ tomato      <int> 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0~\n$ mince       <int> 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0~\n$ salmon      <int> 0, 1, 1, 9, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0~\n$ horseradish <int> 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0~\n$ chickenwin  <int> 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0~\n$ roastbeef   <int> 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~\n$ pork        <int> 1, 0, 0, 9, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0~\n```\n:::\n\n```{.r .cell-code}\n# To see the different categories of the variables\ntabyl(tira_raw, tomato)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| tomato|   n|   percent|\n|------:|---:|---------:|\n|      0| 208| 0.7147766|\n|      1|  83| 0.2852234|\n\n</div>\n:::\n:::\n\n\n\n</br>\n\n</details>\n\n\n#### Step 2.3: Explore age in more detail \n\n**Task** Explore the age of attendees by: \n\n- Getting summary statistics\n\n- Generating a boxplot of age by illness status.\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nYou can create a boxplot with {ggplot2} by using the geom `geom_boxplot()`.  In order to create two boxes, one for each illness status, you can assign in the aesthetics the column *ill* to both the x-axis and the fill. Don't worry if it doesn't look good right now....it should look like the solution below. If you need a refresher on how ggplot works, have a look at the EpiRhandbook [Chapter](https://epirhandbook.com/new_pages/ggplot_basics.html)\n\n</br>\n\n</details>\n\n\n\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Generate summary statistics \nsummary(tira_raw$age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  12.00   18.00   20.00   26.66   27.00   80.00       8 \n```\n:::\n\n```{.r .cell-code}\n### Creating a boxplot of age by illness status\nboxplot_age <- tira_raw %>% \n  \n  ggplot(mapping = aes(x = ill,\n                       y = age,\n                       fill = ill)) + \n  \n  geom_boxplot() + \n  \n  labs(\n    title = \"Boxplot: Age distribution per illness status\",\n    x = \"Disease status\",\n    y = \"Age\",\n    fill = \"Illness (0=No;1=Yes)\"\n  ) +\n  \n  theme_bw()\n\nboxplot_age\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Continuous x aesthetic\ni did you forget `aes(group = ...)`?\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 8 rows containing non-finite values (`stat_boxplot()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: The following aesthetics were dropped during statistical transformation: fill\ni This can happen when ggplot fails to infer the correct grouping structure in\n  the data.\ni Did you forget to specify a `group` aesthetic or to convert a numerical\n  variable into a factor?\n```\n:::\n\n::: {.cell-output-display}\n![](stegen-en_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n</br>\n\n</details>\n\n::: webex-check\n\nQUESTION: Which group (ill or not ill) has more variation around age's median? <div class='webex-radiogroup' id='radio_CLLAXIURIS'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_CLLAXIURIS\" value=\"\"></input> <span>No ill</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_CLLAXIURIS\" value=\"\"></input> <span>Ill</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_CLLAXIURIS\" value=\"answer\"></input> <span>Impossible to know from this boxplot</span></label></div>\n\n:::\n\nWe were not able to create the boxplot that we aimed for. In fact, you can see that a warning message appeared in your console saying: \"Did you forget to specify a `group` aesthetic or to convert a numerical variable into a factor?\"\n\nLooks like all columns that consist of 1 (present) and 0 (absent) values are of class 'integer', including \"ill\". Integer means that they are considered numbers. However, we want them to be categories, otherwise we won't be able to carry out many of the analysis we want (including this boxplot). So, now we'll sort this out alongside other cleaning operations.  \n\n### **Step 3: Clean the data**\n\n#### Step 3.1: Transform categorical variables\n**Task**: Change all present (1) / absent (0) variables from integer to factors. Do the same for the variables that record the number of portions eaten.\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nYou can do this one by one, or you could do all at the same time using the `across()` function from {dplyr}. If you are not sure how to use the `across()` function, read the section on [Transform multiple columns](https://epirhandbook.com/en/new_pages/cleaning.html#clean_across) from the EpiRhandbook.\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntira_clean <- tira_raw %>% # tira_clean will be out clean dataframe after we have performed cleaning tasks on tira_raw\n  \n  # this would be changing one-by-one the columns into factors\n  mutate(ill = as.factor(ill)) %>% \n  \n  # this would change all columns we are interested into 'factors' in only one command\n  mutate(across(.cols = !c(uniquekey, dateonset, age), # with the exclamation mark before c() we are telling R that we want all columns, except those in the c() list, to be transformed into factors\n                .fns = ~ as.factor(.x)))\n\n\n# Check that the changes have been succesful\nglimpse(tira_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 291\nColumns: 20\n$ uniquekey   <int> 210, 12, 288, 186, 20, 148, 201, 106, 272, 50, 216, 141, 9~\n$ ill         <fct> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~\n$ dateonset   <IDate> 1998-06-27, 1998-06-27, 1998-06-27, 1998-06-27, 1998-06-~\n$ sex         <fct> 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1~\n$ age         <int> 18, 57, 56, 17, 19, 16, 19, 19, 40, 53, 20, 23, 17, 19, 15~\n$ tira        <fct> 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~\n$ tportion    <fct> 3, 1, 0, 1, 2, 2, 3, 2, 2, 1, 3, 2, 1, 1, 1, 2, 1, 2, 2, 2~\n$ wmousse     <fct> 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0~\n$ dmousse     <fct> 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, NA, 1, 0, 1, 0, 1, 1, 1, ~\n$ mportion    <fct> 1, 1, 0, NA, 0, 1, 1, 1, 2, 1, 3, 1, 1, 0, 2, 0, 1, 2, 2, ~\n$ beer        <fct> 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, NA, ~\n$ redjelly    <fct> 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1~\n$ fruitsalad  <fct> 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1~\n$ tomato      <fct> 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0~\n$ mince       <fct> 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0~\n$ salmon      <fct> 0, 1, 1, 9, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0~\n$ horseradish <fct> 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0~\n$ chickenwin  <fct> 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0~\n$ roastbeef   <fct> 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~\n$ pork        <fct> 1, 0, 0, 9, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0~\n```\n:::\n:::\n\n\n\n</br>\n\n</details>\n\n#### Step 3.2: Categorise \"missing\" as NA\nWe saw with the `skim()` overview -and in the data dictionary- that the variables *salmon*, *pork* and *horseradish* have 'missing' codified with number '9'. In most analysis and visualisations, it is very important that R considers missing data truly as \"missing\". To do that, missing data needs to be coded as NA (**without quotes**). Other codifications of missing data, such as empty spaces or the number 9 (as in this case) will mean that R will treat this data as a category or a number. For R, 9 is not different from number 1.\n\n**Task** Recode the columns salmon, pork and horseradish so that values of 9 are coded as NA. Add the new code to the cleaning pipeline initiated in the previous step\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nFor this task you can use the `mutate()` function in combination with `recode()` or `if_else()`. The former is used specifically for recoding, whereas the latter is used to create/modify columns based on logical conditions. In any case, functions like `if_else()` and `recode()` may require you to specify the type of NA (e.g., NA_character_, NA_real_, NA_integer_) to ensure that the resulting vector maintains a consistent data type. This is important because R is strongly typed, meaning that each vector must contain elements of the same type.\nIf you want to know more about recoding, read the EpiRhandbook section on [Recoding](https://epirhandbook.com/new_pages/cleaning.html#re-code-values). Regardless of the approach that you choose, add it to the cleaning pipe command you started before, so that your code is tidy.\n</br>\n\n</details>\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntira_clean <- tira_raw %>% # tira_clean will be out clean dataframe after we have performed cleaning tasks on tira_raw\n  \n  # this would be changing one-by-one the columns into factors\n  mutate(ill = as.factor(ill)) %>% \n  \n  # this would change all columns we are interested into 'factors' in only one command\n  mutate(across(.cols = !c(uniquekey, dateonset, age), # with the exclamation mark before c() we are telling R that we want all columns, except those in the c() list, to be transformed into factors\n                .fns = ~ as.factor(.x))) %>% \n  \n  # we can do all columns at the same time with across(). Here we use recode for this example \n  mutate(across(.cols = c(salmon, horseradish, pork), .fns = ~ recode(.x, \"9\" = NA_character_)))\n\n\n# Check that the changes have been succesful\ntabyl(tira_clean, pork)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|pork |   n|   percent| valid_percent|\n|:----|---:|---------:|-------------:|\n|0    | 169| 0.5807560|     0.5847751|\n|1    | 120| 0.4123711|     0.4152249|\n|NA   |   2| 0.0068729|            NA|\n\n</div>\n:::\n:::\n\n\n\n</br>\n\n</details>\n\n#### Step 3.3: Re-categorise mousse and tiramisu portions\nWe saw that there are two columns -*tportion* and *mportion*- that have four categories according to the number of portions eaten. However, exploring these columns we can see that few people ate 3 portions. The low number in this category means that it will be very difficult to have meaningful results due to the wide uncertainty that we'll find in the estimates.\n\n**Task**: Re-categorise these columns so that they have three categories: 0,1 and 2+ portions eaten. Add the new code to the cleaning pipeline initiated previously. \n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nWe will now use the `mutate()` function in combination with `if_else()`. As specified above, this function is used for simple logical recoding, which is what we want to do now. There are three \"partner\" functions called `if_else()` from {dplyr}, `ifelse()` from {base} and `fifelse()` from {data.table}. They all have the same syntax. `ifelse()` has the advantage of being embedded in R, which guarantees its stability and sustainability. `if_else()` has some advantages compared to `ifelse()` that are important in epi analysis. For example, it does not convert Date objects to numeric (which can be a headache) and verifies that both alternatives in the if and else statements are of the same class. Finally, `fifelse()` is the fastest, so it has its advantages when we're analysis a large database.\n\nIf you want to know more about simple logical recoding, have a look at the dedicated [section](https://epirhandbook.com/new_pages/cleaning.html#ifelse-and-if_else) of the EpiRhandbook.\n\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Check portion before\ntabyl(tira_clean, tportion)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|tportion |   n|   percent| valid_percent|\n|:--------|---:|---------:|-------------:|\n|0        | 165| 0.5670103|     0.5769231|\n|1        |  65| 0.2233677|     0.2272727|\n|2        |  42| 0.1443299|     0.1468531|\n|3        |  14| 0.0481100|     0.0489510|\n|NA       |   5| 0.0171821|            NA|\n\n</div>\n:::\n\n```{.r .cell-code}\ntabyl(tira_clean, mportion)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|mportion |   n|   percent| valid_percent|\n|:--------|---:|---------:|-------------:|\n|0        | 166| 0.5704467|     0.5949821|\n|1        |  55| 0.1890034|     0.1971326|\n|2        |  47| 0.1615120|     0.1684588|\n|3        |  11| 0.0378007|     0.0394265|\n|NA       |  12| 0.0412371|            NA|\n\n</div>\n:::\n\n```{.r .cell-code}\n#Run cleaning pipe line with new code\ntira_clean <- tira_raw %>% # tira_clean will be out clean dataframe after we have performed cleaning tasks on tira_raw\n  \n  # this would be changing one-by-one the columns into factors\n  mutate(ill = as.factor(ill)) %>% \n  \n  # this would change all columns we are interested into 'factors' in only one command\n  mutate(across(.cols = !c(uniquekey, dateonset, age), # with the exclamation mark before c() we are telling R that we want all columns, except those in the c() list, to be transformed into factors\n                .fns = ~ as.factor(.x))) %>% \n  \n  # we can do all columns at the same time with across(). Here we use recode for this example \n  mutate(across(.cols = c(salmon, horseradish, pork), .fns = ~ recode(.x, \"9\" = NA_character_))) %>% \n  \n  # simple logical recoding with if_else()\n  mutate(across(.cols = c(tportion, mportion), .fns = ~if_else(.x == \"3\" | .x == \"2\", \"2+\", .x)))\n\n\n#Check portion after to verify changes\ntabyl(tira_clean, tportion)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|tportion |   n|   percent| valid_percent|\n|:--------|---:|---------:|-------------:|\n|0        | 165| 0.5670103|     0.5769231|\n|1        |  65| 0.2233677|     0.2272727|\n|2+       |  56| 0.1924399|     0.1958042|\n|NA       |   5| 0.0171821|            NA|\n\n</div>\n:::\n\n```{.r .cell-code}\ntabyl(tira_clean, mportion)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|mportion |   n|   percent| valid_percent|\n|:--------|---:|---------:|-------------:|\n|0        | 166| 0.5704467|     0.5949821|\n|1        |  55| 0.1890034|     0.1971326|\n|2+       |  58| 0.1993127|     0.2078853|\n|NA       |  12| 0.0412371|            NA|\n\n</div>\n:::\n:::\n\n\n\n</br>\n\n</details>\n\n#### Step 3.4: Create age groups\n\n\n**Task**: Create a new variable with two categories (those aged < age's median and those >=age's median). **Add the code to create this new variable to the cleaning command you created above to ensure your code is tidy. Do not write multiple cleaning commands**\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nYou can  create the age group column with the function `age_categories()` from {epikit}. If you're not familiar with this function, try looking in the *Help* on how it works, or read the specific EpiRhandbook [Section](https://epirhandbook.com/new_pages/cleaning.html#age_categories)\n</br>\n\n</details>\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntira_clean <- tira_raw %>% # tira_clean will be out clean dataframe after we have performed cleaning tasks on tira_raw\n  \n  # this would be changing one-by-one the columns into factors\n  mutate(ill = as.factor(ill)) %>% \n  \n  # this would change all columns we are interested into 'factors' in only one command\n  mutate(across(.cols = !c(uniquekey, dateonset, age), # with the exclamation mark before c() we are telling R that we want all columns, except those in the c() list, to be transformed into factors\n                .fns = ~ as.factor(.x))) %>% \n  \n  # we can do all columns at the same time with across(). Here we use recode for this example \n  mutate(across(.cols = c(salmon, horseradish, pork), .fns = ~ recode(.x, \"9\" = NA_character_))) %>% \n  \n  # simple logical recoding with if_else()\n  mutate(across(.cols = c(tportion, mportion), .fns = ~if_else(.x == \"3\" | .x == \"2\", \"2+\", .x))) %>% \n  \n  # create age categories\n  mutate(age_group = age_categories(age,           # the column to use to create the cateogories \n                                    lower = 0,     # the lower value\n                                    upper = 20,    # the upper value (we want a group of 20+)\n                                    by = 20))      # as we only want two groups, this is also 20\n\n\n\n# Check that the changes have been succesful\ntabyl(tira_clean, age_group)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|age_group |   n|   percent| valid_percent|\n|:---------|---:|---------:|-------------:|\n|0-19      | 137| 0.4707904|     0.4840989|\n|20+       | 146| 0.5017182|     0.5159011|\n|NA        |   8| 0.0274914|            NA|\n\n</div>\n:::\n:::\n\n\n\n</br>\n\n</details>\n\n\n\n\n\n#### Step 3.5: Re-create the boxplot\n**Task**: Create the boxplot we tried in **Step 2.3** using the clean version of the data. Save the boxplot in the subfolder \"outputs\".\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n::: {.cell}\n\n```{.r .cell-code}\n## Boxplot of age by illness status\nboxplot_age <- tira_clean %>% \n  \n  ggplot(mapping = aes(x = ill,\n                       y = age,\n                       fill = ill)) + \n  \n  geom_boxplot() + \n  \n  labs(\n    title = \"Boxplot: Age distribution per disease status\",\n    x = \"Disease status\",\n    y = \"Age\",\n    fill = \"Illness (0=No;1=Yes)\"\n  ) +\n  \n  theme_bw()\n\nboxplot_age\n```\n\n::: {.cell-output-display}\n![](stegen-en_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n### Save the boxplot\n#### A static way of saving it\nggsave(filename = \"outputs/boxplot_age.png\", plot = boxplot_age)\n#### A dynamic way of doing it so that it contains the date of the analysis\nggsave(filename = str_glue(\"outputs/boxplot_age_\",             #First we write the beginning of the file name until the date \n                           str_replace_all(Sys.Date(), \"-\", \"\"),  #Sys.Date() gives us the date of analysis. Str_replace_all() removes all hyphens \n                           \".png\"),                               # Finally we add the ending which is the file type\n       plot = boxplot_age)\n```\n:::\n\n</br>\n\n</details>\n\n::: webex-check\n\nQUESTION: Which group (ill or not ill) has more variation around age's median? <div class='webex-radiogroup' id='radio_QJBGALECXV'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_QJBGALECXV\" value=\"\"></input> <span>No ill</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_QJBGALECXV\" value=\"answer\"></input> <span>Ill</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_QJBGALECXV\" value=\"\"></input> <span>Impossible to know from this boxplot</span></label></div>\n\n:::\n\n### **Step 4: Descriptive analysis**\n\nNow that we have explored and cleaned our data, we can start with the descriptive analysis. As you know, we normally describe the data by time, person and place. We won't do the \"place\" analysis because in this outbreak, that element is not relevant.\n\n#### Step 4.2: Analysis by time\n\n**Task**: Generate an epidemic curve with the dates of onset. Display in the x-axis each day of the study period.\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nYou should be able, by now, to create the histogram required for this epicurve. For the x-axis breaks, remember there are two distinct elements in a `ggplot()`. Inside `geom_histogram()` we can specify the `binwidth =` of the bins to the unit we want (e.g, 1 for daily, 7 for weekly etc.). This will change the whole epicurve. \nThe second element is the scale. Scales change the way the axis or the colours are displayed, but the epicurve remains the same. In this case, as we want to modify the X-axis which is a date, we should use the function `scale_x_date()` and specify inside that we want `date_breaks =` by \"day\".\nIf you are struggling, have a look at the [Epicurves](https://epirhandbook.com/new_pages/epicurves.html#epicurves-with-ggplot2) chapter of the EpiRhandbook.\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n::: {.cell}\n\n```{.r .cell-code}\ntira_clean %>% \n  \n  ggplot(mapping = aes(x = dateonset)) + \n  \n  geom_histogram(binwidth = 1,             # we assign the width of the bins to one day\n                 color = \"darkgreen\",      # color of lines around bars\n                 fill = \"lightgreen\" )  +  # color of fill within bars \n  \n  scale_x_date(date_breaks = \"day\") +      # we want each day to be shown in the x-axis\n  \n  labs(\n    title = \"Epicurve of cases by date of onset\",\n    y = \"Number of cases\",\n    x = \"\"                                 # we leave x-axis title blank because we already say in title it is date of onset\n  ) +\n  \n  theme_bw() +                             # predefined theme\n  \n  theme(axis.text.x = element_text(angle = 90)) # we change the angle of the days in the x-axis so it is readble. Important this happens at the end\n```\n\n::: {.cell-output-display}\n![](stegen-en_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n</br>\n\n</details>\n\n\n::: webex-check\n\nQUESTION: How long after the party was the peak day in cases? <div class='webex-radiogroup' id='radio_QBBHSIDVXO'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_QBBHSIDVXO\" value=\"\"></input> <span>48h</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_QBBHSIDVXO\" value=\"\"></input> <span>A week later</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_QBBHSIDVXO\" value=\"answer\"></input> <span>24h</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_QBBHSIDVXO\" value=\"\"></input> <span>The day of the party</span></label></div>\n\n:::\n\n#### Step 4.3: Analysis by person\n\n**Task**: Generate 2-by-2 tables with sex and age group by illness status\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nThere are several approaches to generate descriptive tables and cross-tabulations. You could use `tabyl()` from {janitor}, which is a very fast approach; or you could use `group_by()` in combination with `summarise()`, from {dplyr} which is the most flexible. In this case, however, we show you the solution with a very efficient approach: `tbl_summary()` from {gtsummary}\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n::: {.cell}\n\n```{.r .cell-code}\ntira_clean %>% \n  \n  select(sex, age_group, ill) %>%  # we select the columns we're interested in\n  \n  tbl_summary(by = ill, percent = \"column\") # we assign the grouping column and define that we want the percentages by column\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"obvnwqfmrf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#obvnwqfmrf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#obvnwqfmrf thead, #obvnwqfmrf tbody, #obvnwqfmrf tfoot, #obvnwqfmrf tr, #obvnwqfmrf td, #obvnwqfmrf th {\n  border-style: none;\n}\n\n#obvnwqfmrf p {\n  margin: 0;\n  padding: 0;\n}\n\n#obvnwqfmrf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#obvnwqfmrf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#obvnwqfmrf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#obvnwqfmrf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#obvnwqfmrf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#obvnwqfmrf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#obvnwqfmrf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#obvnwqfmrf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#obvnwqfmrf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#obvnwqfmrf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#obvnwqfmrf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#obvnwqfmrf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#obvnwqfmrf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#obvnwqfmrf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#obvnwqfmrf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#obvnwqfmrf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#obvnwqfmrf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#obvnwqfmrf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#obvnwqfmrf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#obvnwqfmrf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#obvnwqfmrf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#obvnwqfmrf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#obvnwqfmrf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#obvnwqfmrf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#obvnwqfmrf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#obvnwqfmrf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#obvnwqfmrf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#obvnwqfmrf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#obvnwqfmrf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#obvnwqfmrf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#obvnwqfmrf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#obvnwqfmrf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#obvnwqfmrf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#obvnwqfmrf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#obvnwqfmrf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#obvnwqfmrf .gt_left {\n  text-align: left;\n}\n\n#obvnwqfmrf .gt_center {\n  text-align: center;\n}\n\n#obvnwqfmrf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#obvnwqfmrf .gt_font_normal {\n  font-weight: normal;\n}\n\n#obvnwqfmrf .gt_font_bold {\n  font-weight: bold;\n}\n\n#obvnwqfmrf .gt_font_italic {\n  font-style: italic;\n}\n\n#obvnwqfmrf .gt_super {\n  font-size: 65%;\n}\n\n#obvnwqfmrf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#obvnwqfmrf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#obvnwqfmrf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#obvnwqfmrf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#obvnwqfmrf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#obvnwqfmrf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#obvnwqfmrf .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;0&lt;/strong&gt;, N = 188&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>0</strong>, N = 188<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;1&lt;/strong&gt;, N = 103&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>1</strong>, N = 103<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sex</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">86 (46%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">53 (51%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">102 (54%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">50 (49%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">age_group</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0-19</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">87 (48%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">50 (50%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    20+</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">96 (52%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">50 (50%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">5</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">3</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"3\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> n (%)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n</br>\n\n</details>\n\n::: webex-check\n\nQUESTION: What percentage of ill cases was female? <div class='webex-radiogroup' id='radio_CMCLTPDADS'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_CMCLTPDADS\" value=\"answer\"></input> <span>51%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_CMCLTPDADS\" value=\"\"></input> <span>49%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_CMCLTPDADS\" value=\"\"></input> <span>45%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_CMCLTPDADS\" value=\"\"></input> <span>80%</span></label></div>\n\n:::\n\n### **Step 5: Develop and test hypothesis**\n\nIn the previous step we have described the number of ill attendees by date of onset, and we have described how sex and age were distributed according to illness status. The next step in an outbreak investigation would be to develop and test hypothesis about the possible source of the outbreak.\n\n#### Step 5.1: Compute food-specific attack rates and % of cases exposed\n\n**Task**: Create 2 by 2 tables with exposure and outcome and calculate the attack rates.\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nYou could use the same approach we used before with `tbl_summary()` from {gtsummary}, but to calculate attack rates, you'll need to change from column to row percentages.\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n::: {.cell}\n\n```{.r .cell-code}\ntira_clean %>% \n  \n  select(tira, wmousse, dmousse, wmousse, beer, \n         redjelly, fruitsalad, tomato, mince, salmon,\n         horseradish, chickenwin, roastbeef, pork, ill) %>% # we select the columns we're interested in\n  \n  tbl_summary(by = ill, percent = \"row\") %>% #we assign the grouping column and define that we want the percentages by row\n  \n  add_overall()    # we add the overall counts\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"epmfjmnyek\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#epmfjmnyek table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#epmfjmnyek thead, #epmfjmnyek tbody, #epmfjmnyek tfoot, #epmfjmnyek tr, #epmfjmnyek td, #epmfjmnyek th {\n  border-style: none;\n}\n\n#epmfjmnyek p {\n  margin: 0;\n  padding: 0;\n}\n\n#epmfjmnyek .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#epmfjmnyek .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#epmfjmnyek .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#epmfjmnyek .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#epmfjmnyek .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#epmfjmnyek .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#epmfjmnyek .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#epmfjmnyek .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#epmfjmnyek .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#epmfjmnyek .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#epmfjmnyek .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#epmfjmnyek .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#epmfjmnyek .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#epmfjmnyek .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#epmfjmnyek .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#epmfjmnyek .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#epmfjmnyek .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#epmfjmnyek .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#epmfjmnyek .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#epmfjmnyek .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#epmfjmnyek .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#epmfjmnyek .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#epmfjmnyek .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#epmfjmnyek .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#epmfjmnyek .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#epmfjmnyek .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#epmfjmnyek .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#epmfjmnyek .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#epmfjmnyek .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#epmfjmnyek .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#epmfjmnyek .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#epmfjmnyek .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#epmfjmnyek .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#epmfjmnyek .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#epmfjmnyek .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#epmfjmnyek .gt_left {\n  text-align: left;\n}\n\n#epmfjmnyek .gt_center {\n  text-align: center;\n}\n\n#epmfjmnyek .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#epmfjmnyek .gt_font_normal {\n  font-weight: normal;\n}\n\n#epmfjmnyek .gt_font_bold {\n  font-weight: bold;\n}\n\n#epmfjmnyek .gt_font_italic {\n  font-style: italic;\n}\n\n#epmfjmnyek .gt_super {\n  font-size: 65%;\n}\n\n#epmfjmnyek .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#epmfjmnyek .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#epmfjmnyek .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#epmfjmnyek .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#epmfjmnyek .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#epmfjmnyek .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#epmfjmnyek .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Overall&lt;/strong&gt;, N = 291&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Overall</strong>, N = 291<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;0&lt;/strong&gt;, N = 188&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>0</strong>, N = 188<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;1&lt;/strong&gt;, N = 103&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>1</strong>, N = 103<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">tira</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">165 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">158 (96%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">7 (4.2%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">121 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">27 (22%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">94 (78%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">5</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">3</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">2</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">wmousse</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">205 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">156 (76%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">49 (24%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">72 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">23 (32%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">49 (68%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">14</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">9</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">5</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">dmousse</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">174 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">148 (85%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">26 (15%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">113 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">37 (33%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">76 (67%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">4</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">3</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">beer</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">165 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">96 (58%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">69 (42%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">106 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">76 (72%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">30 (28%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">20</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">16</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">4</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">redjelly</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">212 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">154 (73%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">58 (27%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">79 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">34 (43%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">45 (57%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">fruitsalad</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">220 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">163 (74%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">57 (26%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">71 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">25 (35%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">46 (65%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">tomato</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">208 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">140 (67%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">68 (33%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">83 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">48 (58%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">35 (42%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">mince</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">204 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">133 (65%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">71 (35%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">87 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">55 (63%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">32 (37%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">salmon</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">183 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">120 (66%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">63 (34%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">104 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">67 (64%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">37 (36%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">4</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">3</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">horseradish</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">217 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">145 (67%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">72 (33%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">72 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">42 (58%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">30 (42%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">2</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">chickenwin</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">207 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">137 (66%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">70 (34%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">84 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">51 (61%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">33 (39%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">roastbeef</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">262 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">167 (64%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">95 (36%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">29 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">21 (72%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">8 (28%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">pork</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">169 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">115 (68%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">54 (32%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">120 (100%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">72 (60%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">48 (40%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">2</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> n (%)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n</br>\n\n</details>\n\n::: webex-check\n\nQUESTION: What is the attack rate in those who ate white mousse? <div class='webex-radiogroup' id='radio_JEMRMMRQPB'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_JEMRMMRQPB\" value=\"\"></input> <span>39%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_JEMRMMRQPB\" value=\"\"></input> <span>25%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_JEMRMMRQPB\" value=\"\"></input> <span>78%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_JEMRMMRQPB\" value=\"answer\"></input> <span>68%</span></label></div>\n\n:::\n\n\n#### Step 5.2: Estimate the relative risk of the different exposures\n\nWe have calculated attack rates in exposed and unexposed, which already gives us a lot of information. For example, we see little difference in the attack rates of those who ate and did not ate salmon; but we observe a much higher attack rate among those who ate tiramisu, than among those who did not eat it. We also see a higher attack rate in those who did not drink beer than in those who drank it.\n\nTo have a better understanding of the exposures, we will now calculate relative risks.\n\n**Task**: First, estimate the relative risk for the exposure of having eaten white mousse at the dinner\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nYou could do this manually, but you could use the function `riskratio()` from the package {epitools}, which will give you a lot of interesting information, besides the RR and its 95%CI. In this function, you need first to write the exposure and then the predictor. Try reading the documentation of the function if you have any doubts.\n\n</br>\n\n</details>\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n::: {.cell}\n\n```{.r .cell-code}\n# Relative risk wmousse\nriskratio(tira_clean$wmousse, tira_clean$ill)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$data\n         Outcome\nPredictor   0  1 Total\n    0     156 49   205\n    1      23 49    72\n    Total 179 98   277\n\n$measure\n         risk ratio with 95% C.I.\nPredictor estimate    lower    upper\n        0 1.000000       NA       NA\n        1 2.847222 2.128267 3.809049\n\n$p.value\n         two-sided\nPredictor   midp.exact fisher.exact   chi.square\n        0           NA           NA           NA\n        1 4.219824e-11 5.825494e-11 1.576275e-11\n\n$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n```\n:::\n:::\n\n\n</br>\n\n</details>\n\n::: webex-check\n\nQUESTION: What is the risk of illness among those who ate white mousse compared to those who did not have this food ? <div class='webex-radiogroup' id='radio_RQOQAJFKWL'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_RQOQAJFKWL\" value=\"\"></input> <span>2.1</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_RQOQAJFKWL\" value=\"\"></input> <span>179</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_RQOQAJFKWL\" value=\"answer\"></input> <span>2.8</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_RQOQAJFKWL\" value=\"\"></input> <span>1.0</span></label></div>\n\n:::\n\n**Task**: Calculate now the risk ratio for all the other exposures to develop hypothesis of the possible source\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nYou could write the `riskratio()` function changing the exposure variable one by one. However, to save time, avoid making errors and being more efficient, you could try to use approaches that allow you to apply the same function to many different objects (e.g., multiple columns) simultaneously. There are different options for this such as *loops*, *lapply* or *purrr*. Here we give the solution with *purrr*, so if you want to explore further purrr have a look at the dedicated [section](https://epirhandbook.com/new_pages/iteration.html#iter_purrr) in the EpiRhandbook.\n</br>\n\n</details>\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n::: {.cell}\n\n```{.r .cell-code}\ntira_clean %>% \n  select(-uniquekey, -age, -age_group, -sex, -dateonset, -ill) %>% # we first remove the columns we're not interested + the outcome column\n  map(.f = ~riskratio(.x, tira_clean$ill))     # here we call the function for each column. \".x\" represents all the columns in the database that have not been removed previously\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$tira\n$tira$data\n         Outcome\nPredictor   0   1 Total\n    0     158   7   165\n    1      27  94   121\n    Total 185 101   286\n\n$tira$measure\n         risk ratio with 95% C.I.\nPredictor estimate    lower    upper\n        0  1.00000       NA       NA\n        1 18.31169 8.814202 38.04291\n\n$tira$p.value\n         two-sided\nPredictor midp.exact fisher.exact   chi.square\n        0         NA           NA           NA\n        1          0 1.794084e-41 9.939537e-38\n\n$tira$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n\n$tportion\n$tportion$data\n         Outcome\nPredictor   0   1 Total\n    0     158   7   165\n    1      21  44    65\n    2+      6  50    56\n    Total 185 101   286\n\n$tportion$measure\n         risk ratio with 95% C.I.\nPredictor estimate    lower    upper\n       0   1.00000       NA       NA\n       1  15.95604  7.58160 33.58069\n       2+ 21.04592 10.13646 43.69680\n\n$tportion$p.value\n         two-sided\nPredictor midp.exact fisher.exact   chi.square\n       0          NA           NA           NA\n       1           0 8.032814e-24 1.810033e-25\n       2+          0 5.002260e-35 3.112720e-36\n\n$tportion$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n\n$wmousse\n$wmousse$data\n         Outcome\nPredictor   0  1 Total\n    0     156 49   205\n    1      23 49    72\n    Total 179 98   277\n\n$wmousse$measure\n         risk ratio with 95% C.I.\nPredictor estimate    lower    upper\n        0 1.000000       NA       NA\n        1 2.847222 2.128267 3.809049\n\n$wmousse$p.value\n         two-sided\nPredictor   midp.exact fisher.exact   chi.square\n        0           NA           NA           NA\n        1 4.219824e-11 5.825494e-11 1.576275e-11\n\n$wmousse$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n\n$dmousse\n$dmousse$data\n         Outcome\nPredictor   0   1 Total\n    0     148  26   174\n    1      37  76   113\n    Total 185 102   287\n\n$dmousse$measure\n         risk ratio with 95% C.I.\nPredictor estimate    lower    upper\n        0 1.000000       NA       NA\n        1 4.501021 3.086945 6.562862\n\n$dmousse$p.value\n         two-sided\nPredictor midp.exact fisher.exact   chi.square\n        0         NA           NA           NA\n        1          0 1.167009e-19 1.474249e-19\n\n$dmousse$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n\n$mportion\n$mportion$data\n         Outcome\nPredictor   0  1 Total\n    0     144 22   166\n    1      17 38    55\n    2+     21 37    58\n    Total 182 97   279\n\n$mportion$measure\n         risk ratio with 95% C.I.\nPredictor estimate    lower    upper\n       0  1.000000       NA       NA\n       1  5.213223 3.399895 7.993687\n       2+ 4.813480 3.116181 7.435251\n\n$mportion$p.value\n         two-sided\nPredictor   midp.exact fisher.exact   chi.square\n       0            NA           NA           NA\n       1  1.421085e-14 1.319062e-14 7.031442e-16\n       2+ 7.656098e-13 7.069771e-13 5.375359e-14\n\n$mportion$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n\n$beer\n$beer$data\n         Outcome\nPredictor   0  1 Total\n    0      96 69   165\n    1      76 30   106\n    Total 172 99   271\n\n$beer$measure\n         risk ratio with 95% C.I.\nPredictor  estimate     lower   upper\n        0 1.0000000        NA      NA\n        1 0.6767842 0.4757688 0.96273\n\n$beer$p.value\n         two-sided\nPredictor midp.exact fisher.exact chi.square\n        0         NA           NA         NA\n        1 0.02439079   0.02806394 0.02413045\n\n$beer$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n\n$redjelly\n$redjelly$data\n         Outcome\nPredictor   0   1 Total\n    0     154  58   212\n    1      34  45    79\n    Total 188 103   291\n\n$redjelly$measure\n         risk ratio with 95% C.I.\nPredictor estimate    lower    upper\n        0  1.00000       NA       NA\n        1  2.08206 1.555917 2.786123\n\n$redjelly$p.value\n         two-sided\nPredictor   midp.exact fisher.exact   chi.square\n        0           NA           NA           NA\n        1 4.364656e-06 4.415074e-06 2.646618e-06\n\n$redjelly$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n\n$fruitsalad\n$fruitsalad$data\n         Outcome\nPredictor   0   1 Total\n    0     163  57   220\n    1      25  46    71\n    Total 188 103   291\n\n$fruitsalad$measure\n         risk ratio with 95% C.I.\nPredictor estimate    lower    upper\n        0 1.000000       NA       NA\n        1 2.500618 1.886773 3.314171\n\n$fruitsalad$p.value\n         two-sided\nPredictor   midp.exact fisher.exact   chi.square\n        0           NA           NA           NA\n        1 6.152039e-09 9.998203e-09 2.572527e-09\n\n$fruitsalad$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n\n$tomato\n$tomato$data\n         Outcome\nPredictor   0   1 Total\n    0     140  68   208\n    1      48  35    83\n    Total 188 103   291\n\n$tomato$measure\n         risk ratio with 95% C.I.\nPredictor estimate     lower    upper\n        0 1.000000        NA       NA\n        1 1.289865 0.9379601 1.773799\n\n$tomato$p.value\n         two-sided\nPredictor midp.exact fisher.exact chi.square\n        0         NA           NA         NA\n        1   0.131876    0.1368934  0.1269162\n\n$tomato$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n\n$mince\n$mince$data\n         Outcome\nPredictor   0   1 Total\n    0     133  71   204\n    1      55  32    87\n    Total 188 103   291\n\n$mince$measure\n         risk ratio with 95% C.I.\nPredictor estimate     lower    upper\n        0 1.000000        NA       NA\n        1 1.056824 0.7571858 1.475036\n\n$mince$p.value\n         two-sided\nPredictor midp.exact fisher.exact chi.square\n        0         NA           NA         NA\n        1  0.7455228    0.7893882  0.7467072\n\n$mince$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n\n$salmon\n$salmon$data\n         Outcome\nPredictor   0   1 Total\n    0     120  63   183\n    1      67  37   104\n    Total 187 100   287\n\n$salmon$measure\n         risk ratio with 95% C.I.\nPredictor estimate     lower    upper\n        0 1.000000        NA       NA\n        1 1.033425 0.7452531 1.433026\n\n$salmon$p.value\n         two-sided\nPredictor midp.exact fisher.exact chi.square\n        0         NA           NA         NA\n        1  0.8427855    0.8976422  0.8440915\n\n$salmon$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n\n$horseradish\n$horseradish$data\n         Outcome\nPredictor   0   1 Total\n    0     145  72   217\n    1      42  30    72\n    Total 187 102   289\n\n$horseradish$measure\n         risk ratio with 95% C.I.\nPredictor estimate     lower    upper\n        0 1.000000        NA       NA\n        1 1.255787 0.9008457 1.750578\n\n$horseradish$p.value\n         two-sided\nPredictor midp.exact fisher.exact chi.square\n        0         NA           NA         NA\n        1  0.1973981    0.2026013  0.1916218\n\n$horseradish$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n\n$chickenwin\n$chickenwin$data\n         Outcome\nPredictor   0   1 Total\n    0     137  70   207\n    1      51  33    84\n    Total 188 103   291\n\n$chickenwin$measure\n         risk ratio with 95% C.I.\nPredictor estimate     lower    upper\n        0 1.000000        NA       NA\n        1 1.161735 0.8376217 1.611261\n\n$chickenwin$p.value\n         two-sided\nPredictor midp.exact fisher.exact chi.square\n        0         NA           NA         NA\n        1  0.3803364    0.4176598  0.3766386\n\n$chickenwin$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n\n$roastbeef\n$roastbeef$data\n         Outcome\nPredictor   0   1 Total\n    0     167  95   262\n    1      21   8    29\n    Total 188 103   291\n\n$roastbeef$measure\n         risk ratio with 95% C.I.\nPredictor  estimate     lower    upper\n        0 1.0000000        NA       NA\n        1 0.7607985 0.4129094 1.401795\n\n$roastbeef$p.value\n         two-sided\nPredictor midp.exact fisher.exact chi.square\n        0         NA           NA         NA\n        1   0.365577    0.4172932  0.3540318\n\n$roastbeef$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n\n$pork\n$pork$data\n         Outcome\nPredictor   0   1 Total\n    0     115  54   169\n    1      72  48   120\n    Total 187 102   289\n\n$pork$measure\n         risk ratio with 95% C.I.\nPredictor estimate     lower    upper\n        0 1.000000        NA       NA\n        1 1.251852 0.9176849 1.707703\n\n$pork$p.value\n         two-sided\nPredictor midp.exact fisher.exact chi.square\n        0         NA           NA         NA\n        1  0.1620037    0.1708777  0.1583527\n\n$pork$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n```\n:::\n:::\n\n\n</br>\n\n</details>\n\n::: webex-check\n\nQUESTION: Which exposure has the highest risk ratio? <div class='webex-radiogroup' id='radio_SLFGREHPCT'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_SLFGREHPCT\" value=\"\"></input> <span>beer</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_SLFGREHPCT\" value=\"answer\"></input> <span>tiramisu</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_SLFGREHPCT\" value=\"\"></input> <span>pork</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_SLFGREHPCT\" value=\"\"></input> <span>dark mousse</span></label></div>\n\n:::\n\n\n::: webex-check\n\nQUESTION: Which of the following seems like a protective factor? <div class='webex-radiogroup' id='radio_NXSZAZMHDJ'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NXSZAZMHDJ\" value=\"answer\"></input> <span>beer</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NXSZAZMHDJ\" value=\"\"></input> <span>tiramisu</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NXSZAZMHDJ\" value=\"\"></input> <span>pork</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NXSZAZMHDJ\" value=\"\"></input> <span>dark mousse</span></label></div>\n\n:::\n\n::: webex-check\n\nQUESTION: Which of the following has a non-significant association? <div class='webex-radiogroup' id='radio_IYPXRBOXLS'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_IYPXRBOXLS\" value=\"\"></input> <span>beer</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_IYPXRBOXLS\" value=\"\"></input> <span>tiramisu</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_IYPXRBOXLS\" value=\"answer\"></input> <span>pork</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_IYPXRBOXLS\" value=\"\"></input> <span>dark mousse</span></label></div>\n\n:::\n\n::: webex-check\n\nQUESTION: Is there a dose-response in the association between illness and tiramisu? <div class='webex-radiogroup' id='radio_LNDWOVUBUW'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_LNDWOVUBUW\" value=\"answer\"></input> <span>Yes</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_LNDWOVUBUW\" value=\"\"></input> <span>No</span></label></div>\n\n:::\n\nSeveral food items seemed to be associated with the occurrence of illness; **tiramisu, dark and white chocolate mousse, fruit salad, and red jelly**. They can potentially explain up to 94, 76, 49, 46, and 45 of the 103 cases, respectively. Investigators decided to identify their respective roles in the occurrence of illness. There also seems to be a **dose-response** in the amount of tiramisu eaten, with those eating 2 or more portions having a higher risk than those eating only 1 (who had a higher risk than those who did not eat tiramisu)\n\nFrom the crude analysis, epidemiologists noticed that the occurrence of **gastroenteritis was lower among those attendants who had drunk beer.** They also decided to assess if beer had a protective effect on the occurrence of gastroenteritis.\n\n#### Step 5.3: Confounding and effect modification\n\nThe finding that beer had a protective effect on GI illness is surprising. One of your colleagues suggested that tiramisu might be confounding this association. Given that tiramisu has the highest risk ratio, it might be that the dessert is associated with the outcome (causes it) and to the exposure (those drinking beer might have preferred not to ruin its sour flavour with the sweetness of tiramisu). Another colleague disagrees and thinks that, actually, tiramisu might be an effect modifier in the relation between beer and illness.\n\nQUESTION: How would you check if tiramisu is a confounder or an effect modifier in the association between beer and illness? \n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\nTo check both things: confounding and effect modification, we should stratify our data by tiramisu consumption. Once stratified, we can calculate risk ratios in both strata and an adjusted risk ratio: **the adjusted Mantel–Haenszel risk ratio**. If this risk ratio is very different from the crude risk ratio (the overall risk ratio between beer and illness), we could say that tiramisu is confounding the association between beer and illness. We normally define as \"very different\" when: $(RRcrude/RRadjusted - 1)*100$ is larger than 10-20% difference (no strict threshold, your interpretation and expertise counts!).\n\nIf there is confounding but no effect modification, the adjusted M-H risk ratio should be different from the crude RR, but **the risk ratios in each strata -tiramisu yes and tiramisu no- should not be significantly different**. If they are significantly different then there is **effect modification**. How do we know if they are significantly different? We can run a test to tell us that called **the Mantel–Haenszel test of homogeneity**.\n</br>\n\n</details>\n\n\n\n\n**Task**: Check if tiramisu is a confounder or an effect modifier in the association between beer and illness\n\nTry doing this task with the function `epi.2by2()` from the {epiR} package. **Read very carefully the documentation of the function**. Pay special attention at how the data needs to be structured. Read the hint if you are struggling\n\n<details>\n\n<summary style=\"text-decoration: underline; color: darkgreen;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 384 512\" style=\"height:1em;width:0.75em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:gold;overflow:visible;position:relative;\"><path d=\"M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7l0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5H109c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8l0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4l0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5H226.4c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8l0 0 0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80V416H272v16c0 44.2-35.8 80-80 80z\"/></svg>`{=html} Click to read a hint\n\n</summary>\n\n</br>\n\nUnfortunately `epi.2by2()` is a very \"picky\" function. Although you can pass data into `epi.2by2()` in different formats, the easiest way is to create a new data frame grouped by the three columns that we will use: tira, beer and ill. \nYou could pass this new dataframe into `epi.2by2()` and it may work, but be careful. `epi.2by2()` will consider as *exposed* and as *ill* the first levels of your factor data, as per the image they have in the documentation and that we show you below:\n\n![](../images/stengen/epi.2by2_data.png)\nNow run this line of code `riskratio(tira_clean$beer, tira_clean$ill)` and look at the first part of the output. You should see something like this:\n\n![](../images/stengen/beer_data_before.png)\n\nAs you see, in the top left (96) we have unexposed who did not become ill, but in the previous image we saw that `epi.2by2()` will consider those in the top left (a) as exposed and ill. How to overcome this? The trick is to change the levels of the factor variables. By default, they have \"0\" as first level and \"1\" as second level. So, we can add a line that changes  the order of the levels before we groups the data (See the solution if you don't know what its meant)\n\n\n</br>\n\n</details>\n\n\n\n<details>\n\n<summary style=\"text-decoration: underline; color: red;\">\n\n`<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:red;overflow:visible;position:relative;\"><path d=\"M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z\"/></svg>`{=html}Click to see a solution (try\nit yourself first!)\n\n</summary>\n\n</br>\n\n::: {.cell}\n\n```{.r .cell-code}\n### Group the dataframe\ngroup_data <- tira_clean %>% \n  mutate(across(.cols = c(tira, beer, ill), .fns = ~factor(.x, levels = c(1,0)))) %>% # we change the order of the levels\n  group_by(tira, beer, ill) %>% # it's important to group them in this order: strata, exposure, outcome\n  summarise(n = n()) \n\n### Run the function to obtain M-H estimates\nstrat_analysis <- epi.2by2(dat = group_data, method = \"cohort.count\",  # the method specifies that we are dealing with a cohort study\n           conf.level = 0.95, outcome = \"as.columns\")                  # we set up confidence intervals to 95 and we specify that the outcome variable is a column in the data\n#Print the results\nstrat_analysis\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             Outcome +    Outcome -      Total                 Inc risk *\nExposed +           30           74        104     28.85 (20.38 to 38.55)\nExposed -           67           95        162     41.36 (33.69 to 49.35)\nTotal               97          169        266     36.47 (30.67 to 42.56)\n\n\nPoint estimates and 95% CIs:\n-------------------------------------------------------------------\nInc risk ratio (crude)                         0.70 (0.49, 0.99)\nInc risk ratio (M-H)                           0.80 (0.62, 1.03)\nInc risk ratio (crude:M-H)                     0.87\nInc odds ratio (crude)                         0.57 (0.34, 0.97)\nInc odds ratio (M-H)                           0.48 (0.22, 1.05)\nInc odds ratio (crude:M-H)                     1.19\nAttrib risk in the exposed (crude) *           -12.51 (-24.06, -0.97)\nAttrib risk in the exposed (M-H) *             -7.53 (-15.59, 0.52)\nAttrib risk (crude:M-H)                        1.66\n-------------------------------------------------------------------\n M-H test of homogeneity of IRRs: chi2(1) = 0.136 Pr>chi2 = 0.713\n M-H test of homogeneity of ORs: chi2(1) = 1.512 Pr>chi2 = 0.219\n Test that M-H adjusted OR = 1:  chi2(1) = 3.590 Pr>chi2 = 0.029\n Wald confidence limits\n M-H: Mantel-Haenszel; CI: confidence interval\n * Outcomes per 100 population units \n```\n:::\n:::\n\n\n</br>\n\n</details>\n\n\n::: webex-check\n\nQUESTION: Look at the results, what's the magnitude of the difference between the adjusted MH risk ratio and the crude one? <div class='webex-radiogroup' id='radio_PPWVHNFAET'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_PPWVHNFAET\" value=\"answer\"></input> <span>13%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_PPWVHNFAET\" value=\"\"></input> <span>87%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_PPWVHNFAET\" value=\"\"></input> <span>30%</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_PPWVHNFAET\" value=\"\"></input> <span>20%</span></label></div>\n\n:::\n\n::: webex-check\n\nQUESTION: Look at the results, is tiramisu an effect modifier in the association between beer and illness? <div class='webex-radiogroup' id='radio_VTZMIXNSFS'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_VTZMIXNSFS\" value=\"answer\"></input> <span>No</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_VTZMIXNSFS\" value=\"\"></input> <span>Yes</span></label></div>\n\n:::\n\nYou got several results. Let's now review them to make sense of them:\n\nThe first part is a table in which you get the overall table for the association between beer and illness.\nThe second part, titled *Point estimates and 95% CIs:* has different estimates depending on whether you're interested in risk ratios, odds ratios or attributable risks. As we are carrying out a cohort study, we're interested in the ones for **risk ratios**.\n\n-   **Inc risk ratio (crude)**: The crude incidence risk ratio, comparing the risk of the outcome between exposed and unexposed groups, with 95% confidence intervals. In this case, this is the overall risk of illness in those who drank beer compared to those who did not drink it.\n\n-   **Inc risk ratio (M-H):** The Mantel-Haenszel adjusted incidence risk ratio, accounting for stratification by tiramisu, with 95% confidence intervals.\n\n-   **Inc risk ratio (crude:M-H):** The ratio of the crude incidence risk ratio to the Mantel-Haenszel adjusted incidence risk ratio.\n\n\nThis is all we need to evaluate confounding. As we said before, we need to evaluate if the crude and the adjusted risk ratios are very different. We said that we can do that with the formula $(RRcrude/RRadjusted - 1)*100$. Here, the **Inc risk ratio (crude:M-H):** corresponds to the first part: $RRcrude/RRadjusted$. So we need to substract 1 and multiple by 100: (0.87-1)*100. If you do that you'll get 13%, which is borderline, but we can say that tiramisu is not massively confounding the association between beer and illness.\n\nTo know whether there is effect modification, you can check the **M-H test of homogeneity of IRRs** in the lower part of the results. As it is not significant (p = 0.713), we can conclude there is no effect modification of tiramisu on the association between beer and illness.\n\n\n\n\n",
    "supporting": [
      "stegen-en_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}