---
output: html_document
editor_options: 
  chunk_output_type: console
format: 
  html: 
    css: webex.css
    include-after-body: webex.js
---

<!-- Some considerations about about this quarto template 
-   Text within \<! \> will not show in your final document.
    -   The other parts such as slashes (///), dashes (-) and tildes (\~) are just aesthetic
    -   These comments are used to explain the code chunks.\
    -   We refer to functions in curly brackets, e.g. {dplyr} and functions end in brackets, e.g. count()\
    -   This comment will not show up when you knit the document.\
    -   You can delete them if you want.\ -->


<!--Below insert the name of the Case study. In curly brackets is the section reference name to be cross-references throughout the book -->


### TBE - Linear regression (ENG) {.unnumbered}    

### Overview {.unnumbered}



|**Case study characteristics**|      |
|------------------------------|:-----|
| Name:                     |  TBE - linear regression    |
| Language:                 |   English   |
| Tool:                     |   R   | 
| Location:                 |   Germany   |
| Scale:                    |    National  | 
| Diseases:                 |   TBE   | 
| Keywords:                 |   TBE; Linear Regression; R   | 
| Technical complexity:     |  Intermediate    | 
| Methodological complexity:|   Intermediate   | 
 

***Authorship***\
Original authors:   Teresa Nygren (RKI), Alicia Barrasa Blanco (UK FETP), Jan Walter (RKI) and Achim Dörre (RKI)\
Data source: Data was fictional; inspired by Nygren et al. Tick-borne encephalitis: acute clinical manifestations and severity in 581 cases from Germany, 2018-2020. Journal of Infection. 2023 Apr 1;86(4):369-75\
Adapted by: Liese Van Gompel (MediPIET), Joana Gomes Dias (ECDC),  Chiara Entradi (ECDC) and Alberto Mateo Urdiales (ISS)\

### Instructions

#### Getting Help

There are several ways to get help:

1)  Look for the "hints" and solutions (see below)
2)  Post a question in [Applied Epi Community](www.community.appliedepi.org) with reference to this case study



#### Hints and Solutions

Here is what the "helpers" look like:

<!--Note that this is the way of including hints and explanations to the solutions -->



```{=html}
<!--
NOTE: Below is the hint (all within details tags collapsed)
-->
```
<details>

<summary style="text-decoration: underline; color: darkgreen;">

`r fontawesome::fa("lightbulb", fill = "gold")` Click to read a hint

</summary>

</br>

Here you will see a helpful hint!

</br>

</details>

```{=html}
<!--
NOTE: Below is the solution (all within details tags collapsed)
-->
```
<details>

<summary style="text-decoration: underline; color: red;">

`r fontawesome::fa("check", fill = "red")`Click to see the solution

</summary>

</br>

```{r eval = F, echo=T}
ebola_linelist %>% 
  filter(
    age > 25,
    district == "Bolo"
  )
```

Here is more explanation about why the solution works.

</br>

</details>

```{=html}
<!--
NOTE: End of solution
-->
```

<!-- NOTE ABOUT SOLUTIONS: When using {webexercises} the solution will be automatically highlighted, so you can change (if appropriate) the feature "Click here to see the solution" to  "Click here to see the explanation of the solution" -->


#### Posting a question in the Community Forum

... description here about posting in Community... TO BE COMPLETED BY APPLIED EPI



#### Terms of Use



###  Feedback & suggestions

-   You can write feedback and suggestions on this case study at the
    [GitHub issues
    page](https://github.com/appliedepi/case_studies)
-   Alternatively email us at:
    [contact\@appliedepi.org](mailto:contact@appliedepi.org)




\pagebreak

### Version and revisions

Write date of first version

Write any revisions made to the case study

| Date    | Changes made | Author| 
|---------|:-------------|-------:|
|  2023   |  Revision R code  | Liese Van Gompel (MediPIET)       |
|  2024   |  Revision R code  |   Joana Gomes Dias and Chiara Entradi (ECDC)     |
|  2024   |  Revision of structure, format and R code  | Alberto Mateo Urdiales (ISS)    |

\pagebreak


### Guidance

#### Objectives of this case study 

Here write an introduction to the case study specifying:
      1. Background
      2. Objectives/Learning outcomes
      3. What the users of the case study will learn
      4. Online references to both R code (e.g., EpiRhandbook) and to methodological documents
      

#### Previous level of expertise assumed

Add information of previous expertise needed to follow the case study. This includes expertise on:

* Epidemiological experience (e.g., knowledge of the foundations of survival analysis)
* Software experience (e.g, basic knowledge of R or Rmarkdown)

If appropriate and possible, include references  that can help the user to understand the level of expertise assumed


#### Preparation for the case study

Include the steps needed to start replicating the analysis of the case study

For example:

1. Download folder named XXXX and extract contents in the local laptop
2. Create an Rstudio project in the folder XXXX (they already come with the project)
3. Subfolder data contains XXXX
4. Subfolder scripts should be used to save any scripts related to the analysis
5. Subfolder outputs will be used to store all outputs (tables, graphs, documents) that are the result of the analysis



## Specific to the case study

Finally, add the different sections of the case study. Remember to include questions +/- hints and solutions as appropriate. 

We acknowledge that every case study is different, so we trust you to give it the most relevant structure. However, consider including the following sections:

1. Data import\
If using R, we recommend to use the import() function from the {rio} package to import data, and the here() function from the {here} package to recreate the file path in a reproducible way.

2. Data cleaning and preparation\
If using R, we prefer, to use {dplyr} functions linked through the {magrittr} pipe. 

3. Descriptive analysis\
If relevant, include a section on descriptive analysis divided into three parts: time, place, person. If using R, for the graphs, we recommend using {ggplot2}. For tables, {flextable}

4. Analysis
If appropriate include in a separate section more advanced analysis, such as multivariate regression, time series analysis or survival analysis.

5. Interpretation and reflection
Include this section if relevant


For case studies in R: remember to be consistent with the style represented by the [EpiRhandbook](https://epirhandbook.com/en/).

Thank you for your work!
